### ISSUE TITLE
Improve "Save to Inventory" button

### ISSUE THREAD

**Issue by Atakku** [Yellow-Dog-Man/Resonite-Issues#10]
### Is your feature request related to a problem? Please describe.

As a new Resonite user I was very confused as to why I was sometimes seemingly unable to save items, and only 2 days later I've been told that the "Save to Inventory" button saves to the folder currently open and not the inventory root

### Describe the solution you'd like

It would be nice if the "Save to Inventory" button mentioned which folder (perhaps in smaller font) you are trying to save to, should really help new users understand how exactly the button works

### Describe alternatives you've considered

An alternative could be adding a "Save as", and popping up a menu where you can choose the target folder too.

**Comment by XDelta** [comment]
Part of this request has been made as a mod in the meantime https://github.com/rassi0429/Reso-SaveToWhere 
Do mind that everyone is able to see the text of the context menu and see the path.

**Comment by Psychpsyo** [comment]
Putting the current folder you have open in the context menu sounds like a security problem.
(someone might have, for example, a folder for a yet-unannounced project or an NSFW folder open that they do not expect to be visible to the entire session)

But there should still be some indication as the why you can't save. ("can't save to public folder" or similar)

**Comment by ProbablePrime** [comment]
There are a limited number of reasons that we grey that out, so I think it might be ok to do. Should be just a couple of new locale strings.

**Comment by TisFoolish** [comment]
> Putting the current folder you have open in the context menu sounds like a security problem. (someone might have, for example, a folder for a yet-unannounced project or an NSFW folder open that they do not expect or want to be visible to the entire session)
> 
> But there should still be some indication as the why you can't save. ("can't save to public folder" or similar)

Could have the text visible in user space instead of world space

**Comment by ProbablePrime** [comment]
Yeah there's actually only one reason currently, which is that you don't have permission to write to the directory.

We could surface that by editing the text of the button when this occurs and keep the text Generic e.g. "no permission to save to current directory" that at least gives users a place to "go" to search or lookup but doesn't have the security issues of showing the directory.

**Comment by TisFoolish** [comment]
> Yeah there's actually only one reason currently, which is that you don't have permission to write to the directory.
> 
> We could surface that by editing the text of the button when this occurs and keep the text Generic e.g. "no permission to save to current directory" that at least gives users a place to "go" to search or lookup but doesn't have the security issues of showing the directory.

Are there not two reasons? 1 is that the inventory isn't loaded because they've yet to open the dash tab and the other being a lack of permissions?

**Comment by ProbablePrime** [comment]
Let's leave it to me, I'll see what I can do.

**Comment by ProbablePrime** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/db4dca26-dd64-4593-90f1-53a7d74b266a)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/487b03d5-c280-4a62-9ed2-ceba47d85d35)

Pretty easy, just gotta get the text right.

**Comment by ProbablePrime** [comment]
I'd appreciate string suggestions here, we have limited space due to the context menu etc. So ideas help!

**Comment by TisFoolish** [comment]
For `NoInventory`, what about

"Can't Save
Please open Inventory"

**Comment by TisFoolish** [comment]
Hmmm, having trouble thinking of something concise for `NoWritePermission`.  We should avoid using phrases like "can't write" or "no permissions" as non technical users will not understand what these mean.

Hmm, maybe 

"Can't Save
Please Change Folders"

?

**Comment by XDelta** [comment]
"Unable to Save in current folder"

**Comment by TisFoolish** [comment]
I feel like that is less helpful than tell the user the solution, plus it doesn't fit with my suggested

"Can't Save
Please open Inventory"

**Comment by ProbablePrime** [comment]
Ill try some of these and see what it looks like. I'm not certain that we can use new lines like you've described but I will try and see what they look like.

I do agree with Foolish's comments about making it clear what the next action is. The entire issue is basically to prevent a common question that happens once or twice a month in our discord :D

**Comment by TisFoolish** [comment]
I was thinking something similar to the locomotion menu entry

**Comment by ProbablePrime** [comment]
Played around a bit: 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/a6ba9adb-15e9-4067-9b6c-a94108bf37e3)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/fc244de1-5131-4f82-8eb8-da06c0fcc745)

**Comment by TisFoolish** [comment]
Feels a bit verbose (yeah, I'm biased :P), but it works.

**Comment by JackTheFoxOtter** [comment]
Wouldn't "No Inventory" also be the case when you're not logged in?

**Comment by shiftyscales** [comment]
![image](https://private-user-images.githubusercontent.com/8791132/331850541-a6ba9adb-15e9-4067-9b6c-a94108bf37e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMjkxMDcsIm5iZiI6MTcxNjMyODgwNywicGF0aCI6Ii84NzkxMTMyLzMzMTg1MDU0MS1hNmJhOWFkYi0xNWU5LTQwNjctOWI2Yy1hOTQxMDhiZjM3ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMjIwMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWYwNjljNmY1ZmY1Y2UzYzg3ZmFkNWU5OWEwZjMwMTE1NDgwMDhmNTE3NzQ3NjE1Y2ViZjk3OTgxMWE0NzQ2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NdpU4QAaQxGX36Uyyl5ydEUnplLDE5n0Z06Pek8Tidk)

This one doesn't quite work because if the user is on the 'inventories' selection, opening the inventory tab does not resolve this issue. They would still have to select a folder they can write to.

![image](https://private-user-images.githubusercontent.com/8791132/331850563-fc244de1-5131-4f82-8eb8-da06c0fcc745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMjkxMDcsIm5iZiI6MTcxNjMyODgwNywicGF0aCI6Ii84NzkxMTMyLzMzMTg1MDU2My1mYzI0NGRlMS01MTMxLTRmODItOGViOC1kYTA2YzBmY2M3NDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMjIwMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Y5MzcxZThkNTkwYWY1ODc2MDgyOTNiOTUzYmI0NWQ3ZDEzMGM2ZTdmMGRlN2M2ZWNjN2Y0Nzg3Yzc1ZTJlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._WVUAqSIA3pyv72tYVlFIYN5WkCsCdGmrkSXOXTB6qU)

I actually think this text could cover both of the primary cases.

**Comment by ProbablePrime** [comment]
Shifty, I like it! Keeps it simple. In both cases telling you to go to your inventory and check the folder is the right fix!

**Comment by ohzee00** [comment]
Strange, I don't see either of those pictures that Shifty posted, I get a Can't Be Found error.

**Comment by shiftyscales** [comment]
Weird- they're the same pictures Prime linked above, @ohzee00. Can you see those?

**Comment by shiftyscales** [comment]
In either case- they just show the context menu with the proposed text. The top image was "Open your inventory at least once before trying to save." and the bottom image was "Unable to Save in current inventory folder."

**Comment by ohzee00** [comment]
I can see those! Though I misread, I was assuming those were edits that I couldn't see. Though I do agree with your assessment of it, the second one seems pretty clear from the get go.

**Comment by ProbablePrime** [comment]
2024.5.30.68 has this!
