### ISSUE TITLE
Stores don't propagate updates when their value changes

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1034]
### Describe the bug?

When writing to stores, they won't update their value unless you use a ContinuouslyChangingRelay. This means any FireOn node won't fire, and displays won't show the correct value.

### To Reproduce

Spawn the item from the linked folder, make sure you are either the host or put your own user into the updates timer.

resrec:///U-JackTheFoxOtter/R-0966A79198B0E4C7AAB6D2752534FB01DCA87ADE1158A5BC68AC32A07AE4F3E7

### Expected behavior

The Store should propagate updates when its value changes in the same way that the DataModelStore does, without needing to use a ContinuouslyChangingRelay.

### Screenshots

![2023-12-31 13 40 32](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/10ffc15b-483b-4db0-8f52-86808c35e885)

### Resonite Version Number

2023.12.21.1127 and Beta 2023.12.29.1306

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[J4-C - 2023.12.21.1127 - 2023-12-31 14_47_01.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13801331/J4-C.-.2023.12.21.1127.-.2023-12-31.14_47_01.log)
[J4-C - 2023.12.29.1306 - 2023-12-31 14_42_56.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13801332/J4-C.-.2023.12.29.1306.-.2023-12-31.14_42_56.log)

**Comment by Frooxius** [comment]
This is expected behavior, Stores do not provide change tracking mechanism - that's a property of the data model.

The Stores are a lower level efficient mechanism that exists outside of the data model and doesn't give you the same level of functionality, syncing and tracking as a data model store does.

I strongly recommend using them for just semi-temporary storage during computations and operation, but not for holding any state that should be persistent, tracked or synced.

**Comment by Nytra** [comment]
This makes Stores not as useful then. I was under the impression that they were like a ValueUserOverriden field for each user. However from what you said it seems like this is not the case? I would very much expect them to be like that and it doesn't really make sense that they are not IMO.

**Comment by TisFoolish** [comment]
I was under that impression as well

**Comment by Frooxius** [comment]
This is not the case, they are not part of the data model.

Stores are very useful and powerful when you use them right, they are just for different purpose than what you assumed.

They are roughly an equivalent of a field in a class instance - it persists across calls (impulses), but otherwise is not persistent or synced.

There are many important nodes that use them internally in ProtoFlux - e.g. SmoothLerp - it's used to hold the intermediary value for smoothing - this doesn't need to be synced or saved, so stores an ideal for those.

If you want ValueUserOverride functionality, you can use that with the data model store - it's already there as an existing functionality.

We do not plan to make Stores into something they're not meant to be.
