### ISSUE TITLE
Add Launch trailer splash to game startup

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#107]
### Is your feature request related to a problem? Please describe.

Current Resonite boot screen is boring

### Describe the solution you'd like

The opening to the launch trailer, seen https://www.patreon.com/posts/introducing-89643308 here, is really slick.  Before the loading bar is presented, but while content is still loading in the background, this splash or similar should be presented to the user

### Describe alternatives you've considered

would also be nice if, once implemented, this splash screen is customizable

### Additional Context

zangooseoo

**Comment by ProbablePrime** [comment]
Thank you for making this issue,

This is unfortunately not suitable. Our opening video is just designed to be a teaser, its not designed to introduce Resonite to the world.

We may make loading/start-up enhancements but these would not be simply dropping in this video.

Due to this I will unfortunately be closing this issue as not planned, thank you.
