### ISSUE TITLE
Allow dynvar components to specify root like ProtoFlux can

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#111]
### Is your feature request related to a problem? Please describe.

protoflux nodes for interacting with dynamic variables can specify a slot to search for the space from, similar components cannot, making what could be a simple component-only workflow more complex

### Describe the solution you'd like

Perhaps a “dynvar space proxy” component, that acts exactly like a dynamic variable space for its heirarchy, but has a slot reference to where the “actual” dynvar search space should start, linking the two spaces and imitating the flux node behavior.

### Describe alternatives you've considered

individual nodes could have slot references like their protoflux equivalents, however i believe this would be cumbersome for component workflows

### Additional Context

zangooseoo

**Comment by Banane9** [comment]
Acting as a proxy for the whole hierarchy may get very confusing when space names overlap.  
I'd favor variants where you can provide a Slot reference, for the most part.

Although I haven't tested yet, if those "indirect" dynamic variable accesses also update with new values like regular inputs do.
The lack of updating was a problem on the other platform.

**Comment by Frooxius** [comment]
This won't be added, I'm sorry.

It goes against the system design and the comparison is a bit flawed - ProtoFlux nodes for reading in a hierarchy react to an impulse - the read from the hierarchy is relatively expensive operation, that is manually invoked at particular point in time, rather than being continuous like components are.

The components are bound directly to the hierarchy and they listen to the events in that particular hierarchy chain to find and update their variables. However listening to another hierarchy is not something the data model supports like that, which would complicate things.

The component would have to essentially implicitly constantly search target hierarchy every frame, which would be hiding an expensive cost. Or we'd have to add a system to track and cleanup tracking in another hierarchy, which would add engineering burden.

There are already solutions for this:
- Setup the variable on the target hierarchy and proxy/copy your values instead
- Just use ProtoFlux, it's designed for this kind of purpose
