### ISSUE TITLE
Updates on busy days (US Weekends Friday - Saturday) cause disruption

### ISSUE THREAD

**Issue by kulzae** [Yellow-Dog-Man/Resonite-Issues#1139]
### Is your feature request related to a problem? Please describe.

Not really a "feature" request but fits better as this than a bug,

When the platform gets updates during busy days it causes disruption as users on incompatible versions need to update and restart

This can cause multiple issues. particularly with events that are running headlesses. these need to be taken down to update and if the update is in the middle of an event it cuts any users from further joining if they happened to start the game after the update.

having to restart in the middle of something gives users a good "stopping point" where they will go and do something else rather than continue to attend and this can harm the potential of an event

### Describe the solution you'd like

A pre planned update day, usually twords the start of the week or at least some warning a breaking update will be coming so they can be planned around. Mistakes are unavoidable and sometimes updates require several hotfixes that will compound the above issue sometimes severely if they are required updates

### Describe alternatives you've considered

Im not sure if there is an alternative to this

**Comment by TehTurk** [comment]
Throwing voice in here, I completely agree. I understand updates need to come out as they are made, but having stuff come out on a Mon/Tues(Early in the work week the better) works out for everyone as a whole. 

That or have updates be in beta for a week before push. I'm sure there are methods and approaches to this.

**Comment by ProbablePrime** [comment]
While I understand the issue with today's builds and in the past and do apologize for them.

A "release day" isn't the way I'd like to fix this, and I don't think it aligns to our long term plans too. We could swap to doing that for now, but it has a number of problems.

I've spent many years in software development and have always always hated the release day mentality in software teams. 

- It hides problems, as issues with bugs/build systems etc are not prioritized because of the "release process"
- It causes people on teams working on the project to view releases as "scary".
- It is frustrating and very stressful for engineers. There's constant pressure on the release day and leading up to it so that your work doesn't miss the train.

If a bug is affecting a large amount of users, I don't want to wait a week to deliver them a fix.

Instead(pending team discussion, but this is based on prior talks) we'll most likely be operating under a system of branches/releases that can be selected somehow within a launcher or Resonite itself.

These releases **could** look something like this:
1. Nightly/Bleeding Edge - YOU GET DA BUGS
2. Weekly - The one you want
3. Monthly - Usually for events/businesses
4. Quarterly - Usually reserved for just governments.

Most other software is doing this right now.

For some added context, I've just spent a month getting our build systems started on the path towards automation and with that I'm sure we'll see additionally stability. The work I'm doing paves the way for:
- Smoke Tests(Yo, does resonite even run) on all of our target platforms before a release is released to you guys.
- Unit Tests - Does this code actually work
- Integration Tests - Using the code, does this code based scenario succeed
- UI Tests(I actually forgot the name for this type of testing) - We program a robot to click things in the resonite window to do certain activities. In these cases the robot can't see Resonite internals.

**Comment by Geenz** [comment]
Just following up in support of Prime here- we do see the need for “channels”, and it’d be good to see some discussion and feedback on what these channels should be. Understand that we can’t really guarantee compatibility between these channels, but knowing the needs of the community for these would be good.

**Comment by TisFoolish** [comment]
What about just restricting Friday updates to only be bug fixes? No new features, optimizations, etc; only small changes.

**Comment by TehTurk** [comment]
> While I understand the issue with today's builds and in the past and do apologize for them.

That's ok, I feel bad you feeling you need to apologize for this but the gesture is appreciated. To me personally it's more just us asking what the plans are, or at least what approaches might be viable for everyone as a whole. 

I knew prior there was some pushback to have release days, but was unsure what the intended process may be. So seeing the outlined ideas and goals is a great start.

**Comment by kulzae** [comment]
> While I understand the issue with today's builds and in the past and do apologize for them.
> 
> A "release day" isn't the way I'd like to fix this, and I don't think it aligns to our long term plans too. We could swap to doing that for now, but it has a number of problems.
> 
> I've spent many years in software development and have always always hated the release day mentality in software teams.
> 
>     * It hides problems, as issues with bugs/build systems etc are not prioritized because of the "release process"
> 
>     * It causes people on teams working on the project to view releases as "scary".
> 
>     * It is frustrating and very stressful for engineers. There's constant pressure on the release day and leading up to it so that your work doesn't miss the train.
> 
>     * If a bug is affecting a large amount of users, I don't want to wait a week to deliver them a fix.
> 
> 
> Instead(pending team discussion, but this is based on prior talks) we'll most likely be operating under a system of branches/releases that can be selected somehow within a launcher or Resonite itself.
> 
> These releases **could** look something like this:
> 
>     1. Nightly/Bleeding Edge - YOU GET DA BUGS
> 
>     2. Weekly - The one you want
> 
>     3. Monthly - Usually for events/businesses
> 
>     4. Quarterly - Usually reserved for just governments.
> 
> 
> Most other software is doing this right now.
> 
> For some added context, I've just spent a month getting our build systems started on the path towards automation and with that I'm sure we'll see additionally stability. The work I'm doing paves the way for:
> 
>     * Smoke Tests(Yo, does resonite even run) on all of our target platforms before a release is released to you guys.
> 
>     * Unit Tests - Does this code actually work
> 
>     * Integration Tests - Using the code, does this code based scenario succeed
> 
>     * UI Tests(I actually forgot the name for this type of testing) - We program a robot to click things in the resonite window to do certain activities. In these cases the robot can't see Resonite internals.

I mentioned a release day as a potential solution but its not the "expected" one. the issue is the releases cause disruptions so anything that reduces the likelihood of that id see as progress. I just wanted to make the github to bring attention that its something that occurs

**Comment by Frooxius** [comment]
I think this is definitely good as a "feature" in a way - there's a lot of things we can do here to lower the impact of disruptions.

Like @ProbablePrime and @Geenz mentioned above, this is a bit more trickier than it seems at first and we'd need a good release system to provide improvements here.

To add onto this, there's a few things that make this more challenging:
- Busy days can be hard to define for this. US Friday - Saturday are busy for some, but not others. There's a lot of other things that can be disrupted too - e.g. university lectures or business events on any of the other days of the week. We've had requests to not update on other days than this range too. Honoring them all would make the update schedule very difficult on our end and sometimes we had to wait more than we were comfortable with when we did honor them. And as we grow, it will become nearly impossible
- Sometimes we're trying to get stuff out of the door as soon as we can, but because of delays, it ends up being related later than we'd like. We then face a choice between having people wait longer for fixes (which can be an ongoing disruption on its own to some users) and issues or just getting on with it and potentially causing disruption that way
- In some cases we are not aware that something will cause disruption until it gets released - some bugs are just not hit during our testing. There's better processes and automated testings we can setup on our side to help this (and we've been making some progress there), but in some cases we only hit issues once things get to the wider community, given the complexity of the content. To help with this, I'd recommend people keep an eye on #devlog channel and see when there's testing builds, to help catch things earlier

What I think our solution will look like is that we setup a system for managing builds and we have a number of branches. Then from our development side, we can push the new features, fixes and so on, as fast as we can. This will produce nightly builds, which can be available for internal testing.

For larger features and changes, we can push them into public preview branches, before they get merged to main. Once these builds are tested sufficiently, they can be scheduled to be released on main - this can be automated - so whatever makes it, makes it. From development perspective we're just making rolling updates.

The other thing that should help in a number of cases is the rework of the data model and generalization: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/702

What this will do is that for a lot of updates, we don't actually need to push a new build - the new binaries will be automatically and dynamically downloaded - you just need to join/start a session with the updated ones. This would help overall, as you'd be able to run multiple versions seamlessly too, so from user perspective there's no need to "restart to update" unless we make changes to the core.

**Comment by Frooxius** [comment]
@TisFoolish That can be difficult, because we'd have to spend more time separating out those out from other changes that were done over the week - which is time we need to take away from implementing features and bugfixes - and we already have very little of it.

I don't think it'd solve the problem anyways, because bugfixes can cause disruptions too.

**Comment by stiefeljackal** [comment]
Having different channels is a good idea to have as you can have that one group verify fixes or provide QA. You do technically have them right now since there is the **prerelease** option in Steam's Betas section, which was used to test the ProtoFlux update.

A monthly channel may not be a bad idea to utilize as that will cause less disruptions for events or presentations that use Resonite. The question that should be answered for that is "How can a client on a Weekly schedule join a session that is on a Monthly schedule due to the compatibility check?" I think it can be solved, but it will be tricky and will require thought.

Hotfixes and vulnerabilities should be the only exceptions to the channel rule as those should be pushed to all channels as soon as possible, especially critical vulnerabilities.

Having the required unit tests, integration tests, and e2e tests will also help mitigate issues, so I am glad that was mentioned.

> UI Tests(I actually forgot the name for this type of testing) - We program a robot to click things in the resonite window to do certain activities. In these cases the robot can't see Resonite internals.

@ProbablePrime E2E (End-to-End) Tests is the name you are looking for.

**Comment by Frooxius** [comment]
Yes, the prerelease channel on Steam serves a bit of as a "primitive" version of those. The update that was released today was there as well, but unfortunately we did not run into issues with the changes until it went live and hit broader community.

For the compatibility, there are two things in post I mentioned above:
- The system for managing builds will let you switch between them more easily
- With the data model rework, unless we made changes to the core (which the goal would be to make it rare), you'll simply just join a session with the more up to date binaries

**Comment by stiefeljackal** [comment]
> The update that was released today was there as well, but unfortunately we did not run into issues with the changes until it went live and hit broader community.

That makes sense. Today's issue mainly hit clients and servers that were using Linux, so I can see how this was not found out in the **prerelease** channel due to the small number of clients or servers that use Linux. When you have your full suite of automated tests, those tests should help prevent this.

**Comment by Frooxius** [comment]
Yeah, those will definitely help with this. We can have automated processes run a bunch of smoke tests on those, so they get caught very early. Right now it relies on manual testing. 

It's part of why the push to CI/CD we've been doing so important too - it allows us to actually implement those tests and automate this, which should help prevent a number disruptions as well.

**Comment by o6uipi** [comment]
The main point here is that the updates are being released at random and that is what's causing the disruption that we're having issues with

let's rewind from the release day thing and think about how the updates are organized.  You could simply set a time every day that updates would be released if they are going to be released constantly.  The point is that you want it to be CONSISTENT so that everyone who plays the game knows to plan around that.  You can also set different priorities of updates so maybe feature updates can be released weekly/monthly on a specific day, and significant patches can be released daily at a specific time, it doesn't have to follow any specific pattern or be restricted to one single solution.  You don't have to "rush" developers to release patches at a specific time because they can just schedule it for the next day's predetermined release time frame.

You already organized specific times that you do resonite livestreams so people know to expect a stream at that time, why not set up the same thing for update scheduling?

**Comment by Frooxius** [comment]
I understand the point, we definitely want to provide consistency like that and fewer disruptions. 

What we're trying to say above is that it's more complicated problem than just setting a time for release - we need to implement tooling and other changes into our development process to be able to achieve that.

For example the release channels and the tooling for those would allow for that to happen, but without that tooling, it's very difficult to achieve those (we'd have to manage and keep track of them all by hand) and would add even more stress and workload on our end - and we already have a bit too much to deal with than is healthy.

It's not as simple as setting a time every day for the release, because unlike the live streams, development work is highly irregular and way less predictable. Often things take longer than we'd want, which can end up pushing other things out of the way. 

Sometimes those other things have a high urgency to get out, which makes planning difficult too and we operate on "Get this out ASAP" mode - in this recent case for example, there were some fixes that needed to get done that were causing some people being unable to access their accounts at all and some diagnostics that we needed to add for event, but we missed that deadline unfortunately.

Sometimes there's work items that pop out of nowhere, that we didn't plan for and disrupt our work schedule too, especially if they're causing ongoing issues that might get worse as time goes.

It's challenging to deal with those in development when we have deal with a lot of these cases manually, which is why we need the tooling to be able to do that efficiently and allow for fewer disruptions. The work on CI/CD has been moving us towards that. There's still a lot more to do though.

All in all, I'm sorry for the disruptions, it's something we do want to improve, but we're a bit strained and a small team, so please bear with us in the meanwhile.

**Comment by TehTurk** [comment]
@o6upi Because a livestream and updating a program are different tasks so to speak and have their various weight and processes? 

I'm happy with what Prime outlined, and what Geenz, Froox and others have chimed in. Even Kulza pointed out the issue but ultimately wasn't demanding a particular solution, nor I. Its ultimately up to what team decides works best for them and community accepts. I'm fine with waiting as they work on their tooling and processes to facilitate that.

**Comment by o6uipi** [comment]
Yes obviously designing a game is different than going live on twitch.  The point I was making is that they are there so people know to expect it at that specific time.

For Froox, I do understand that there is a lot of extra stuff that goes on in the background before releases are posted.  If it's something that can be incorporated into the release channels in the future that would be helpful.  I have previously worked in project management so I know that tasks rarely stay on the timeline you set for them and cause disruptions with other important work that has specific deadlines.

Do you already have a task priority chart for development work?  We used a matrix to determine what the risk / priority was of everything needing to be worked on and that helped with releasing some of the strain of having to juggle multiple tasks and deadlines together.  It also helps any time problems show up at the last minute because you can immediately rank where it is on the priority list to determine when you should start on it.  But that only works if you have a standardized table of how you classify the priorities and outcomes.  Either way, we're just suggesting that hopefully in the future everything is organized enough that we can switch to the "scheduled update" model to allow users to deconflict reliably.

**Comment by shiftyscales** [comment]
Since the issue was created, Frooxius had created #1212. The underlying needs of this issue are best met by that issue, as such I will be closing and merging this issue into it. Thank you for your feedback.
