### ISSUE TITLE
Add New IsUserInNoClipNode to Protoflux Locomotion Nodes

### ISSUE THREAD

**Issue by Xlinka** [Yellow-Dog-Man/Resonite-Issues#1225]
### Is your feature request related to a problem? Please describe.

Some users of the game need a way to detect when a player is using NoClip locomotion for debugging purposes or for gameplay mechanics. Currently, there is no built-in node to check this in the Protoflux system. Without making a system first with multiple nodes to check the locomotion type.

### Describe the solution you'd like

this is proven working code from my plugin

```cs using FrooxEngine;
using ProtoFlux.Core;
using ProtoFlux.Runtimes.Execution;

namespace FrooxEngine.ProtoFlux.Locomotion
{
    [ContinuouslyChanging]
    [NodeCategory("ProtoFlux/Obsidian/Locomotion")]
    public class IsUserInNoClipNode : ValueFunctionNode<ExecutionContext, bool>
    {
        public readonly ObjectInput<User> User;

        protected override bool Compute(ExecutionContext context)
        {
            User user = User.Evaluate(context);
            if (user == null)
            {
                return false;
            }

            LocomotionController locomotionController = user.Root?.GetRegisteredComponent<LocomotionController>();
            if (locomotionController == null)
            {
                return false;
            }

            return locomotionController.ActiveModule.GetType() == typeof(NoclipLocomotion);
        }
    }
}
```

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/22996716/02e3c33b-15ba-4128-8013-1adc22299c5f

### Describe alternatives you've considered

getting the type and comparing it against the word noclip but is a unnecessary amount of nodes 

### Additional Context

Adding this node will greatly enhance our ability to create complex game mechanics and provide better in-game support for both developers and players.

**Comment by Frooxius** [comment]
There is a way to get the locomotion module using the "Get Active Locomotion Module".

I'm not sure if we'd add node for no-clip specifically, because there are several locomotion modules and more might be added over time (especially once you can make custom ones) and this approach is not scalable, while checking the type of the module is.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/efa90e89-51ea-440d-ba75-338523224fae)

The main issue is that the Type input has no UI right now, so you can't plop in the locomotion module type you want to compare against. I can see about picking that one up.

**Comment by Xlinka** [comment]
A type input for what type I would like would be nice but would this work with custom Locomotion people have added to their avatars ?

**Comment by Frooxius** [comment]
The type has already been implemented, so you should be able to make that check happen now.

What kind of custom locomotion do you mean in this case?

Regardless of that though, having this as a single node wouldn't help, because what I showed above would essentially be what the node does inside.
