### ISSUE TITLE
Graphics options

### ISSUE THREAD

**Issue by InconsolableCellist** [Yellow-Dog-Man/Resonite-Issues#13]
### Is your feature request related to a problem? Please describe.

Currently there doesn't seem to be a way to change common graphics options.

### Describe the solution you'd like

I'd like to see an additional tab in settings that allow me to change graphics settings, such as resolution, anti-aliasing, etc.

### Describe alternatives you've considered

I believe some of these settings can be changed in the NVIDIA Control Panel, but this is not ideal and it's not entirely clear that they're working. 

### Additional Context

I think perhaps that the render resolution is determined by your monitor resolution rather than headset resolution, as it seemed to be very low res on my 1080p monitor until I changed the screen resolution to 4k. I was running it with a Quest Pro but before doing that change, the game looked super jaggy and low res.

**Comment by Atakku** [comment]
A setting to toggle Motion smoothing on desktop would be great too
As well as reorganizing the whole Options tab into multiple sub-tabs, decluttering the whole thing and potentially adding search

**Comment by XDelta** [comment]
Some graphic related settings can be set using Command line arguments. Several of the Unity Standalone Player ones work.

As example `-monitor N` to have the game start on a specified monitor instead of the default
`-screen-fullscreen 0` override fullscreen to start in windowed mode
`-screen-height` and `-screen-width` can be used to manually set the resolution the game runs in.

More info on these and other commands can be found in [unity's manual](https://docs.unity3d.com/2019.3/Documentation/Manual/CommandLineArguments.html)

**Comment by Frooxius** [comment]
A bunch of these were added in 2024.4.18.1398!

I'm keeping this open as I plan to add a few more (like the resolution / fullscreen).

**Comment by Frooxius** [comment]
Added the resolution options in 2024.4.30.495 now. Closing this now. THanks!
