### ISSUE TITLE
Better Full Body Tracking (My FBT wishlist and comparisons!)

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#130]
### Is your feature request related to a problem? Please describe.

It's been a huge problem for many people, but the full body tracking for Resonite is really old, and should definitely be reworked at some point. Other platforms like VRC and CVR have great full body tracking, with instant set up and easy calibration. This is to the point where people outright refuse to play Resonite because of the full body tracking, And when you calibrate, It can really be a pain if your avatar isn't entirely proportional.

Some examples of problems i've noticed: 

(Note, this is on a Valve Index with controllers and three vive trackers, and these models have the exact same rig in both platforms.)

When laying on your side, your leg and knee can end up inverting, which can cause the entire leg to bend backwards, and your chest ends up facing an odd direction.

The spine doesn't bend properly if your IRL hip is rotated. This causes issues especially with an avatar like the chibi bestboi, which is not very IRL proportional.

Moving your head side to side makes your chest go side to side in a strange way, unless you turn down RotateChestByHands in the IK to 0.

There are no limits on how much the IK can bend, This causes a lot of issues.

The chest caves in if you look up, this is an issue unless you calibrate it in a certain way, though that way is really not documented well, and you can't really solve it fully.

If you bring the hip down, the spine always stays straight, which for some of my avatars does work well but nonetheless it's not proper (i'd love to have the ability to change how much your spine can bend like CVR)

Here's a video i made of some common weirdness i've experienced in Resonite. (Note, on the chibi bestboi i'm using FBT+ in resonite, it tries to compensate for when you move your head up and down by moving the hip up and down, and in VRC i'm actually using lock hip mode.  (Sorry i had to bitcrush it to hell because of github.)

Granted this is just a small smidge of what the IK does, this pose is very problematic.

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/311be695-d6dd-49e9-afb6-9471839310c2

### Describe the solution you'd like

Some type of IK update or rewrite, and much easier calibration, not having to calibrate the avatar by default too.

Would like the calibration reference to follow your head, and have it so the IK is a bit more like VRCs.
I would also love the ability to change stuff like:

How much the spine bends when I rotate my hip

An ability to lock your avatar's head to be always where the headset is (so the hip can move up and down depending if you look up or down if you want, and Before you tell me about HeadMaxFixDistance, no. it stretches the neck and it looks awful) and an option to lock to hip as well, but still keeping the head and spine looking natural and not caving in every time you look up and down

### Describe alternatives you've considered

Writing own IK in ProtoFlux, literally learning IK from scratch, both though I really don't know how to do. I've also messed with a lot of the IK settings, although none of them are able to help with my problems.

### Additional Context

If an IK rework is going to be done, i'd recommend checking out VRchat's IK for inspiration.

**Comment by FlyingStitchman** [comment]
Hello,

I'm stitch and I have 11 point tracking for context. I also
enjoy dancing and having very accurate avatar proportions/movement
to my irl self.

Even though I have 11 point tracking, most of the issues I talk
about should be hugely reduced with 6 point tracking, even if 
they cannot be completely fixed

I wanna add that a number of issues that likely are redundant, but 
thought having them in a centralized location would be helpful.

Some of it is self-explanatory, others not so much; please ask 
for clarification on any part if there is still confusion.

There are also a few things that can be done in game already, but I
believe should not require setting up (such as walking animations).

I also feel that taking a system like IK 2.0 (VRC) where you can
select whether hips/head/all trackers are 100% accurate would 
be a good addition to please groups like me who want perfection, 
but also allow others that don't care as much to not suffer 
breakage due to that.

Note:
I am going to refine this and add videos over time.

## Avatar Stuff

Avatar creation issues with FBT

* UpperChest Support
* Hands based on Hand Bone (instead of hand positions in creator)
* Head based on Head Bone (instead of head position in creator)
* Twist Bones Automatic Setup

## Calibration

Calib Issues with FBT

* Head-Locked Placement of Calibrator
* One Trigger Calibration (option)
* Graceful Failover of Lost tracking/ Disconnected Trackers (aka flying hip)
* Walking Animation Toggle
* Selective Disabling of Trackers 
  * eg. disable elbows or disable all trackers

## Spine

Issues with hips through neck of the IK

* Chest Position/Rotation does not follow Tracker
* Hips Position/Rotation does not follow Tracker
  * Aka Very Stiff Spine issues
  * Also, most of the issues after stem from these
    * I thought giving Context would be beneficial
* Chest crunches backwards when leaning backwards
* Chest does not crunch down far enough when crunching forwards
* Chest Cannot Crunch Sideways Far enough
* Hips does not crunch well either
* Gamer neck
  * When the neck crunches forward a lot when just standing)
## Joints

Misc Joint issues

* 'Pinching' issues where joints twist too much (elbow/knees)
* Shoulders Not Shrugging with upperArm trackers


### Upside Down

The IK does not respond well to the player being inverted IRL
(Good videos by Echo in the discord, gonna ping them to attach in this issue)

* Joints 'Pinching' (100% of the time)

**Comment by alexderpyfox** [comment]
the hip needs to be decoupled from the position so it can go up and down based on head movement

**Comment by HamoCorp** [comment]
**To add on to the comparisons with VRChat.**
I find the upper body movement is very stiff in Resonite. In VRC the Chest movement is much more pronounced while in Resonite the chest is more muted. also, the lock-both setting in VRChat (which I use in the attached video) is very good for chest tracking and makes chest movement even more visible.

Using elbow trackers in VRChat seems to track shoulder position as well, This makes the shoulders move a lot more realistically whilst in Resonite shoulders don't move at all, they are completely stiff, this looks very strange when lifting arms up.

I use 11-point with index controllers and Pico 4 headset, this was filmed within 5 minutes so the trackers would be exactly in the same positions. no changes hip applied.

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/43244781/0e7e48be-ee18-42d6-b486-35f96a71b4d8

**some other smaller issues I find to be annoying:**
1. You need to have both feet, knee or elbows to calibrate and can't do individual parts. This can be very annoying when one elbow might run out of battery and you still have a working one. if you T pose again you need both, so you have to maintain the bad calibration and just manually adjust.

2. when one foot tracker is disconnected/ doing strange stuff, both legs stop working in game. This can be an issue when one tracker is acting strange and you have both legs taken away. Whilst VRC has settings to freeze position on disconnect, that makes it look and feel a lot nicer.

3. Also the calibrator which I find to be very useful to make small adjustments by dragging the body parts, however it can be very annoying for people when opening it up in a public world as it is large and sometimes causes the game to lag for a few seconds when opening. a local option would be nice.

4. If the T pose could be attached to head position. I have had some situations where the tpose spawns in a weird place in my room like slightly in a wall or object then I have to redo it again, also trying to aline your body with the center of the T pose could be alot easier if it could be attached to head position. This would mean less adjusting from slightly off positions.

5. ofcourse the already stated and well known issue while being upside down like laying in a strange position or hand-stand. but it is becoming very bothersome to not see an accurate representation of actual body movements when seeing full-body dancing.

**Comment by ModernBalloonie** [comment]
Seriously, thanks for the comparisons! These are great.

**Comment by Frooxius** [comment]
Thank you for the info and comparisons!

I've created new thread for a new in-house IK system: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/612

I'm closing this thread so we can continue the discussion there and keep it in one place. I'll reference this in the other thread too so we can tap into this for info and design decisions for the new system.
