### ISSUE TITLE
Default VirtualParent Scale to [1,1,1].

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [Yellow-Dog-Man/Resonite-Issues#1336]
### Describe the bug?

Scale vectors will reset to 0,0,0 when reset to default, virtual parrents LocalScale also defaults to 0,0,0 , even when initialized.

### To Reproduce

Simply make a cube and reset the scale field to default, or make a virtual parent and observe the LocalScale vector

### Expected behavior

Scale vectors should default to 1,1,1

### Resonite Version Number

Beta 2024.2.5.848

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Replicated without headset (UI and internal)

### Log Files

Does this really need a log?
https://pastebin.com/UQ348UR3

### Reporters

@EmergencyTemporalShift

**Comment by Frooxius** [comment]
Those are technically two separate issues:
- VirtualParent should default to [1;1;1] we can change that
- Resetting to "default" here isn't default for whatever that field is, but the default value of that datatype - the system doesn't really know what the "default" should be for any particular field, so this is tricky

I'm not sure which one to really tackle in this one, because they're two separate problems.

**Comment by EmergencyTemporalShift** [comment]
As a note, the LocalScale of the Virtual Parent also defaults to 0,0,0 when reset to default is done, I forgot to re-add that after my tab crashed, I understand that that would have the same problem but I feel it should be noted.

**Comment by Banane9** [comment]
> As noted above- that would be it's own issue- having a system to set per-field defaults for that reset, but is probably not something we'd be likely to prioritize.

It might be of note, that there already is a `DefaultValue` attribute, which is used to mark _some_ fields with default values - althought the vast majority of fields don't have them. I don't presume to know why this is only the case for relatively few fields, but making use of such information in `InspectorMemberActions.ResetField` would seem easy enough.

**Comment by Frooxius** [comment]
We have been moving away from `DefaultValue` attribute and we might eventually stop using it altogether, because it has a number of issues, so it's not a viable solution.

Part of the reason is that attributes cannot use custom types, so it's not actually usable for float3 datatype in the first place.

However we should move this discussion to separate issue now.

**Comment by Banane9** [comment]
> We have been moving away from `DefaultValue` attribute and we might eventually stop using it altogether, because it has a number of issues, so it's not a viable solution.
> 
> Part of the reason is that attributes cannot use custom types, so it's not actually usable for float3 datatype in the first place.

Ahhh! Yea, that makes sense (and using stringly typing for it is pain too x.x).

**Comment by Frooxius** [comment]
I've changed the default VirtualParent value in 2024.2.12.1430! Thanks for report!
