### ISSUE TITLE
Add checks to make sure that generic dynamic object variable ProtoFlux nodes cannot be given Value types for T

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1346]
### Is your feature request related to a problem? Please describe.

Currently it is possible to make nodes like `DynamicVariableObjectInput<int>` and `ReadDynamicObjectVariable<int>` however you can't actually get the output from these nodes as the wire breaks on trying to connect it to something.

### Describe the solution you'd like

Add generic type checking for T to make sure that these nodes can only be created with non-value types.

### Describe alternatives you've considered

Remembering to use the Value variant of the node for Value types, however this only works if you have prior knowledge of this, people run into this problem accidentally all the time due to not knowing the difference.

### Additional Context

N/a

### Requesters

Nytra (discord: nytra)

**Comment by Nytra** [comment]
This issue seems related but for a different node (conditional node) https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/766

**Comment by Frooxius** [comment]
This looks like same issue. 

What you're asking for in this issue isn't something we would actually do. Those are technically valid types for those nodes and there are cases where they might be needed by the system - e.g. when primitives types are stored on the heap, instead of a stack. 

Because of that we cannot make this change you request.

However, the wire breaking and such means that other parts of the system are not handling that properly. This should be handled through #766, so I'm going to close this issue.

**Comment by Frooxius** [comment]
Also just as a note, we strongly encourage people to report the issue, rather than solution to the problem in our guidelines: https://github.com/Yellow-Dog-Man/Resonite-Issues

We've been closing a number of issues for this reason.

It's much better if you report the actual problem (in this case the wire breaking and exceptions thrown), rather than the way you want us to fix it, because it might not be the right way to fix given problem.
