### ISSUE TITLE
Stereo Camera Mode on Default Resonite Camera Captures Wrong Resolution

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#1353]
### Describe the bug?

The default Resonite camera does not keep consistent resolution in stereo mode, resulting in very wide pictures.  This is related to: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/866

### To Reproduce

* Spawn the default Resonite camera
* Set it to stereo mode
* Take a picture

Observe that the pictures are wider than what is displayed.

### Expected behavior

The camera should produce images at the correct aspect ratio as shown in the preview screen.

### Screenshots

![299326387-cae04972-3b3c-4339-a5cd-7255c0371462](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/0cf433d2-5ff6-41d2-a4de-20defe6d4fc7)

![299327241-791c7595-5a1e-4f31-9e7a-47e579af27b0](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/f8fb9a12-5160-40bf-90e2-3de0db8aed00)

### Reporters

code807, LuxKitty, Nytra

**Comment by Frooxius** [comment]
This is expected behavior.

With stereo, you actually have two images that are side by side, with each image shown only to one eye. In order to maintain same horizontal resolution as in the preview, the actual texture needs to be doubled in width.

If this didn't happen, the resulting image would effectively have half the resolution (pixel density) horizontally, than vertically, resulting in blur.

**Comment by lxw404** [comment]
I do greatly understand that there need to be two images (hence stereo).  However the default resolution of the camera is `1920x1080`.  If you take a close look at the provided resolution in the screenshot, the output image is `3840x540` resulting in two stretched `1920x540` images instead of the correct resolution of `3840x1080` which would give two images at the original default resolution `1920x1080`.  This seems to be an error in not handling the aspect ratio calculation correctly.

**Comment by Frooxius** [comment]
I see, thanks for the info.

Next time, please include that information in the initial post though so we can take it into consideration.

Your initial post only states that the image is wider than preview, which is normal behavior - they are supposed to be wider.

However the vertical resolution should be the same resolution as preview, which is the actual problem here.

**Comment by lxw404** [comment]
That is my bad sorry, I copied the original context from the linked issue where it was reported as well and didn't recognize my wording was wrong.

**Comment by davidheiserca** [comment]
I hope this isn't out of line here, but I made a video to share some of what I learned about this issue while poking around in the camera. Maybe it will help someone else solve it.

It's a 9 minute video that's too big to post here, but I posted it on the Resonite Discord server at this address...
https://discord.com/channels/1040316820650991766/1207128674072137749/1209365900327911444
