### ISSUE TITLE
Resonite crashes wen tabbed out and UIX Components cause immense desync

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#1390]
### Describe the bug?

My friend Wattle is hosting a Headless server with great proformance "sometimes" and i started building Uix components and most of the server got immense desync and we managed to rule it down to the uix and someones avi causing it.

also, mentioning the tabbing out issue. 

whenever you tab out of resonite and back in, regardless of how long your out for, you will crash on a random chance where the random chance becomes more and more likely to crash regardless.

### To Reproduce

load into a headless instance or any world with people from around the world, load a uix template panel base and people  should get desynced. 

for the tabbing, stay in a server for around half to an hour then try tabbing out and back in ether in VR or desktop and you should freeze then crash after a few secconds to a minute.

### Expected behavior

none of this should be happening lol

### Resonite Version Number

Beta 2024.2.12.1430

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

quest

### Log Files

No logs here as my game doesn't generate one but i do have one from my friend wattleFoxxo.
[DESKTOP-0U6A7V9_-_2024.2.12.1430_-_2024-02-21_16_52_10.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14360670/DESKTOP-0U6A7V9_-_2024.2.12.1430_-_2024-02-21_16_52_10.log)

### Reporters

WattleFoxxo, charlie_san in Discord and resonite

**Comment by mpmxyz** [comment]
I think that with the information given it could be quite hard to track down the issue:
- The reproduction steps are quite long (in time) and open to interpretation. That is not meant as critique but more an explanation why it may be hard to use them as they are since you can spend hours on this without triggering the error.
  An example item that has been tested to trigger the issue could help with the ambiguity.
- As you said the log files are not from the user that crashed. A crash (with stack trace) and the lines before that contain valuable information.
  So, with the goal to obtain more information: Why is it that your game does not generate a log file?

**Comment by charlie-sans** [comment]
i have no clue why my game doesn't create a log file but the logs i provided came from the person who crashed.

**Comment by charlie-sans** [comment]
unfortunatly i don't have the player.log but this can be achived in pretty much any instance with more then 5 or so hours.

however giving it more time after that might make the thing more likely to crash. 
i don't quite have anything besides my main avi that could have a cause in this?
this occured on my friends contacts+ headless.

**Comment by charlie-sans** [comment]
so, they had around i think 32 gigs of ram from what i heard, there were
only me and them present at the time of the crash. it seems to be fine for
now, must be a networking issue
