### ISSUE TITLE
Audio Output Channel Selection

### ISSUE THREAD

**Issue by FlameSoulis** [Yellow-Dog-Man/Resonite-Issues#1426]
### Is your feature request related to a problem? Please describe.

At this time, when you use an Audio Output component, it has a few options like Spatialized, Distance adjustments, volume, etc. The issue is that if you want stereo audio, you cannot use Spatialized, as it merges(?) the channels to a single mono output. For some casual video-watching, this may be okay, but for a decent audio experience (especially in VR), this isn't very impressive.

### Describe the solution you'd like

An option to specify a channel on the Audio Output would allow for building specialized stereo/surround audio experiences by allowing the slot to reposition where an audio channel should play in 3D space. This could allow for a simple stereo expansion on a video player to a full surround sound virtualization.

### Describe alternatives you've considered

The only way to emulate a surround setup for audio was to split each channel into its own audio file, then painfully sync the audio timestamps over time with a channel acting as the master.
The same as the above could be applied for video files, but it would be much more complicated. This may simply be impossible via manual methods for video services (YouTube, Twitch, Twitter, etc.).

### Additional Context

If there is a concern regarding backward compatibility, a solution could be to introduce a new Audio component that filters out a Sound source to only a requested channel and has its own output be a sound source. This would allow existing content to remain operational without any concerns (especially for ProtoFlux-related issues, which I think also has an AudioOutput node) and could slowly begin a roadmap to other 'filters/effects' for audio processing.

### Requesters

Flame Soulis (FlameSoulis)

**Comment by Frooxius** [comment]
I'm not sure if this is something we would want to put on the AudioOutput itself, because we're trying to keep this relatively light, with pretty much no processing of the actual audio data.

The goal for approaches like this would be to introduce the DSP system: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/567

This would let you modify/filter the audio streams coming into AudioOutput, separately from the audio output itself. This way things are kept more modular and flexible - e.g. you might want to split out channels for other reasons too (for additional processing) or do some more processing. The streams can also be more varied (stereo, quad, 5.1...) which would require AudioOutput being aware of all of these.

**Comment by FlameSoulis** [comment]
Ah, yeah, fair point.

I'll update it there, but part of the discussion mentioned Steam Audio, which went open-source a few weeks ago. Not sure if this helps at all, but figured it'd be worth pointing out, since it's already part of the workflow.

https://steamcommunity.com/games/596420/announcements/detail/7745698166044243233

**Comment by FlameSoulis** [comment]
Ah, yes. #436 was closed due to duplication, so I'll do the same here.
