### ISSUE TITLE
Current LOD index output for LODGroup

### ISSUE THREAD

**Issue by LeCloutPanda** [Yellow-Dog-Man/Resonite-Issues#1450]
### Is your feature request related to a problem? Please describe.

The LODGroup component works fine but having no integer output of what group is being used prevents stuff from being used in tandem with ValueGradientDriver on stuff like dynamic bones, asset multiplexers and more.

### Describe the solution you'd like

An integer output of the current LOD group being displayed/used on the LODGroup component

### Describe alternatives you've considered

Remaking the component out of flux and having it go off distance to the local user and then sprinkling in some support components like ValueGradientDrivers.

### Requesters

[LeCloutpanda](https://github.com/LeCloutPanda)
[UltraWideGamer](https://github.com/UltraWideGamer)

**Comment by Frooxius** [comment]
Unfortunately we cannot add this due to how the LOD groups work:

LOD group affects the rendering process by selecting which of the parts of the object a camera renders based on the apparent screen size, but it doesn't change what's actually "present". It is not designed to allow switching of components and other interactive behavior dynamically like you request.

E.g. if you have multiple cameras/views, the LOD that's being displayed is dependent on each camera rendering it - meaning the index would be different for each - and it would also be determined during the rendering, at which point you cannot make any changes like driving values or disabling dynamic bones - it just doesn't fit into the system.

Additionally the LODGroup component isn't best supported right now, so we're unlikely to add new behaviors that would let users build on top of it, because we might overhaul it significantly later and this would make that work more difficult.

I'd recommend using different types of culling systems for this, either distance based or based on colliders for now. In the future we'd like to introduce proper culling systems which would allow for culling of behaviors like this as well, but very likely independently of the LODGroup component.
