### ISSUE TITLE
Session hitches when other users join

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#1477]
### Describe the bug?

In a session(particularily large sessions), when a user joins there is a "hitch" or lag spike in Movement, Voices and Interactions.

### To Reproduce

1. Host a semi-large session
2. Have A USER JOIN
3. Witness the Lag

### Expected behavior

Users joining should not affect the performance of a session

### Resonite Version Number

2024.3.1.1178

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[ALFRED - 2024.1.3.1265 - 2024-01-05 20_24_10.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14565761/ALFRED.-.2024.1.3.1265.-.2024-01-05.20_24_10.log)

This is a log file from another version but its the "largest" session i've been in, in awhile.

### Additional Context

I'm making this issue so that there's a public reference to it. There's no updates to this issue but its important to have items logged.

It might be a duplicate but searching didn't find it.

### Reporters

Literally Everyone?

**Comment by ProbablePrime** [comment]
@rileyguy has a temporary work around here in the form of a mod: https://github.com/RileyGuy/Outflow

While the mod fixes the issue it's methodology is probably not suitable for actual inclusion as evidenced by its readme. But I'm linking it here because it makes sense to do so.

This message does not constitute an endorsement or recommendation for said mod. Please use at your own risk.

**Comment by RileyGuy** [comment]
> @RileyGuy has a temporary work around here in the form of a mod: https://github.com/RileyGuy/Outflow
> 
> While the mod fixes the issue it's methodology is probably not suitable for actual inclusion as evidenced by its readme. But I'm linking it here because it makes sense to do so.
> 
> This message does not constitute an endorsement or recommendation for said mod. Please use at your own risk.

Feel free to alpha test this, but do note that I need to do some testing to ensure that nothing is being corrupted.

The jist behind what's going on in the EncodeLoop is that even though StreamMessages can be asynchronously enqueued for transmission, they will still get stuck behind large FullBatch messages as those take quite some time to encode (up to multiple seconds for populated sessions, even on good hardware like a Ryzen 5900X). It's specifically when they're encoded though and not when they're transmitted, as transmission is quite efficient.

A given session only has one processing thread for the encoding/decoding, so streams get held up which causes that pause in everyone talking/moving. Outflow simply creates a new queue & encoding loop solely for SyncMessages on a separate thread while leaving everything else in the normal queue. LNL/Steam networking appear thread-safe so it ended up fairly simple. (That is, after a week of reverse-engineering how the networking functions and realizing Occam's Razor very much applies)

Though the data model needs to be re-worked so that FullBatch encoding doesn't take so long, I think unreliable messages in particular should be handled in a separate thread from the reliable messages anyhow.

Disclaimer that this is just my personal opinion, and I'm happy with whatever is decided in the end. I just wanted to give my input nonetheless. :3

**Comment by Banane9** [comment]
_But how will we notice someone joining, if you fix this?_ 😉

**Comment by ProbablePrime** [comment]
Record the noises that happen when a user joins(its usually glitchy and weird) + User Join Audio Indicator => you can re-create the effect.

**Comment by ohzee00** [comment]
If doing a recording, it might be more convenient for a user to stream their audio in game and play some music, this mechanism is the same as user voice and doesn't require talking to hear the issue.

**Comment by TisFoolish** [comment]
> Record the noises that happen when a user joins(its usually glitchy and weird) + User Join Audio Indicator => you can re-create the effect.

Wouldn't that have to wait for #567?

**Comment by ohzee00** [comment]
> Wouldn't that have to wait for #567?

I think you're getting confused, they most likely mean just recording externally via OBS or otherwise.

**Comment by TisFoolish** [comment]
That would take way too long and isn't automatable.

And it was going with the joke

**Comment by BlueCyro** [comment]
> Potentially related to #234

Not likely, #234 deals with assets / large hierarchy modifications in particular affecting the framerate on the client.

This issue deals specifically with the fact that StreamMessage packets were getting held up behind large FullBatch encodes when someone joins the session, causing streamed data to stop transmitting for a while. This issue only describes the lapse in networking (e.g. voices stop working, people stop moving), not the client-side freezes that come from asset loading / hierarchy changes.

**Comment by PraxThing** [comment]
To contribute a sense of **Impact** to this issue to help the team determine where it lies in priorities according to the [How We Prioritize](https://github.com/Yellow-Dog-Man/Resonite-Issues/blob/main/HOW_WE_PRIORITIZE.md) document:

This affects social gatherings **greatly**.  In hangouts (especially public ones), with users leaving and joining, it is extremely disruptive to conversations and frequently requires people to repeat themselves.  It is a zero-threshold phenomenon that is _ubiquitous_ and exacerbated proportionally by the number of users.

Therefore I would suggest this be classified as a Stability issue, as it impedes the function/use of the platform.  **Struggling to support a room of 10 people conversing is a threat to the viability of the platform.**  

If there is any more data I can collect to help assist in the resolution of this issue, please let me know; I am happy to help in any way I can.

**Comment by BlueCyro** [comment]
> To contribute a sense of **Impact** to this issue to help the team determine where it lies in priorities according to the [How We Prioritize](https://github.com/Yellow-Dog-Man/Resonite-Issues/blob/main/HOW_WE_PRIORITIZE.md) document:
> 
> This affects social gatherings **greatly**.  In hangouts (especially public ones), with users leaving and joining, it is extremely disruptive to conversations and frequently requires people to repeat themselves.  It is a zero-threshold phenomenon that is _ubiquitous_ and exacerbated proportionally by the number of users.
> 
> Therefore I would suggest this be classified as a Stability issue, as it impedes the function/use of the platform.  **Struggling to support a room of 10 people conversing is a threat to the viability of the platform.**  
> 
> If there is any more data I can collect to help assist in the resolution of this issue, please let me know; I am happy to help in any way I can.

I've already narrowed it down to a full world encode. When a user joins, a function gets called that iterates over every single IWorldElement and gathers it up. This doesn't take super long, but the actual encoding part does. Go look up where FullBatch is used and you'll find the full encode method. I don't know how much you're wanting to find, but the actual encoding process of each world element appears to be the culprit. I have a suspicion it could be the compression, but it uses LZ4 which should be very fast according to froox, so it could also just be the mere act of serialization.

**Comment by Frooxius** [comment]
I'll be addressing this one very soon by reworking the corresponding chunk of session networking handling mechanism. This one is pretty crusty code with manual thread management and there are a lot more modern approaches, like using Task Parallel Library primitives. 

This will help simplify the code and will resolve those issues as well, leading to better parallelization and nicer API's (which will in turn enable other improvements).

This falls under the performance optimizations tasks and I believe it's most beneficial to address this now, because with .NET 8.0 upgrade for headless, community is now hosting a lot bigger sessions than before, which makes this problem more pronounced, resulting in interruptions.

**Comment by Frooxius** [comment]
I've been working on reworking and restructuring the session handling system. I think I'm about halfway done through it. It's promising so far, I'm making the code a lot more modularized and separated, which will make following the logic (and expanding it) much easier going forward, while providing optimizations for the handling.

Through the rework, I've made some discoveries, partly on why the Outflow mod has issues. What it ends up doing is that it effectively ends up sending messages out of order - the user receives a number of delta messages before the full encode, which they can't do anything with, so they end up ignored. However this means, they end up completely missing some changes to the data model between the full encode and them receiving it, which ends up subtly corrupting the data model as a result.

The corruption will vary depending on how much happens during that period of time - e.g. any items spawned or modified during that period will end up crashing the user, since they are missing some bits of the data model for those. 

The rework addresses this in a mode fundamental way, by changing some of the flow, especially around the initial sync, which should resolve the issue without any negative effects.

It'll also make other things easier to integrate into the flow as well. E.g. one that's been on my mind is this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2619

With those changes it'll be easier to rework this part of the flow to provide better data privacy.

That's all for now, I just wanted to share some of the progress and findings I made.

**Comment by BlueCyro** [comment]
Clarifying for the rest of the class since I already mentioned it to froox - the issue with my mod is actually far more peculiar.

I actually don't touch any of the reliable sync messages at all. I specifically only intercept stream messages since they don't touch the reliable data model. This is how I keep player movements, voice data and other miscellaneous streams running while the full batch encodes. You can see the mermaidjs diagram in the README of my mod for visualizing how it works.

Obviously my mod will become moot quite soon, but I figured it was an interesting mention nonetheless. I would still be curious to know why it happens in the first place.


Trade offer for anybody who's bored.

- I receive: Why my mod is broken
- You receive: The absence of the time you spent figuring out why and my unending gratitude

**Comment by Frooxius** [comment]
Yeah I've talked with Cyro and it looks like the issue with mod is actually different from what I understood. My understanding of it was colored too much by the way I'm restructuring it myself for the rework ^^;

**Comment by Frooxius** [comment]
This is now in public `prerelease` testing! Head over here if you'd like to help testing this out: https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/3021

**Comment by BlueCyro** [comment]
Happy to report that Tatsu tested a sizeable session of about 15-20 people and joins didn't hitch voice/music streams at all.

There's a noticeable jostle of about a fifth-second in the transform streams which I noticed as the session got larger, but audio was unaffected entirely. I'd say the issue has been mitigated quite satisfyingly and I'm eager to see how truly huge sessions perform.

**Comment by Frooxius** [comment]
This is now implemented in 2024.9.30.1215!
