### ISSUE TITLE
"Inventories" button clutters UI when it isn't needed.

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#1532]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when a new user accidently navigates to their Inventories, showing them Personal and no groups because that leads to confusion.

### Describe the solution you'd like

The "Inventories" button should not be available when you have no group folders you could access since it is useless in those cases.

### Describe alternatives you've considered

Not doing this. (why?)

### Requesters

cameron5 on Discord, Psychpsyo in Resonite

**Comment by ShrikeAlvaron** [comment]
I'd say it's not useless even without groups, since it lets you refresh your inventory in case it's not updating properly, or you want to see the size of newly saved items without restarting the game.

**Comment by Psychpsyo** [comment]
> I'd say it's not useless even without groups, since it lets you refresh your inventory

That sounds like other bugs that should be fixed and not a feature of the Inventories button.

**Comment by Frooxius** [comment]
Thanks for making the issue.

I understand the problem. However our plan is to rework the Inventory UI completely, which will make this issue irrelevant, see here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1119

Since this is not a critical issue, we will not be committing development time towards the legacy UI with this.
