### ISSUE TITLE
Alpha-translucent textures can get white fringes around edges

### ISSUE THREAD

**Issue by iamgreaser** [Yellow-Dog-Man/Resonite-Issues#1570]
### Describe the bug?

Importing of textures with fully-transparent pixels from programs which force the colour of these to be white results in white fringes on texture edges. This includes Inkscape.

### To Reproduce

This gives you an extreme example.

1. Open up Inkscape.
2. Draw a black-fill, black-stroke circle.
3. Select said circle and export it as a .png with default settings.

The result of this should be something like this: [black-circle inkscape 001.png.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14814631/black-circle.inkscape.001.png.zip)

Now, import this texture into Resonite, and enjoy the unexpected white fringing around it (enjoyment is optional).

### Expected behavior

A fully-transparent texel should not have a notable effect on the rendering of the texture other than being fully transparent.

A texture of this kind can be alleviated mostly by using point sampling, but to completely eliminate it in that case requires using uncompressed textures and disabling mipmaps. Changing the colour space does not eliminate the fringe.

(As a corollary, given plain bilinear sampling without premultiplied alpha, the colour of a fully-transparent texel should be selected based on the colours of the neighbouring pixels which aren't fully transparent. Working out how to achieve such a thing sanely in an sRGB space would probably be a Geenz question.)

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/138113/aa465d02-ba8b-4496-9d63-886b598eff01)

### Resonite Version Number

2024.3.12.1169

### What Platforms does this occur on?

Windows

### Log Files

N/A

### Additional Context

There *may* be legitimate uses for fully-transparent pixels having designated colours, but such uses would require concrete examples, and this would have to be an import option, such as "Force the use of provided colours from transparent pixels".

### Reporters

GreaseMonkey, Medra, Rucio.

**Comment by lxw404** [comment]
This I am pretty sure is expected behavior and not a bug.  The reason being, it is actually properly interpolating between the real color information that is actually stored in the color channels between neighboring pixels when in default bilinear filtering mode (in fact as you note, only Point filtering mode will result in black edges since it does not sample neighboring pixels).

Some concrete examples of needing specific color fully alpha images:
* Specular maps - Color information is completely independent of the specularity (alpha)
* Metallic maps - Color information is independent of the metallic channel (alpha)
* Erosion maps - Color on erosion maps is the original color image and is completely separate from the alpha

If I recall, you should be able to specify a background color in Inkscape and this might fix your specific issue?  In Substance, GIMP, Photoshop, etc. this just comes down to setting the background color before export.

**Comment by Frooxius** [comment]
This is not a bug, but an issue with the image itself.

If you switch the blending to Opaque, you can see that the image you provided actually has white color information around the circle. This is what ends up bleeding through with billinear interpolation and in mip-maps.

There are two ways you can solve this:
1) Use export option in your software that will fill the alpha data with proper color information (I'm not familiar enough with your software, so you have to do your own research here)
2) In Resonite, there is "Bleed Color To Alpha" operation, which will do this for you. Click it on this texture and that'll fix your issue.

**Comment by iamgreaser** [comment]
Alright, it's good to know that there's a feature already. I was thinking this would be good for a tutorial world but I'm not sure which tutorial worlds even explain how to import textures yet - I'm mostly familiar with the usual JP Tutorial World and that doesn't cover how to build things.

I filed it as a bug due to the unexpectedness of it for the average user. But it does seem that there are concrete examples where doing this automatically would be surprising for others.

The "god-tier" solution would be to automatically do something like this for a texture where alpha is truly alpha, although there's a risk of using double the VRAM where both variations are used.

**Comment by Frooxius** [comment]
I've talked with Medra about this in world. I think best solution here would be to add another import option, something like "Sprite / Cutout image" when bringing an image which would run this automatically when this option is selected, but not others.

We can't do this automatically for every image/texture you bring in, because while you want the processing to happen to sprites and images like this, for other types of textures it would destroy the data - e.g. when bringing in metallic/specular maps, color splats and other types of textures where the alpha encodes data that's decoupled from the color data.

**Comment by iamgreaser** [comment]
...in the "god-tier" solution I should have clarified that it would be applied to an in-VRAM representation, effectively having up to two in-VRAM representations... *but* the complexity might not be justified there.

Yeah, an import option would be a good idea. I'd argue that the "cut-out" case is the more common case, although I'm not quite sure how I'd work it... "keep transparent colours" for the other case?

**Comment by Frooxius** [comment]
I don't see the benefit in that. You either want to use one version or the other.

You'd effectively need to have two textures in VRAM and doing it for everything would double the VRAM usage for no reason - the user would still have to choose which version they want, wasting the other.
