### ISSUE TITLE
Grabbable Receiver Surfaces are overriding Snapper / Snap-Targets, making Snap Targets break for Receivable objects when sitting on Receiver Surfaces.

### ISSUE THREAD

**Issue by NukiRaccoon** [Yellow-Dog-Man/Resonite-Issues#1590]
### Describe the bug?

I recently added a Snap Target / Snapper system to a "Maglev Display" I made with ShiningHero, available in Dusk Modular.

This is a decorative object, with a base piece made to be placed on a table, and a displaying saucer made to be snapped on top of it.  My intent was for the saucer to functional when standalone, but the main thing about it is it's supposed to snap to the base as a floating thing.  It works, except for one issue...

**When the base is set on a Grabbable Receiver Surface, the Snap Target / Snapper is overridden, and the item falls to the surface.**

This seems to be unintended, as the Snapper is a rare and specialized component, and one might often want this kind of working behavior.

### To Reproduce

This is the object I had the issue with, for reference and testing purposes.
resrec:///U-1NpQoxe8oee/R-2476a073-1354-4671-90df-97b4ca4a29c6

Spawn it, and have a table or some other object with a Receivable Surface on hand.

Remove the floating saucer, observe that it snaps just fine, and that you can place it on the Surface just fine.

Place the Base on the table, then attempt to snap the Saucer into the "magnetic" area it's supposed to snap to.

Saucer will fall down to the base, completely ignoring the snapper.

Note that the snapper IS firing, as can be seen if you watch the Slot Children Events, only it is happening for less than a frame before being overriden by the Receiver, causing the object to reparent and drop.  However, we were unable to build a quick workaround using methods like a parent-variable to try to stop it from being receivable do not work: until testing the Slot Children Events just now, it seemed to bypass the whole thing entirely.

Any workaround requires one to watch the Slot Children events, and manually replicate the Snapper, which defeats the purpose and may be unreliable.

### Expected behavior

The Snapper should ALWAYS take precedent over the Reciever, as it is a much rarer and more specific component.

### Resonite Version Number

2024.3.12.1169

### What Platforms does this occur on?

Windows

### Log Files

Logs are irrelevant, as this won't appear in them, as far as I know.

### Reporters

Nuki

**Comment by JackTheFoxOtter** [comment]
> The Snapper should ALWAYS take precedent over the Reciever, as it is a much rarer and more specific component.

I'm not sure about the "always" part, as that depends on how it's used. You could have the same issue the other way around, even if rarer. But more generally a priority system simliar to the "GrabPriority" for all grabbable receivers could make sense.

**Comment by NukiRaccoon** [comment]
@shiftyscales I'm not sure this is the same issue: this other one is talking about Reciever Surfaces taking priority over each other, while this issue is talking about Snappers breaking when used near Receiver Surfaces...  If the feature request was implemented, it wouldn't fix this, unless the same system was also implemented with Snappers with a default priority that would override the Receiver's default priority.

**Comment by JackTheFoxOtter** [comment]
I think this priority system would make sense to be implemented for all things that can receive grabbable objects on release. As already outlined, which thing should take priority is something that depends on how those components are used, so you can't have a blanket solution like "snappers should always take priority", as it depends on the context of the creation.

**Comment by NukiRaccoon** [comment]
> Can you please provide a full replication world that exhibits your issue, or additional context, e.g. video demonstrating the issue @NukiRaccoon? What is breaking on the snap targets, exactly?

I keep not getting around to this.  I've have the actual item-combination I first found the issue on sitting in my public folder for quite some time now, but remembering when I have Resonite open and can post on here has been hard.

Here is an item that can be spawned to demonstrate the issue.
resrec:///U-1NpQoxe8oee/R-b6381877-8815-4fe2-a377-8be550ae095c

When the maglev plate is on its own, the display thing snaps as intended.

When it is on the table surface, the Grabbable Reciever overrides the snapper, unavoidably leading to behavior that is not only not my intent, but I don't think it was the intent of those components.

**Comment by shiftyscales** [comment]
I see a few issues in how you had set up the components on your object, @NukiRaccoon:

- On the `GrabbableReceiverSurface`, you did not have a `OverrideParent` slot specified

This means that by default any objects are placed under the slot the `GrabbableReceiverSurface` are parented underneath it, and their colliders in turn are used for checking the range / radius of nearby objects to receive. I placed a slot under the root object to parent these to- and applied a `GrabbableReparentBlock` so that objects grabbed and released are not still parented to the table afterward unless they are received by the surface again.

- There was no `MaxDistance` specified - coupled with the above- it was aggressively checking everything above the surface for stuff to grab / snap onto the surface.

For your object I found a value of `0.25` worked well as a good balance between letting you easily snap the object onto the surface while also still using the snapper.

Please refer to the following video for a demonstration of how the object performs with the above tweaks.

https://github.com/user-attachments/assets/d93ceb49-2514-46c3-8baf-d02182dcdbe2

I hope this helps.
