### ISSUE TITLE
possible suppport for a new node?

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#16]
### Is your feature request related to a problem? Please describe.

i want to find a way to make protoflux without getting angry at the fact the nodes getting jumbled and dont have proper documentation, so i decided to make a text based compiler.

### Describe the solution you'd like

a way to spawn in nodes natively thru a websocket while passing the name of the protoflux instead of a 20 odd something long string that allways starts with frooxengine.frooxengine

### Describe alternatives you've considered

ive thought of creating a resonite mod to combat the node spawning issue but for the use case it would be required for, i dont think it's needed

**Comment by ProbablePrime** [comment]
Hey,

Thank you for making this feature request.

On the surface, this feature request is unfortunately not suitable. Text based editing and scripting/programming is an idea that we've had for awhile, we've talked briefly as a team about doing this via WebAssembly so that any language can be integrated into Resonite.

WebAssembly support as a feature is likely to be a lot better and smoother than making changes to how nodes can be spawned.

In particular doing this sort of thing over websockets isn't really how we'd tackle it, we'd place stuff in the UI natively that allows for text editing, compilation etc and then running.

Due to this i'll unfortunately have to close this issue as not planned.

Thank you for making this request. I'll stand up the WebAssembly issue shortly.

**Comment by charlie-sans** [comment]
no worries! it's nice to see WebAssembly being added into Resonite as a text based programming language option but i do have a worry that some people who code in languages that dont compile to WASM might get angry or sad the fact that they have to learn a new language just to text based code
