### ISSUE TITLE
Inspector UI components not correctly clipped and/or shaped

### ISSUE THREAD

**Issue by ProtogenDelta** [Yellow-Dog-Man/Resonite-Issues#163]
### Describe the bug?

The corner of the inspector UI slightly overlaps its own border.

Very low priority, but annoying nonetheless.

### To Reproduce

1. Launch Resonite
2. Grab a Dev Tooltip
3. Open an Inspector
4. Observe Corners

### Expected behavior

The corners should match the shape and size of their outline.

### Screenshots

![screenshot showing the corner of the inspector](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47292121/330f672c-f773-4cb0-9d46-9fa8277b786f)
![screenshot showing the corner of the inspector, credit to toxic_cookie on discord](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47292121/a9462b34-6436-4556-a198-9b8adf21d24f)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop

### Log Files

- [Pastebin: DELTA-ROVER - 2023.10.13.743 - 2023-10-15 01_00_28.log](https://pastebin.com/H4MMvEDL)

### Additional Context

Again, should stress that this is a pretty low priority nitpick, but nonetheless, still a bug?

### Reporters

`toxic_cookie` on Discord
`leocatto` on Discord

**Comment by Frooxius** [comment]
We plan to rework inspectors completely in the future, which will get rid of this problem, as they will be made from a template in-game, rather than code constructed: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/563

I'm closing this, as I don't believe fixing this in the interim is worth our development time.

Thank you for the report though!
