### ISSUE TITLE
Expand Face/Eye Tracking.

### ISSUE THREAD

**Issue by AmriaLeiah** [Yellow-Dog-Man/Resonite-Issues#1653]
### Is your feature request related to a problem? Please describe.

Currently the Expression drivers do not support every feature that headsets in the last year have come out with, such as certain movements of the face and even eyebrow tracking.

### Describe the solution you'd like

Expanding the list of supported expressions would be great, but what would be even better is if we could define our own methods. I'm not too familiar with how Resonite does things, so I don't even know if it would be possible to do so.

### Describe alternatives you've considered

(Mentioned above)
Perhaps a component or flux node to communicate with OSC methods?

### Requesters

Amria
(And probably anyone else that would appreciate using the full capabilities of their face/eye trackers.)

**Comment by ModernBalloonie** [comment]
Actually, I'm curious if there could be an ability of putting our own facetracking presets in because there are several standards.

Now there are things like sranipal, quest pro, arkit, but there's also one that is becoming used a lot now, and that's unified expressions. It's normally a part of VRCFaceTracking, but I have been updating all my avatars to use this unified expressions standard. It's basically a more universal expression standard that's really great and it's also future proofing a bit. https://docs.vrcft.io/docs/tutorial-avatars/tutorial-avatars-extras/unified-blendshapes

**Comment by Frooxius** [comment]
We will need to expand the input system representations to support more standards and map between them based on what the device driver provides.

This isn't really something that you could do yourself easily, as the mappings between them can get complex and we'll need to update the data model.

**Comment by AmriaLeiah** [comment]
I missed Issue #4, the next one is also relevant.
Though, there is a compounding problem of needing to manually address each different headset manufacturer. That could get cluttered and complicated over time. Plus there are the rare few who DIY. While I would like to see more options for users to be independent in supporting their headset, alas at this time nothing like that is even remotely feasible and would take away from more pressing matters. 

I'm closing this because there is another issue close enough to one part of the issue, and the other part I realize would be an undertaking so massive that supporting each method individually would likely be vastly more time efficient and save so many people so much sanity.
