### ISSUE TITLE
Cloud Home's Directional Light Intensity is too Strong

### ISSUE THREAD

**Issue by lill-la** [Yellow-Dog-Man/Resonite-Issues#171]
### Describe the bug?

The Intensity of CloudHome's daytime DirectionalLight is as high as 1.5.
The colors of avatars set up normally with XiexeToon are blown out.

### To Reproduce

Open `Resonite Cloud Home`.
`World Assets/Dawn Sky/Sun pivot/Sunlight`

### Expected behavior

Set Intensity to 1.
Change the Value of ValueGradientDriver in `World Assets/Dawn Sky/Variables/Sunlight coloring/Directional light intensity gradient` to 1.

### Screenshots

![2023-10-14 19 51 45](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44998659/a65cb065-ed8f-46c8-884b-659a57060585)

### Reporters

lill

**Comment by Enverex** [comment]
It looks fine on PBR shader based objects, which would imply an issue with the toon shader rather than anything else. In my own worlds where I've set up lighting around proper PBR materials and models, they all look fine but toon shader models/avatars are still blown out.

Ergo I believe this is an issue with the toon shader (shadow ramp maybe?) and not the choice of light intensity.

**Comment by RyuviTheViali** [comment]
Given the nature of the sunlight in the cloud home, we will be keeping it's brightness where it is - the issue is not necessarily the brightness of the light, and more-so how the Xiexe Toon shader handles bright lights. Thanks though!
