### ISSUE TITLE
Add settings for controlling/managing trackers

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1735]
### Is your feature request related to a problem? Please describe.

Sometimes I need more control over trackers (notably Vive Trackers) - for example when they're charging, I'd like to disable them completely, so they stop being used for tracking or review/reset their mapping individually. 

### Describe the solution you'd like

Add new setting which will contain both global and per-tracker settings, such as:
- Use tracking (allows completely disabling trackers)
- Enabled status for each tracker
- Mapping for each tracker (can be reset individually)
- ID & Battery charge (purely informational)

### Describe alternatives you've considered

N/A

**Comment by JackTheFoxOtter** [comment]
While you're working on this, do you think it would be possible to add a user configurable alias or "label" to trackers? For body trackers it's easy to see based on the mapping, but for trackers that are used for non-fullbody things I could see "Water Bottle Tracker" being more useful to me than "LHR-416FC30F"

**Comment by Frooxius** [comment]
Yeah we could do that. But question is, where would you want this to show up?

**Comment by JackTheFoxOtter** [comment]
Primarily in the settings as the section label instead of the tracker ID if set, and on the facets you can instantiate, so if I make one for multiple trackers and put it on my home screen I know which one they are linked to. potentially in the future in other places where tracker names are displayed. But for now I'm just asking for organization in the settings / facets.

**Comment by Frooxius** [comment]
Added in 2024.4.24.33
