### ISSUE TITLE
Implement userspace quick-access facet anchors

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1749]
### Is your feature request related to a problem? Please describe.

Currently facets can only be placed within the dash in the userspace, which requires to be opened to access them. However for quick workflow, it would be beneficial to be able to place facets on anchors on the avatar or the viewport.

### Describe the solution you'd like

Implement facet containers in user-space that can be invoked by the second App button. These facet containers will allow users to place facets onto:
- Hands
- Forearms
- Head Viewport (this will be useful for facets such as mute indicator)

### Describe alternatives you've considered

N/A

### Additional Context

This will replace the legacy world switcher, since it'll be possible to just place a facet to quickly switch between active worlds directly on the hand instead.

This will also combine well with the new Settings UI, which will allow placing common settings for quick-access onto users hands.

**Comment by 5H4D0W-X** [comment]
If "second app button" refers to one of the dash buttons, there might be some incompatibility problems with people's controllers. Many people rebind one of their dash buttons to be a jump button, so that they can jump without pressing their joystick. This would either prevent the dash from opening or prevent the facet anchors from being used. I would really appreciate a way to rebind the action, for example to be the opposite of the legacy inventory gesture (right grip + dash)

**Comment by Frooxius** [comment]
That'll be left to the users to handle the rebinding. Once you rebind the official bindings, you take on the responsibility of maintaining those changes with the ones we do - we will not take on that burden.

The goal for our bindings is to be quick, because we want it to be quick and easy to access official functionality.

If people want to find ways to make that work with their binding changes, they'll have to figure out bindings on their own for that.

**Comment by JackTheFoxOtter** [comment]
It would also be a bit of a accessibility concern for people that can only use one controller.

**Comment by Frooxius** [comment]
I think if people can use only one controller, they'd probably just use the dash anyways.

Typically with this, you'd access the facets on the opposing hand with your other hand - meaning if you can't use the other controller, I don't see how would you put facets on it in the first place?

**Comment by JackTheFoxOtter** [comment]
Maybe making tapping the menu button toggle the dash, and holding the menu button toggle the body facet anchors.

> Typically with this, you'd access the facets on the opposing hand with your other hand - meaning if you can't use the other controller, I don't see how would you put facets on it in the first place?

Well, you're also talking about the ability to pin facets to your view, which would be desirable regardless of how many controllers you're using.

**Comment by Frooxius** [comment]
> Maybe making tapping the menu button toggle the dash, and holding the menu button toggle the body facet anchors.

This won't work with some controllers, because they use long-press to open/close dash and short press to open/close context menu, since they don't have enough buttons.

> Well, you're also talking about the ability to pin facets to your view, which would be desirable regardless of how many controllers you're using.

Yes, but this secondary use and you can just open/close dash if you'd only use that part anyways. This is mainly meant for quick access to things, but it doesn't lock away any actual functionality.

We can add additional ways to open/close this using a button in the space or other button, but the primary action will be one that's very quick to execute normally.

**Comment by Frooxius** [comment]
How would you expect that to behave when tje object is deleted or when you go to another world?

What would be usecases for something like this?

**Comment by Frooxius** [comment]
I think that'd be better to split off into separate issue, since that's pretty distinct from this issue. 

We can look into something like that, but I don't imagine that working too well - `10, 2, 16` in one world could be good location and very poor location in middle of wall or in-accessible location in another.

**Comment by gameboycjp** [comment]
To solve not being able to use it on one controller, there could possibly be a setting to have it always on. 
Will the non-avatar specific anchors be positionable?

**Comment by WorldTheory** [comment]
My original draft of this comment was long-winded, so I decided boil it down as much as I could... It was really difficult.

For context, I haven't used VR before. I play in desktop mode. But basically, I hope there will be options to make the viewport-tracked anchor canvas responsive to changes in FOV and aspect ratio.

I made a comment on the youtube video from the dev log, and a reply from Epic Easton comes to mind. They said they imagined it working similarly to how the grid on the dash resizes in response to changes in game window. So I opened Resonite to look at the dash while I play around with window size changes.

I'm not sure how facets decide to present themselves, but from observation, they each seem have a mini quad that they have to fit inside, whose corners are positioned on the dash in a relative unit based on percentage of screen space, so these container quads get stretched with the window size changes. Then the contents of the facets reflow and resize themselves inside those containers, I assume based on some internally defined logic.

Giving it some thought, I would definitely want the viewport-tracked facet anchor to behave like that. Because it gives maximum flexibility to change things to your own preferences.

For example, someone might decide they want to make different versions of the same facets. So each version will reflow with the assumption of being along specific edges or corners and look like it belongs there no matter the screen size. This would address one of the concerns I had.

Another worry I had, was how motion blur will affect the anchors. I made my own HUD icon attached to my avatar that follows my vision with the PositionAtUser component, and despite it not really appearing to move relative to my vision, it would blur a lot in response to my avatar running or turning. This is much less of a concern now that we can turn motion blur off, but it seemed worth mentioning in case no one tests with motion blur turned on. I don't know how putting things in User Space might affect things like that.

That's everything I can think of right now.

**Comment by Frooxius** [comment]
These are for VR specifically, this is not something you'd use in desktop. Any of the resizing, FOV, motion blur and such are not relevant here.

Generally we advise against feedback from devlogs, because they are very early work in progress stages. Usually we either open it up for feedback during specific points (e.g. during testing phase) or we iterate once it's released if it doesn't break anything.

**Comment by TisFoolish** [comment]
Will the notification bubbles be changed to use this system? I'd love to be able to move where the notifications are in my user space and I know of some people who have mentioned wanting to put them on their hands or palms.

**Comment by Frooxius** [comment]
Yes, they will use this system.

**Comment by epicEaston197** [comment]
Seeing the latest devlog makes me wonder if you'll be able to enable select anchors like if you only want anchors on the back of your hand and nowhere else I think this should also be side dependent so you can have the ability of only being able to put facets on the back of your right hand or only on your right upper arm

**Comment by TisFoolish** [comment]
Will there be any way to "freeze" the anchors in place? I am thinking I'd like to place some facets on my left hand but I have no way to grab with my right hand.  For those with limited mobility it'd be nice if we could temporarily freeze some or all anchors in place so we have full use of this feature like able-bodied users.

**Comment by epicEaston197** [comment]
Another thought I just had. Would this add more steps to the avatar creator?
It would be really useful to set up the facet anchors when setting up an avatar but this would increase avatar setup complexity more and add more visual clutter to a process that's already considered difficult

maybe it could be its own toggle like "show tool anchors" but in this case it would be called "show facet anchors"

**Comment by Frooxius** [comment]
I've added this in 2024.5.28.94! Yay!
