### ISSUE TITLE
Body Node Slot Head/Hands Avatars

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#1805]
### Describe the bug?

When using the Body Node Slot flux node on an avatar it will retrieve slots from within the avatars armature, but when using it on a head/hands avatar it will instead retrieve the body node slot at the root of the avatar. This inconsistency makes it very hard to use these values with any amount of certainty of which slot you have

### To Reproduce

view the head Body Node Slot on a regular avatar, view it on a heads/hand avatar and compare

### Expected behavior

for Body Node Slot to return similar slots between regular avatars and head/hands avatars

### Screenshots

![2024-04-22 01 40 40](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/9d07a9a4-6aa8-4ed5-a729-48e0d2e3e4ae)

### Resonite Version Number

2024.4.18.1398

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

N/A

### Reporters

ultrawidegamer

**Comment by kulzae** [comment]
This will occur with full il avatars as well and it's behavior seems to be inconsistent

**Comment by epicEaston197** [comment]
This issue also affects my nose booper which is intended to increase the user's head size by x5 for three seconds it does this by using the body slot node and if I want to demonstrate this functionality to anyone they need an avatar for it to function which is inconvenient

**Comment by Merith-TK** [comment]
It appears that when the BodyNode on the "rig" does not exist, it will default to the Proxies, which causes issues for systems like Gabriel's OpenPrint that utilize the hand body node to find the tool and perform actions based off where its pointing

Or my modification that uses your "laser image" when in desktop.

**Comment by shiftyscales** [comment]
> to find the tool and perform actions based off where its pointing

Assuming the structure of an avatar is on our list of things to avoid, @Merith-TK. https://wiki.resonite.com/Things_to_Avoid#Names_or_structure_of_an_Avatar

As you have seen, building things in such ways are prone to breakage. If you need functionality to determine where users are pointing their lasers, please open a feature request focusing on that/your use-cases for needing that.

@ultrawidegamer - Requesting again, could you please provide context on your needs and use-cases. Otherwise for now, I am closing this issue.
