### ISSUE TITLE
Change default Maximum Skinned Mesh Weights per Vertex from unlimited to four

### ISSUE THREAD

**Issue by Hayden-Fluff** [Yellow-Dog-Man/Resonite-Issues#1811]
### Is your feature request related to a problem? Please describe.

I've come across a few avatar creators that aren't even aware this is a limitation of real time rendering engines, if this isn't a default setting in Resonite, users may be unaware of problems that may exist in other platforms and engines due to this setting.

### Describe the solution you'd like

The default setting should be changed to Four instead of Unlimited to maintain parity with other platforms, users can then change this at their own digression if desired.

### Describe alternatives you've considered

Make sure avatar creators testing in Resonite are aware of this setting, and make sure they test with it set to Four to ensure compatibility with other platforms.

### Additional Context

Unity by default has this limit set to Four weights per vertex, this is also the maximum, offering no "unlimited" option.
Seeing as how most other social VR platforms use Unity for user content, having a default quality parity seems like a good option, with the alternative ensuring users are well educated about the differing defaults.

I have not been able to test if this is actually unlimited as the name suggests, as I only saw it default to unlimited when I was poking through the options and I had my concerns with it.

### Requesters

`@hayden_fluff` (Discord)

**Comment by JackTheFoxOtter** [comment]
> I'm not certain that I understand the relevance of what other platforms has to do with what we choose to do with ours. If we can offer higher quality option in future, why wouldn't we take it?

Using more bones with influence than 4 per vertex would likely result in some form of breakage / artifacts on models that aren't designed for it. But then again I think most exporters already limit the bone weights so I don't think this would be much of an issue? Just chiming in because it wouldn't automatically be "higher quality" to have more bone influences unless the model was specifically designed for it by the artist (which I've never heard of so far).

**Comment by JackTheFoxOtter** [comment]
Yes, but it can quickly happen by accident that there are weights accidentally applied to the wrong bones, depending on workflow. As long as the accidental bone has less weight than the 4 largest ones, it wouldn't have a visible impact on the end result, so it could easily be overlooked. If such a model was uploaded with more than 4 weight (which, again, I'm not even sure how many exporters actually do that by default), it could result in the described breakage. Personally I'd agree with making 4 the default value, but it won't have an adverse effect until the maximum might get changed in the future anyway.

**Comment by JackTheFoxOtter** [comment]
If anything though I think the SkinnedMeshRenderer itself should have a maximum bone weight exposed that can be set on a per-model basis, so that even on unlimited, it wouldn't use more than the configured maximum per skinned mesh. This is something that's dependant on individual assets and there won't be a general answer that applies to all meshes.

**Comment by JackTheFoxOtter** [comment]
> The mesh inspector allows you to trim the vertex bone weights to the target number of bones.

Ah! Well that's at least a quick fix then in case something does break.

> That is on the creators to optimize their content for the platforms on which they intend to distribute it, @Hayden-Fluff.

Kind of, but many people upload avatars they bought for other platforms without the creator ever having optimized it for Resonite to begin with. This is easy to say, but at least currently doesn't reflect the reality. Considering we have the ability to edit some mesh data currently, and likely all mesh data eventually, this is less of an issue. It should perhaps be something the import dialog asks you about though.

**Comment by Frooxius** [comment]
> Unity by default has this limit set to Four weights per vertex, this is also the maximum, offering no "unlimited" option.

This is incorrect. We are using Unity as a renderer, which does have this option: https://docs.unity3d.com/2019.4/Documentation/ScriptReference/SkinWeights.html

> The default setting should be changed to Four instead of Unlimited to maintain parity with other platforms, users can then change this at their own digression if desired.

I think this is a poor reason to make this change. Just because other platforms offer lower quality, doesn't mean we have to as well.

I'd say that's actually worse, since people might eventually bring in content that has more and be confused on why it's broken.

But mostly like Shifty said, our data structure doesn't support more than 4 right now, so it's a bit moot anyways, but that is something we do want to expand.

**Comment by Hayden-Fluff** [comment]
> This is incorrect. We are using Unity as a renderer, which does have this option: https://docs.unity3d.com/2019.4/Documentation/ScriptReference/SkinWeights.html

Forgive my inaccuracy, I did not remember seeing this last time I had looked through the Quality settings in Unity, I just verified in Unity 2022.3, and it is indeed an option, though I highly doubt other platforms take advantage of this, and new Unity projects do default this option to 4 bones.
