### ISSUE TITLE
Duplicate patreon messages in inbox after logging in for the first time

### ISSUE THREAD

**Issue by Nwhis** [Yellow-Dog-Man/Resonite-Issues#1871]
### Describe the bug?

Supported the patreon for about 7 months before actually starting the game and setting up my account for the first time, consequently got 7 duplicate messages acknowledging my patreon support for each of the 7 months I had supported it before actually logging in.

### To Reproduce

Support patreon for more than one payment cycle before logging in for the first time.

### Expected behavior

Send a maximum of one confirmation message for a newly verified user.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/17502190/700c4d04-8dc7-4ee2-8b35-2b9e00dc8798)

### Resonite Version Number

2024.4.26.1258

### What Platforms does this occur on?

Windows

### Log Files

`11:53:35 PM.898 ( 75 FPS)	SIGNALR: MarkMessagesRead - Read 7 messages from U-Resonite on 4/28/2024 4:53:35 AM`

**Comment by Nwhis** [comment]
Update: worth noting this message is apparently triggered every single month as well, and I question if that's intentional or not.. (but it explains the possibility of several of them appearing at once at the start)

**Comment by shiftyscales** [comment]
> Update: worth noting this message is apparently triggered every single month as well, and I question if that's intentional or not.. (but it explains the possibility of several of them appearing at once at the start)

Yes. This is by design, @Nwhis. These messages act as confirmation to the user that their Patreon pledge has been properly processed, and applicable perks for their given tier are active. As such, it is still important that we send them, even if a user is not actively using Resonite.

If you had received more messages than you had months pledged- that might be a bug, and could be something that is looked into- but based on your report, everything here appears to be working as intended.

I do not believe it would be worth the engineering effort to rework the Patreon integration to account for queued messages on account creation at this time, but we thank you for the suggestion, and support, even before you had begun playing Resonite.
