### ISSUE TITLE
Contacts organization improvements

### ISSUE THREAD

**Issue by Madamblu** [Yellow-Dog-Man/Resonite-Issues#1880]
### Is your feature request related to a problem? Please describe.

Messy and disorganized contacts list and lack of open messages

### Describe the solution you'd like

_The ability to split contacts into separate folders or groups_ and a setting to allow direct messaging by those within your current session similar to discord allowing the toggle of direct messages per server and having the ability to send "message requests"

### Describe alternatives you've considered

Being able to create labels which appear below the username of the contact, to show which group they are from or friend status, i.e: Mentor, acquaintance, friend, close friend, USFN, etc

### Requesters

U- Rosebloodinthegarden (would rather not give my discord name to be credited)

**Comment by shiftyscales** [comment]
We are not going to continue to make incremental improvements to the legacy contacts UI.

> Being able to create labels

This is covered by #915.

> the ability to send "message requests"

This is covered by #943.

> Messy and disorganized contacts list

This is covered by the Contacts UI Rework #1116.

Per our [reporting requirements](https://github.com/Yellow-Dog-Man/Resonite-Issues#reporting-requirements) it is better to focus on a single issue, rather than compounding a bunch of requests into a single issue.

As the requests made in this issue are better covered by existing issues, I'll be closing this out as a duplicate. Thank you for your understanding, @Madamblu.
