### ISSUE TITLE
FireOnOSCMessage ProtoFlux

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [Yellow-Dog-Man/Resonite-Issues#1896]
### Is your feature request related to a problem? Please describe.

One useful feature of OSC is firing events based on button presses, but detecting events directly is a bit janky, see below.

### Describe the solution you'd like

A ProtoFlux node that fires when a OSC message is received that matches a pattern (this should include the payload)

### Describe alternatives you've considered

I saw someone who checked when a value was one then set it back to zero.

### Requesters

@EmergencyTemporalShift

**Comment by FlameSoulis** [comment]
Couldn't you link a FireOnChange node to the value of the OSC Reader?

**Comment by ProbablePrime** [comment]
> Couldn't you link a FireOnChange node to the value of the OSC Reader?

Yes, this is how I'd advise doing it right now.

**Comment by EmergencyTemporalShift** [comment]
Doesn't FireOnChange come with a small overhead that adds up with many? The nice thing about this is the event would only fire when there is a message, an event that presumably already exists.

**Comment by BlueCyro** [comment]
> > Couldn't you link a FireOnChange node to the value of the OSC Reader?
> 
> Yes, this is how I'd advise doing it right now.

This unfortunately doesn't cover cases where multiple OSC values might be received within a single frame.

**Comment by FlameSoulis** [comment]
I thought I was beginning to see where the details were missing.

So, to best understand what would work, in Web sockets, when a message is received, it creates a pulse alongside the message received. Thus, when a pulse comes in, you know a message did as well.

Since OSC can have many channels through which a message can arrive, I'm assuming the desired project can have some, but not all, or a usable pattern of data are updated.  What is being asked for is a node that, when referencing an OSC receiver, makes a pulse each time a message is received, regardless of the value it sends is being tracked?

**Comment by EmergencyTemporalShift** [comment]
Also, such events could also contain bundled messages, somethings that the OSC standard supports.

**Comment by BlueCyro** [comment]
So I think what this boils down to is an OSC analog of the websocket events nodes then.

**Comment by ProbablePrime** [comment]
Thanks for your issue, I'm moving conversation to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1888 for the conversation on this issue. We've got a few duplicates, so I'm merging into the one that Froox responded to.
