### ISSUE TITLE
Cloud home storage indicator does not function

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1904]
### Describe the bug?

The cloud storage indicator has not been functioning since launch

### To Reproduce

Open the cloud home and look at the storage indicator

### Expected behavior

The storage indicator should display my storage used

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/c19f3c58-971b-4f75-9fee-65be4500b39d)

### Reporters

@epicEaston197

**Comment by epicEaston197** [comment]
okay thank you for the information

**Comment by epicEaston197** [comment]
> seems to be caused by the "StorageUsageStatus" component not outputting any information

also you did not provide an owner ID in the storage indicator
even if you do assign it the issue remains

**Comment by LuZanth** [comment]
Question: Does this still happen in the version that loads when you have no favorited world?

**Comment by epicEaston197** [comment]
> Question: Does this still happen in the version that loads when you have no favorited world?

all i did was open up the Resonite cloud home uploaded by the Resonite team

**Comment by shiftyscales** [comment]
@epicEaston197 @RueShejn - This component only works in the user's assigned cloud home. You need to have the world favourited for it to be functional. That is by design, not a bug. It is only meant to be used in a user's home, not in worlds outside of it.

I just tested, and it works without issue inside of my cloud home.
