### ISSUE TITLE
UniversalMediaPlayer crash

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#1907]
### Describe the bug?

Resonite crashed, UniversalMediaPlayer in the stack trace.

### To Reproduce

Unknown, probably that same old issue with video players that randomly crash.

### Expected behavior

Not crashing when video players are used.

### Resonite Version Number

2024.5.1.68

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3 via SteamLink

### Log Files

[Crash_2024-05-01_202319784.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15181134/Crash_2024-05-01_202319784.zip)
[VIXEN - 2024.5.1.68 - 2024-05-01 22_13_57.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15181135/VIXEN.-.2024.5.1.68.-.2024-05-01.22_13_57.log)

**Comment by Frooxius** [comment]
Thanks for report! 

We are aware that UMP causes crashes sometimes, but unfortunately there is little we can do with UMP itself, since it's no longer actively updated. 

Our goal was to move to the official libVLC integration: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1476

I'll close this issue, as that's handled by the one I linked.

**Comment by shadowpanther** [comment]
Yeah, I made this issue because I didn't find any referencing the UMP. I know the issue itself is old.
