### ISSUE TITLE
Add "is receiving" to OSC receiver

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1920]
### Is your feature request related to a problem? Please describe.

Right now you can't trigger logic depending on if the OSC receiver is receiving data or not for example i'm using OSC to use my phones orientation to move my head around but there is no way for me to have a default behavior for if the OSC server is offline resulting in my head Being in a really inconvenient position

### Describe the solution you'd like

I want a `is receiving`value on the OSC receiver and if this doesn't make sense I just want a value that tells me if the OSC receiver is currently receiving data or not

### Describe alternatives you've considered

Figuring out when one of the values stops updating

### Requesters

@epicEaston197

**Comment by Frooxius** [comment]
This isn't unfortunately possible due to how OSC works, particularly over UDP.

It's a "connectionless" protocol, so there's no way to determine if there's a connection, because there's never really one. It's just passively listening to data, whenever and wherever it arrives from.

If you want this, you'll have to implement your own logic for it - e.g. periodically sending some "heartbeat" value and checking if it stops updating all of sudden.

**Comment by epicEaston197** [comment]
Thanks that is understandable I was suspecting this
