### ISSUE TITLE
Out of sequence new user prompts

### ISSUE THREAD

**Issue by Zbossgamer** [Yellow-Dog-Man/Resonite-Issues#1951]
### Describe the bug?

I recently joined resonite for the first time and was greeted by the first time user screen. It asked me what my prefrances where Left vs Right hand, Smooth vs Snap turning, ect. After that it asked me to create an account or continue as a guest. I created an account and entered the totorial world only to realize that all of my settings I just selected did not save. 

### To Reproduce

Assuming just open resonite for the first time and create a fresh account. 

### Expected behavior

My assumption is that when you create an account your prefrences are set to the default Resonite prefrences, currently you create an account after setting your prefrences. I would expect for the user to set there prefrences after creating an account so that it will actually save to the user instead of being immidiatly forgotten when creating your account. I understand that they might choose to be a guest although I still dont see the problem in letting the user select preferences after selecting guest. This is more of a user experience bug than a tangable visual or gameplay bug.

### Resonite Version Number

2024.5.1.68

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

N/A

### Additional Context

I joined resonite yesterday, voiced my experience to someone in resonite and they pointed me to the GitHub so I figred I would come here.

### Reporters

Resonite: Zbossgamer
Discord: zbossgamer

**Comment by epicEaston197** [comment]
okay so from my understanding that setup screen uses the new settings system and if you're not logged in it stores your settings locally on your machine and when you create an account that is technically a new settings profile meaning that your settings reset because it can't write settings to an account that doesn't exist yet which is not preferable
**this is just speculation on my part but it's feasible in my eyes**

this could possibly be fixed just by writing the local settings to the new settings profile when your account is created

**Comment by shiftyscales** [comment]
Thanks for taking the time to report your issue, @Zbossgamer.

Seeking input from @Frooxius - I suspect Easton's suggestion might be in the right area, and that the local machine settings are not properly persisted to the newly created account.

**Comment by Frooxius** [comment]
This should be fixed in 2024.5.23.1416! The new system now inherits the settings from local values after logging in when the settings are not created yet. 

Thanks for report!
