### ISSUE TITLE
Desktop physical grab not working 

### ISSUE THREAD

**Issue by Lewisvz** [Yellow-Dog-Man/Resonite-Issues#1955]
### Describe the bug?

Can't grab dynamic bones and some other items because desktop physical grab doesn't work.  Only works in VR which is very inconvenient for testing and debugging.

### To Reproduce

Try to grab a dynamic bone set to grab. Won't work.

### Expected behavior

Should be able to grab grabble dynamic bone.

### Resonite Version Number

Latest 

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Log Files

Nothing to see here.

### Reporters

Irix

**Comment by shiftyscales** [comment]
Currently this is by design, not a bug- because desktop users have no native means to directly manipulate their hands, and reliably interact with things, we had disabled desktop physical grab to prevent accidental grabbing. Previously, physical grabbing was enabled in desktop, but resulted in a lot of accidental grabs. We could revisit re-enabling physical grabs if we were to implement a native desktop hand poser/desktop hand tracking.

**Comment by Lewisvz** [comment]
Personally didn't have issues with accidental grabs.  However, that's why I originally asked for a toggle.  It's a useful feature for developers at the very least.  I used to have a mod for it however the creator of it no longer plays game and did not update the mod.  Can we at least get a launch option?  I don't understand why this needs to be so difficult.
