### ISSUE TITLE
Glue Block component

### ISSUE THREAD

**Issue by BaxterOttoman** [Yellow-Dog-Man/Resonite-Issues#1967]
### Is your feature request related to a problem? Please describe.

The glue tip in the wrong hands can lead to many problems. The selection area can grab world slots, user slots, anything, and slam them together into an object that is freely grabable/movable/deletable. This leads to mistaken destruction and manipulation of world geometry.

### Describe the solution you'd like

A glue block component that can be applied to a hierarchy would be useful for situations in which brush tools are being used to draw/sculpt in Resonite with the intention of using the glue tool to bake them together.

The desired use would be to apply the component to a slot and when the glue tip is used, children slots to the slot with the component should be ignored by the glue tool.

### Describe alternatives you've considered

The other option is to give the glue tool a wide berth or set things up ahead of time to parent strokes under a specific slot and baking that specifically. Both work, but specifying whole hierarchies would allow for more control in a situation where less familiar users are attempting to use the glue tip.

### Requesters

Baxter

**Comment by shiftyscales** [comment]
Preventing modification of a given hierarchy would be better handled via the hard permission system. #1103.

If the glue tool has usability issues with accidentally glueing things you do not want it to, it would be better to focus on and report that as a usability issue with the tool itself rather than working around the problem by addition of additional components to compensate for its issues.
