### ISSUE TITLE
Access to alternitive/extra tools when using the modifier keys in desktop mode

### ISSUE THREAD

**Issue by AmasterAmaster** [Yellow-Dog-Man/Resonite-Issues#1968]
### Is your feature request related to a problem? Please describe.

This came to me as a hallucination of me hitting a tool keybind and holding shift on the keyboard, and I "thought" that Resonite supported accessing the other tools in this way (as I did not recognize the tools at the time). Then later when I attempted this, I discovered that Resonite does not actually support this feature and I would like to request it.

### Describe the solution you'd like

I would like Resonite to support holding down a modifier key (Shift, Ctrl, Alt, and/or possibly some combination of these once you have more available tools) while pressing the number keys to equip a tool.

### Describe alternatives you've considered

I could just go into the Resonite Essentials folder and pull out the tool, but that would be slower than having the muscle memory to just getting the tool you need at an instant (like getting a Geometry Line Brush tool by holding shift+5, or the Color Tool with Shift+2 for example).

### Additional Context

This could allow you to have more room to place tools you expect a user would need without being cramped with just the number keys alone.

I will also address the issue (https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/772) as it can be related (in case a user would want custom keybinds for moving the extra tools around), however this feature is more to do with having modifiers to access more tools that are available and not so much the customization of the tool placements.

### Requesters

AmasterAmaster

**Comment by shiftyscales** [comment]
Keybinding editing #23, particularly as it pertains to modifying/adding/changing which tools spawn (#772) already exist as issues as you highlighted.

I do not think this issue is sufficiently distinct from the aforementioned issues, as the needs it establishes (use of modifier keys to spawn out additional/different kinds of tools, and the inventory being slow to navigate) are addressed by the other linked issues, as well as the inventory UI rework #1119, and #461.
