### ISSUE TITLE
shareStorageWithUser Command Non Functional

### ISSUE THREAD

**Issue by Kinectika** [Yellow-Dog-Man/Resonite-Issues#199]
### Describe the bug?

if you try to share your storage with a user it just says 0.00b shared no matter the amount put in the command and the recipients storage never increases 
![image-6](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/48077461/7e17eafe-3804-4f78-b610-7b8ea6788812)

### To Reproduce

use the /shareStorageWithUser bot command to share storage with a user

### Expected behavior

recipient revives storage from the sender 

### Screenshots

![image-6](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/48077461/f7a1112f-e361-49fe-8300-b8596a89db34)

### Resonite Version Number

any

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive/Desktop

### Reporters

@Kinectika#6673 U-Kinectika

**Comment by sveken** [comment]
I had this issue and asked about it in a support ticket. 
The wording of the message isn't that great. It means the user is using 0 bytes of the storage you just shared. 

However in my testing the end user also doesn't see their quota increase on their end. Unsure if that is expected behavior too or it really is broken?

**Comment by sveken** [comment]
Further testing even the message in the bot command is fixed now as of todays update. all is working

**Comment by ProbablePrime** [comment]
Yup this is resolved see: https://discordapp.com/channels/1040316820650991766/1154514012143362151/1163651491307995156

Thank you for the report!
