### ISSUE TITLE
Contacts+ sessions and lower show as Private world in discord

### ISSUE THREAD

**Issue by ExoTheWicker** [Yellow-Dog-Man/Resonite-Issues#1999]
### Describe the bug?

When a session's access level is not set to Anyone or Registered Users. It shows the user as being in a private world.

### To Reproduce

With the discord-rich presence set to full set a session to anything lower than Registered users.

### Expected behavior

The rich presence shows the proper session access level.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/e2465f65-4e5b-4f71-8994-d6323a383188)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/c0b31f36-de58-4a32-9219-ed9d6dbf15ce)

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/ba68e166-413e-49dd-ac29-15caf724c029)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/da32a31a-dfa6-434f-a04d-3e38c88a4761)

### Resonite Version Number

Beta 2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop and Index

### Log Files

[DESKTOP-I5BSEJ5 - 2024.5.7.505 - 2024-05-07 10_41_49.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15237268/DESKTOP-I5BSEJ5.-.2024.5.7.505.-.2024-05-07.10_41_49.log)

### Reporters

ExoTheWicker (Discord and Resonite)

**Comment by shiftyscales** [comment]
From the perspective of Discord, and our API, this is technically correct. They are not a contact, and thus would not have access to that information from the API. The only expected sessions that should provide session information via Discord would be "Anyone" public (non-hidden) sessions.

**Comment by TisFoolish** [comment]
I don't think it's unreasonable to expect the Discord status to show that info when it's the user themselves that is giving that info, especially since "Full" implies that it's giving the full info, not a small piece of it. It'd be no different than the user manually setting their status to "In Res, Contacts+ World".

**Comment by ProbablePrime** [comment]
- If a session is not publicly available, it doesn't report it status to the public (The world browser etc) and we're using that to make our "bar" for Discord.
	- If the session is publicly available, it should be in Rich Presence systems.
	- If the session is not, then it shouldn't. 
- Doing anything else would open up a security issue where users can use Rich Presence to track users in Sessions, that they would not otherwise be able to see.

We have no way of knowing if your discord contacts are your friends or who they are.

As an example say I am in a contacts session with team members, we're discussing a super secret project. With this change the session name would leak to discord despite the fact that it would NOT have leaked via our systems.

**Comment by TisFoolish** [comment]
No one is saying that the session name, thumbnail, etc would be visible, just what the session requirements are.  Plus I had also suggested adding a new setting that people would have to opt into to alleviate concerns. 

If a person wants to be able to share that they're in a contacts+ world via the Discord Rich Presence setting, then they should be able to, just don't force it on everyone.
