### ISSUE TITLE
[Setting] add option to use arrow keys instead of WASD

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2029]
### Is your feature request related to a problem? Please describe.

Some people are left-handed or have mobility issues

### Describe the solution you'd like

A way of switching the movement from WASD to arrow keys

### Describe alternatives you've considered

Using a mode that's on some keyboards that swaps the keys

### Additional Context

i saw a negative steam review they mentioned they wanted custom keybinds but their core issue was with them being left-handed and having mobility issues so I thought this would be a really important accessibility feature

here's a quote from it (not naming names)
>I'm left handed and do not, and have never used WASD for movement as it's painful for me and I already have permanent wrist damage.

### Requesters

@epicEaston197

**Comment by ko-tengu** [comment]
I'm going to double hit this one with a duplicate and also a suboptimal implementation goal over the more common ijkl or 8456 answers.

https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/23

**Comment by epicEaston197** [comment]
> I'm going to double hit this one with a duplicate and also a suboptimal implementation goal over the more common ijkl or 8456 answers.
> 
> #23

maybe but this might be a common enough problem to where it would warrant this feature
but idk

**Comment by shadowpanther** [comment]
The key (re)binding would allow anyone to set their preferred method of control (directionals, IJKL, 8456 or whatever), so I agree #23 covers this request.

As a side note, I remember the period (early-ish 00s) when I had to rebind almost every game to WASD because the default bindings at that time were to directionals. Also, the left and right arrows were often bound to turn, not strafe, because computer mice were rare in 80s-90s.
