### ISSUE TITLE
Add loading details to loading screen

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2054]
### Is your feature request related to a problem? Please describe.

Right now we only have the loading bar telling us details on the loading progress

### Describe the solution you'd like

I want a bit of text at the bottom of the loading bar that tells me what is being initialized

### Describe alternatives you've considered

Things like [ResoniteModLoader](https://github.com/resonite-modding-group/ResoniteModLoader) and [monkey loader](https://github.com/ResoniteModdingGroup/MonkeyLoader.GamePacks.Resonite) do this

### Additional Context

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/f88fe312-7e44-4651-b8ed-86c886a323eb)

### Requesters

@epicEaston197

**Comment by LeCloutPanda** [comment]
Well for the average user it would be a bit too much and become confusing but what about those who want to see what's going on? from a debug stand point as well it could be nice to see what stage stuff is hanging at rather then going through the log file instead of just having a live preview. 

What if we had an option for it under ``Misc``? because personally my self and I am sure a lot of people would like to see what things are doing during runtime.

**Comment by Frooxius** [comment]
For debug standpoint, you should always use logs and not rely on visuals - they contain more information and are more up to date.

There's not really any benefit in having the visual.

Settings are complicated - they require the engine to be loaded... which it's not during loading process. So making that work requires more engineering effort - and I don't see any need for this that would justify putting that engineering time into this.

**Comment by epicEaston197** [comment]
I wouldn't use this feature for debug purposes I just think it looks neat

**Comment by AmasterAmaster** [comment]
I would say having more information to show is beneficial, even if it is daunting to new users, for the reason of when Resonite decides to freeze, it will show exactly the point where it froze because the text will reveal it on the loading screen. This helps pinpoint where we can show the devs where the application hung when trying to load/initialize. But this is just my opinion with the programmer mindset.

@Frooxius and yes, debug logs are way better for this, but at least having more verbose text reassures that the user would not complain in the wrong direction (as it would clearly show where and when, instead of the user "guessing" what happened).
