### ISSUE TITLE
User sometimes logged in to local home

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2071]
### Describe the Underlying Issue

Sometimes when you load into your local home you might load into your avatar which could cause issues

### To Reproduce

open Resonite and you might load into your avatar

### Expected Behavior

My avatar should not be loaded when I open my local home
right now this is a bug and will potentially be fixed but this cloud avatar load option should be disabled as a redundancy

### Screenshots / Video

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/b96b00a4-965a-4c24-959a-aa7b2bf1bece)

### Reporters

@epicEaston197

**Comment by JackTheFoxOtter** [comment]
I'm pretty sure the fact that the local home logs you in and loads your avatar sometimes is a bug, so it might be better to focus on fixing that, rather than working around the bug.

**Comment by epicEaston197** [comment]
> I'm pretty sure the fact that the local home logs you in and loads your avatar sometimes is a bug, so it might be better to focus on fixing that, rather than working around the bug.

Yeah and I did state that in the issue and I would like that to be fixed I'm requesting this to be implemented as a redundancy measure to prevent issues

**Comment by Frooxius** [comment]
Like Prime mentioned, this is XY problem. 

Generally you should report the issue, which is "Avatars are loading in the local home" or "Avatars shouldn't be loading in the local home", not a particular way to fix this.

In this case, I wouldn't accept this as a solution, since it's treating a symptom and not the underlying cause - the main problem here is that local sometimes loads after the user is already signed in, so it inherits that, which it shouldn't. We need to make sure that Local always loads first, or is loaded in a way that doesn't link the user to their cloud profile.

**Comment by Frooxius** [comment]
This is now fixed in 2024.6.5.198. Thanks!
