### ISSUE TITLE
Add a Resonite Wiki Shortcut Facet to the Home tab

### ISSUE THREAD

**Issue by FlameSoulis** [Yellow-Dog-Man/Resonite-Issues#2115]
### Is your feature request related to a problem? Please describe.

Doing my review of the Steam reviews and other discussions has many holding issues with finding out helpful information. This seems to stem from not knowing how to find certain components to having a hard time understanding certain systems, and that the only avenue of information are from other users, which may not work well with those who prefer a less social acquisition of knowledge.

### Describe the solution you'd like

Adding a "Visit the Wiki" facet to the home tab is one idea. With a simple shortcut, this could help people find the information they need and even aid experienced users who may need additional context.

### Describe alternatives you've considered

I'd say some kind of internal browser to avoid VR users from getting confused on why no additional window appeared, but that is reliant on another feature request (#956)).

### Additional Context

I know this isn't a cure-all solution, but showing there is a place for additional help may help reduce confusion since it might not be known there is even an information repository.

### Requesters

Flame Soulis (flamesoulis)

**Comment by Frooxius** [comment]
We were actually planning to add a whole Help Tab, which would include this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1123

I think that might be better solution overall, since it'll be very clear "Help" button that can draw users and it'll help to clutter the Home screen a bit less - one thing we found is that adding more stuff to the main screen tends to overwhelm the users.

**Comment by FlameSoulis** [comment]
The latter part I can absolutely agree with.

Closing since the help tab is better (I was looking for Wiki related mentions, and somehow that one didn't turn up).
