### ISSUE TITLE
Option to Disable Sociable Notifications When User is Inaccessible

### ISSUE THREAD

**Issue by JewelTK** [Yellow-Dog-Man/Resonite-Issues#2181]
### Is your feature request related to a problem? Please describe.

Getting notified of a user being on Sociable status just to see they're in a session inaccessible without an invite is annoying and feels counter to the purpose of the notification. I feel it defeats the functionality of making it easy to know which of my friends I can seamlessly get into a session with. Now I'm back to having to ask for an invite as though they were just set to Online. If the intention is primarily for users to mark themselves as "Please invite me," it makes the Sociable status seem more like a blind mass ping to request an invite from anyone rather than an initiation of desire to socialize.

### Describe the solution you'd like

An on/off toggle for being notified of Sociable users who are inaccessible without an invite.

### Describe alternatives you've considered

A gradient of options for what kinds of inaccessible sessions the recipient would like to receive notifications. Options could be Private/Hidden sessions, Contacts Only, Contacts+, etc.

### Additional Context

This request comes from the perspective of a user who almost always joins sessions rather than host sessions. To me, the sociable notification is best for users to broadcast they'd like to be joined rather than invited.

**Comment by Frooxius** [comment]
This would defeat the point of the feature. If you read the release note or the message, "Sociable" user might be looking to be poked or invited in. 

This doesn't necessarily mean "Join me", but "Invite me" - that's the purpose of the notification. If you see user with this - maybe invite them to your session?

If we add this, it effectively defeats the purpose of this status - because user who's alone in Private session won't get invited into groups.

If you just join sessions and don't host - you can just disable this notification.

**Comment by GlitchFlux** [comment]
I agree that this is a blind mass ping and so far in its implementation its really displeasing me as its not being used as intended and all that it really does is beg for attention. I feel it should either be a swap Join me or invite me, or at the very least make it so the message is able to be swapped around. It would be great when you set, to prompt it as a notice "Hey, invite me" or "hey, come hang out". This feature is not working as intended and its already causing silent backlash as everyone ive listened to issues from is discouraged from github because every issue gets autoclosed.

I like the input Jewel has, its too bad nobody in the minority who wants to even use Github will see it from the issue being closed.

**Comment by Frooxius** [comment]
That's pretty much what the intent of it is though - it's a way to indicate that you're looking for a session to be invited in - the notification says that and the release notes do as well.

**Comment by JewelTK** [comment]
That may be the team's intent for the feature, but so far I don't think that's how people are using it. And regardless, Resonite is built on letting users customize and utilize tools in a way that works for them. Saying "This is how we intended it to be used" and refusing another perspective on the feature feels extremely antithetical to the platform's values of user freedom. Vive _**intends**_ for their trackers to be used for FBT and _**doesn't intend**_ for their controllers to be used for FBT. But some users still want to do cool stuff with them outside the boundaries of what the creator intended. I totally understand making something with intent/vision for how it should be used, but there is a lot of value in seeing how it's actually used by people and working with that rather than against it.

**Comment by shiftyscales** [comment]
@JewelTK - I think the feature as it is useful for both use-cases depending on context. E.g. if a user is in a public, open session, and has the sociable status, that feels to me like an invitation to hop in/join them.

Likewise- if the user is in private- it indicates to me they probably want users to invite them instead.

The status is broad in its intent, and purpose- it simply signals that particular user wants to be actively in sessions with other users/is seeking people to talk to/interact with- that goes both ways- as a user looking for an invite, and as a session host looking for more people to drop in.

I'm in the process of collating feedback and have found a few common threads for minor tweaks that can be made to improve this feature. Thank you for your feedback.

**Comment by shiftyscales** [comment]
@GlitchFlux - We require users posting issues and feedback to provide it using neutral, and objective language. I think you will find your feedback is better received if you follow our [reporting requirements](https://github.com/Yellow-Dog-Man/Resonite-Issues#reporting-requirements)

> - **Use objective, and respectful language** for any posts/comments submitted (negativity, hateful/angry issues/comments are liable to be edited or removed)

**Comment by JewelTK** [comment]
@shiftyscales very well put and I agree greatly that it's a great two-way system. I'm very grateful you understand my desire to tailor it to my needs. There's a lot of potential for this system to empower users to socialize more seamlessly and I cannot wait to see what tweaks the team makes to make it even better.
