### ISSUE TITLE
"Status Persistence" setting

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#2191]
### Is your feature request related to a problem? Please describe.

Users can sometimes forget their status on something undesired across restarts.

### Describe the solution you'd like

A "Status Persistence" setting which functions similar to the existing "Mute Persistence" setting.

This would allow users to set their preferred online state between "Last Status" and any other status available. This would also expose the option to let users start as invisible without use of the existing `-Invisible` command line argument.

### Describe alternatives you've considered

Default users to "Online" when starting Resonite, and automatically clear the last status unless it is explicitly set by a command, e.g. `-Invisible`- however, I think a setting would be a better/more visible option here.

### Additional Context

Following up from some feedback I have seen indicating that some users have forgotten what status they were on (e.g. sociable) across sessions while restarting.

### Requesters

@shiftyscales

**Comment by ExoTheWicker** [comment]
I've done this on multiple occasions and think this feature should be added

**Comment by Azavit** [comment]
I agree with this feature but for the exact opposite reason than the sociable status.

Sometime I forget I'm set to invisible or busy then wonder why no one realizes I'm around.

**Comment by Frooxius** [comment]
I think this is a bit tricky though, because some statuses you might want to remember, while other you might not.

Say you set yourself to Invisible - you might want to stay invisible on the next start - this is actually one of the reasons why we remember the status in the first place, to avoid users accidentally "leaking" they're Online.

Other statuses, say Sociable/Busy they might want to keep.

I wonder if this should be per-status setting - like which ones you want to remember and which ones you want to reset.

Perhaps recency too - like if you logged in within an hour since last time it was saved, keep it, if it was longer, then just reset it.

**Comment by shiftyscales** [comment]
If you think it's worth the extra engineering effort I'm alright with that.

I think the only status that is particularly relevant/of any particular importance to be kept is 'invisible' though- so another approach would be to have invisible override or write to that setting.

I don't think it matters as much if 'sociable', 'online', 'away', or 'busy' are remembered across sessions- as those could be covered by the setting itself- either having it set to 'last status' or selected directly.

You do raise a good point though. Recency between sessions could play a factor, e.g. if someone needed to restart quickly- but still continued to use Resonite- it's effectively still the same session from the perspective of the user.

Regardless to that- if "Invisible" is explicitly set in the setting- I think it should still be set on each launch to match the behaviour of the `-Invisible` command line argument.

In feedback relating to the Sociable status- users highlighted concern of the status persisting across sessions- so if you do opt for per-status continuity- I'd recommend defaulting Sociable to not be remembered so the user has to explicitly enable it after launch unless they have it set as their default status intentionally in the setting.

**Comment by Frooxius** [comment]
I understand that users might not want to default Sociable to be remembered. I just got concerned that we might end up causing an accidental "privacy leak" when Invisible doesn't get remembered.

I guess the question here is - should there even be a setting separate for Invisible? Or do we always enforce that one to be remembered? 

We could add a separate setting for that, default to be remembered at all times. Perhaps other statuses don't need separate setting as much and could be grouped into one to keep things simpler.

**Comment by JackTheFoxOtter** [comment]
I do think invisible and the rest should be treated separately. What would make sense to me would be being able to choosing either a default presence or making the current presence persistence, but by default invisible should be excluded from that, and only reset automatically if explicitly enabled by the user.

That said, I can also see situations in which I'd want the busy status to be persistent, but the sociable status to automatically reset. Since this is a bit of a preference thing and comes down to how individual users use the different presences, it might make more sense to just make them all separate toggles, since that would allow the maximum flexibility without making assumptions about how users might interpret / use the individual presences.

I don't think UX wise this would be very confusing / overwhelming. I imagine a "default presence" option where you can choose which one should be used when the previous presence wasn't a persistent one, and then a toggle per presence for "is persistent".

**Comment by shiftyscales** [comment]
Yeah, while initially envisioning this- I imagined it working just like the mute persistence setting- so the user could set their status as desired.

My thinking was if a user is concerned enough to appear invisible on every launch they would either already be using the command line argument for it, or could set the setting to their default state.

If we want to add logic on top of that to remember the invisible status regardless of their setting/preference, that could be useful to prevent that scenario of a user restarting and accidentally leaking their online state.

Regardless of whether or not we automatically reset the invisible status, the user would still have the option to manually switch their status back online as needed. So to that end- I think it'd probably make the most sense to have a grace period of 8-12 hours where invisible status is remembered, and if they want to be invisible on every launch even if it's >8-12 hours since their last session, they could set it as their default status explicitly, or use the command line argument.

**Comment by Zyzyl** [comment]
To be honest, I think the current behavior (i.e. default to Online except for remembering Invisible status) is actually a pretty good balance; I'm not convinced that adding additional complexity around this is the best approach.

My sense is that, in the past, many users didn't really use the activity status all that much outside of setting it to Invisible. Perhaps just bringing a bit more attention to it (maybe asking Mentors to bring it up with new users?) would result in it people being more intentional about how they use it. I don't think it's unreasonable that setting one's social status be an intentional choice made every time people log in (outside of remembering Invisible - that should stay).

**Comment by shiftyscales** [comment]
> I think the current behavior (i.e. default to Online except for remembering Invisible status)

That isn't the current behaviour, @Zyzyl.

The current behaviour is to remember your last status. You probably just tend to leave yourself on "Online" most of the time.

> it should not be necessary to use command line arguments

Agreed- which is why I proposed a setting- to which the user could default their status to invisible as desired.

> needlessly complex

That was why my initial proposal was just to let the user set their preferred state- but Frooxius did raise a good point about the invisible status in particular persisting across restarts- so whether or not we opt to have it expire- invisible should at the least be remembered in the short term- if not indefinitely regardless of what the user has their setting set to.

**Comment by Zyzyl** [comment]
My mistake, thanks for the correction @shiftyscales! 

Having thought about this a bit more, I've come around to your main suggestion that users be able to set either 'last status' or any one of the available options as their default status on login. It would make sense for the default to be 'last status' to maintain the current behavior for users who don't want anything to change.

I think that would handle the Invisible case adequately. Users who currently have themselves set to Invisible would have the current behaviour persist without having to change anything. Users who wish to default to Invisible could use the new setting to ensure that. For users who currently only transiently use Invisible, nothing would change in status persistence behaviour unless they make a conscious choice with the new setting (e.g. choosing to default to Online).

**Comment by Frooxius** [comment]
I'm not fully sure how to actually proceed here. It seems some users would want this to be configured individually for each type of setting (e.g. whether to remember Busy or not), but that adds extra clutter to the settings.

I think Invisible at very least should be its separate thing - this one is sensitive, because user might want to get on Resonite, but not worry about appearing Online to users, even if for a brief moment.

I don't think same worry exists with Busy - people know you're online anyways and if your status got reset to Online and you get some notifications, that's usually not such a big deal - you just flip it back to Busy and worst thing that happens is that you were annoyed by a notification or two.

With invisible, if it got reset to Online - the damage is already done - people have seen you pop online, while you wanted to remain "stealthy".

We could have following settings:
- Default Online Status (when not remembered)
- Remember Normal Status
- Remember Invisible Status

For each of the remember settings you can pick following:
- Always (will always remember)
- For x amount of time (user can specify for how long it will be remembered)
- Never (it will never remember and always use the default online status)

Would this work?

**Comment by Frooxius** [comment]
Added this in 2024.6.5.198, thanks!
