### ISSUE TITLE
In-Depth Avatar Culling

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#2278]
### Is your feature request related to a problem? Please describe.

Currently and probably for a very long time to come avatars will be a very large source of lag just because of UGC being UGC, so it would be nice to have some more meaningful culling options than the current user-created ones that simply hide the slot of the avatar so that resources can be saved on by not loading avatars entirely when they are culled.

As well as wanting to use less resources with more people most of the user-made culling systems fundamentally break things specific users may be doing if they happen to interact with components in their head proxy or similar so not having to use those would be nice.

### Describe the solution you'd like

Some official way to hide avatars and not actually load them into memory until some condition is met (usually distance/player cap) based for other platforms) that actually doesn't load the users avatar until then and can un-load it as well if they go out of range.

### Describe alternatives you've considered

Using the existing culling systems

### Additional Context

This may be a duplicate of #428, but I noticed it was slightly more than just avatar culling which might have made it get passed over, so I wanted to break that part off for consideration under the performance updates

### Requesters

Venport, GrayBoltWolf (technically), probably anyone else who ever used the user made culling systems

**Comment by shiftyscales** [comment]
> not actually load them into memory until some condition is met

This is in of itself a substantially larger request, as currently Resonite has no means of dynamically streaming assets into and out of memory, @Dusty-Sprinkles.

Likewise- it's not as simple as just not loading the avatar at all- because that avatar and its contents could be making adjustments to the datamodel/world around it, even if you are not directly in its proximity.

There are also other types of optimizations that could be considered, e.g. occlusion culling- which Resonite also currently has no native way of doing- this would ensure that mesh renderers that are occluded aren't being drawn. Currently Resonite only has frustum culling- meaning only objects that are not in the direction of the camera are not rendered.

Rate limiting for components would also help in that regard, e.g. users that are far away do not necessarily need their IK / other values updated at full fidelity/framerate.

Based on the solution you requested- it sounds like what you are asking for with this issue is asset streaming- as that seemed to be the primary focus of your request.

**Comment by gameboycjp** [comment]
A method for dynamic asset loading/asset streaming is something I'd also like to have. Could there be a general issue opened for it?

**Comment by shiftyscales** [comment]
Is there anything else you feel distinguishes this issue as unique / separate from the prior issue / are there any aspects of your request you feel are not met by #428 or #2737, @Dusty-Sprinkles?

**Comment by Dusty-Sprinkles** [comment]
> [@gameboycjp](https://github.com/gameboycjp) [@Readun](https://github.com/Readun) - A substantial improvement in that area will come in the form of cascading asset dependencies [#2737](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2737) which will help in that regard.
> 
> E.g. if a user has additional meshes / textures / or hidden objects (e.g. HUDs that are only visible to them) that system will ensure that assets are only loaded as-needed for relevant users that need to see them.
> 
> It will also implicitly benefit the use-case of existing user-made avatar culling systems by the same mechanism.
> 
> It would be best to keep this issue focused on the requested feature of avatar culling.
> 
> There are also some relevant comments from [#2737](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2737) which are relevant to some of the inquiries of this thread:
> 
> > Will there also be options to unload (clear from RAM) assets after they're not in use for a while (or even immediately)? For big worlds, especially with linear progression game worlds where the player cannot travel backwards, unloading past areas would allow for much bigger environments without overly high RAM usage. I'm guessing garbage collection would already kinda do that but that only happens rarely and when it does it often lags the game a fair bit.
> 
> Was asked to which Frooxius responded:
> 
> > Not explicitly for this. Assets are unloaded automatically when nothing no longer uses them.
> > If you deactivate stuff that uses them, the system will be able to unload them at that point.
> 
> Since most of the underlying concern for this issue seems focused around avatar culling itself, I believe it would best to close and merge this into the previous issue [#428](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/428) [@Dusty-Sprinkles](https://github.com/Dusty-Sprinkles).

Thats probably fine, I'll let you close it
