### ISSUE TITLE
Make 3D model importing require builder permission or more

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2323]
### Is your feature request related to a problem? Please describe.

When hosting public hangouts, some users will join and start importing models despite being told not to.

While importing memes, videos, spawning items and such is desirable in such contexts, importing avatars and objects to work on/setup isn't.

### Describe the solution you'd like

Importing a 3D model should be a builder-only action, as doing so can be quite disrupting to sessions, and in lots of cases, will require access to tools such as the avatar creator and developer tool that are not available at lower permission levels.

### Describe alternatives you've considered

Putting everybody in spectator, but that solution is even less flexible as people can't interact with anything.

### Additional Context

In those sessions, users are all set to the Guest permission, making them unable to use developer tools and such to avoid people working on stuff while still being able to interact, spawn objects and pictures.

### Requesters

U-j4 | j4.lc (Discord)

**Comment by PointerOffset** [comment]
I think this request might be better worded as "Require Builder by default to import assets" since it'd be difficult to differentiate the behavior and intent for this.

It might make sense that importing a model isn't something one might do in a more social session compared to importing an image. However, I've been in plenty of sessions where sharing a model one is working on or a 3D print is part of the social discussion. So model importing isn't automatically an act of work/building that's distinctly different from sharing a photo or video. Likewise, importing a photo vs importing a texture are the same thing. It's the same behavior with different intent.

I'm going to guess "Hard Permissions" (https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1103) will be needed if you want to restrict something as specific as importing 3D models.

**Comment by shiftyscales** [comment]
If you do not want users spawning objects you need to configure your `WorldPermissions` accordingly.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/901855a6-ca7c-4898-9810-205ca761b890)

> Putting everybody in spectator, but that solution is even less flexible as people can't interact with anything.

You can edit your `TouchablePermissions` to allow spectators to interact with things- e.g. either selectively tagged things, or things in general.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/2a747df0-46f8-4118-b6e7-78f334cd807a)

**Comment by jae1911** [comment]
> If you do not want users spawning objects 

@shiftyscales 
I DO want users to be able to spawn items, as spawning memes and some items are within the scope of a hangout session, as outlined in my original issue text:

> While importing memes, videos, spawning items and such is desirable in such contexts[...]

My issue is specifically with the 3D model import, that is pointless in most cases when users don't even have the permissions to use development tools and such to start with.

As far as I know, there are no permissions nor setting currently available to restrict that particular type of import.

**Comment by shiftyscales** [comment]
In which case- the issue would likely be covered under further expansion to the permissions system, i.e. hard permissions #1103 as pointed out above.

**Comment by Readun** [comment]
@shiftyscales 
I would not count this as "already exists" (And closed), as this should be the default in my opinion for guest roles.
This should be counted as an addition to hard permissions.

Or if possible, even implemented before, if it is fast to implement.
