### ISSUE TITLE
Option to Disable Grabber

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#2331]
### Is your feature request related to a problem? Please describe.

I have created a flight system that uses the grip button as one of the buttons in the combination to activate it. During flight if I crash into or touch any character collider that is grabbable I will be instantly stopped and will have to let go of the surface before i can continue flying.

### Describe the solution you'd like

I would like to have a way of disabling the grabber of a hand temporarily while my character is in flight

### Describe alternatives you've considered

I currently have a setup that throws my GrabArea Anchor out into the void so that it has basically a 0% chance of hitting any grabbable surface, but this also has the downside of if you accidentally grab a character collider surface just before activating my flight it will actually also throw myself into the void with my GrabArea Anchor

### Requesters

ultrawidegamer

**Comment by Electronus** [comment]
I don't suppose just disabling the grab area anchor works?

**Comment by ultrawidegamer** [comment]
@Electronus Yup, ive tried disabling the grabber, scaling it to 0, and also using the release all grabbed node

**Comment by shiftyscales** [comment]
> During flight if I crash into or touch any character collider that is grabbable I will be instantly stopped and will have to let go of the surface before i can continue flying.

My recommendation would be that you make use of a custom locomotion that is tailored to your needs, @ultrawidegamer.

In specific- I'd recommend setting "Gripping" on the locomotion module to `Disabled` or `GrippableObjects` (only explicitly tagged grippable surfaces, and also unchecking `GripOnHold` so that you won't grip a collider just by running into it- but would have to be already in range of it at the time you press grip.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/22daa58f-dd13-4740-abe1-dd4ebbdf2dc8)

---

For additional redundancy- it's also already possible to disable physical and remote grabbing outright through the context menu.

Setting the grabbing mode to lasers only, and disabling your lasers will mean that you are entirely unable to grab anything until either of those are re-enabled, @ultrawidegamer.
