### ISSUE TITLE
Change custom Session ID to use username instead of userID

### ISSUE THREAD

**Issue by sveken** [Yellow-Dog-Man/Resonite-Issues#2334]
### Is your feature request related to a problem? Please describe.

Currently custom session IDs for headless are userID:custom name. 
This is nice and readable with the old style usernames however now we have Snowflake IDs it makes this information hard to read for setup/flux and server side administrator point of view. 

### Describe the solution you'd like

If possible, change it to username instead of userID. This would make the session ID alot easier to read and use. 

### Describe alternatives you've considered

N/A

**Comment by Frooxius** [comment]
We can't make this change unfortunately for a few reasons:
- Usernames can include characters that are not valid characters for ID's
- Usernames are mutable. This creates a bunch of problems for systems, because they assume that this will be immutable. 

Generally the goal for custom SessionID's (and most ID's in general) isn't to be human readable - you should copy them verbatim and they shouldn't be displayed to users.

If there are some underlying issues around this, feel free to make issues about those and we can look into what could be done, but for this specific change, unfortunately it's not something we can do on technical level.
