### ISSUE TITLE
Dynamic bones colliding with user FBT unexpectedly

### ISSUE THREAD

**Issue by rawpie2** [Yellow-Dog-Man/Resonite-Issues#2355]
### Describe the bug?

When using 3 Point full body tracking (Left Foot, Right Foot, Hips) and getting close to a user, the dynamic bones of the user will twitch rapidly and also move around depending on how I move my feet and head. I believe this might be because there is are invisible lines from the head to the tracker and the dynamic bones seem to collide with this invisible line that cannot be changed or fixed or viewed in game at all. This happens even if the user disables their avatar completely.

### To Reproduce

Equip FBT in real life, and lie down next to someone with dynamic bones such as check or hair, and move your foot near and around them, then move your head. Ensure you have no colliders on your avatar in any capacity to see this still happen.

### Expected behavior

Dynamic bones don't collide with invisible full body calculation.

### Screenshots

Screenshots not applicable. videos instead:

https://drive.google.com/file/d/1dC4Hh4211TboRqZbq9kG0DDDeh3tshed/view?usp=sharing
https://drive.google.com/file/d/1VPfQY-0Ne6Ew-ZdYh_ohS9ZXeHlzIUkS/view?usp=sharing

### Resonite Version Number

Beta 2024.6.11.74

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Valve Index

### Log Files

[DESKTOP - 2024.6.11.74 - 2024-06-17 21_22_53.log](https://github.com/user-attachments/files/15879022/DESKTOP.-.2024.6.11.74.-.2024-06-17.21_22_53.log)

### Additional Context

Only works if in Full Body, for pose mode users nothing happens.

### Reporters

rawpie

**Comment by ohzee00** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1567 Do you think this is the issue? This sound very familiar

**Comment by rawpie2** [comment]
> #1567 Do you think this is the issue? This sounds very familiar

I don't believe so, as this doesn't give enough info. Also this is a major FBT issue, that one classifies it as a "small" issue.
Quite literally makes getting close to anyone or anything with dynamic bones impossible and makes any social situation awkward if its a person with many dynamic bones when laying down. Which most of my friends with FBT lay down as well.

**Comment by art0007i** [comment]
I'm pretty sure it's the same issue. you can visualize what is happening by making a DynamicBoneChain with "VisualizeColliders" enabled and then walk close to that bone chain. you will see some spheres that cover the path from your head to the midpoint of your feet, which is similar to what you described in the original issue, and is also described in #1567 

here's a picture of how this works exactly (green spheres are dynbone colliders)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/a4b03aa7-99e1-4d1f-bc1f-60101204eb69)

**Comment by shiftyscales** [comment]
It would help if you had debug visuals enabled on the dynamic bone chain so we could see what colliders were being interacted with- but I'm pretty certain this is the same issue as #1567.

The body collider attempts to place itself at the midpoint between your feet- this is why if you move your feet- it would cause it to move from side to side- you are moving the dynamic bone collider as you move your feet further apart / closer together.

From what you've provided / shown above- I don't have reason to believe this is a distinct issue from the previously mentioned one. If you are certain it is- and wish to provide additional testing / video demonstrations of how this issue is different, please feel free to- otherwise, for now I'll be closing this issue as a duplicate.

Thank you for your report, and understanding.
