### ISSUE TITLE
AvatarRenderSetting set to NearClip = 0 causes black image with finger or desktop photos

### ISSUE THREAD

**Issue by Nordwig** [Yellow-Dog-Man/Resonite-Issues#2358]
### Describe the bug?

When you have a AvatarRenderSetting component where the NearClip is selected and the value is set to 0 (default) then the "finger photo" gesture will render pictures completly black. Same in desktop mode (Shift + P, Ctrl + P)

### To Reproduce

1. Set up an avatar
2. add a "AvatarRenderSetting" component
3. toggle on the NearClip setting
4. leave the value of NearClip at 0
5. take a photo with the "finger photo" gesture
6. the photo will pop up instantly and is completly black

### Expected behavior

Finger photo gesture and desktop photo should work normaly

### Screenshots

![2024-06-18 16 11 35](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44645982/67cf89f1-4398-4555-b8a8-60e59af5a446)

### Resonite Version Number

Beta 2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[DESKTOP-HU8JOJP - 2024.6.11.74 - 2024-06-18 18_09_13.log](https://github.com/user-attachments/files/15890301/DESKTOP-HU8JOJP.-.2024.6.11.74.-.2024-06-18.18_09_13.log)

### Additional Context

in the Log only tested in VR

### Reporters

ErrorJan, Nordwick

**Comment by shiftyscales** [comment]
It is not advisable to set near clip to zero @Nordwig. Having both too small of a near clip, or too far of a far clip value can cause graphical issues as the floating point precision is spread over too wide a range.

From personal experience I have not ever needed a nearclip value of lower than around 0.05- but even setting it to 0.01 would be a drastic improvement compared to setting it to zero (although I'd recommend  at least 0.1 if you are going to override it at all as opposed to using the default render settings).

If you do need a nearclip as low as you're suggesting- you will need to lower your far clipping value to accomodate so the rendering engine has sufficient floating point precision to not cause such graphical issues.

This isn't really something that can be fixed- you just need to use render settings that only cover the range you need them to.

**Comment by Banane9** [comment]
I'm not sure why you closed this immediately, @shiftyscales - the fingerphoto's rendering should not be affected by the near- or farclip settings for the avatar like this, especially when the same setting works perfectly fine for the user themselves. As such, this is a perfectly valid bug in my eyes.

Looking through things, the near- and farclip for the "user" camera is capped to minimum values:
* Nearclip to `0.001` in `UnityFrooxEngineRunner.HeadOutput.UpdatePositioning()`
* Farclip to `0.5` in the same method

In the `PhotoCaptureManager.OnCommonUpdate()` method however, the local user's render settings are used without such checks, defaulting to `0.005` and `4096` for near- and farclip respectively when a value isn't present.

The fix for this bug would thus obviously be to include the same sanity checking on the fingerphoto system's setting of the camera's settings, as on the "user" camera itself. `InteractiveCamera.OnCommonUpdate()` seems to suffer from the same issue, where the override near- and farclip are used without sanity checking when in Smooth First Person mode. In other modes, it does seem to enforce a lower bound on the near clip, though using `0.00001`, or 1/100th of the "user" camera's minimum.

**Comment by Nordwig** [comment]
Hello @shiftyscales im sorry i should have descriped the problem better.
A user told me that with one of his avatars the photos of his "finger gesture" camera are not working and only show black.
All his other Avatars where working fine. We found a "AvatarRenderSetting" where the NearClip was checked but the value was 0 (witch is the default sadly).

Three other Useres in the session told thye had this "Black Finger Photo" - Problem in the past and never found the reason for this. Thats why i made this issue.
 
Having the NearClip set to 0 or a very small number dosent make sense. But its a relativ easy to make mistake that breaks a seamingly unrelatet system. 
I will update the Issue so that it better discripes the problem.
