### ISSUE TITLE
Dynamic Impulses should create nested Protoflux context

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#2412]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when having a recursive dynamic impulse that deals with temporary output values of nodes since the output values get overwritten in each level of recursion meaning that once the outer ``Dynamic Impulse Trigger`` fires its ``OnTriggered`` impulse, all the temporary output values up until that point have been replaced by the recursion it just triggered.

### Describe the solution you'd like

``DynamicImpulseTrigger`` and ``DynamicImpulseTrigger<T>``, als well as the async ones, should create a nested Protoflux context before triggering their receivers and get rid of this context after the receivers are done.

### Describe alternatives you've considered

1. Not doing this. (I don't see why)
2. Manually creating these 'contexts' in the form of duplicated dynamic variable spaces. (or similar)
3. Preventing dynamic impulse recursion by disabling the nodes when an impulse hits the same trigger twice. (awful, why?)

### Additional Context

I had to work around this while building an XML parser in the past.
XML consists largely of nested elements that I parsed with a parseElement dynamic impulse.
So I ran into this when the parsing for nested elements started messing up some node outputs that the parsing for outer elements still relied on afterwards.

Today I am with someone else who is recursively iterating down a slot hierarchy which is causing similar problems.

### Requesters

1. Resonite: Psychpsyo, Discord: cameron5
2. Resonite: Baxter, Discord: BaxterOttoman

**Comment by mpmxyz** [comment]
I personally agree it is a bit inconsistent. If you change the ProtoFlux group with the dynamic impulse you get your requested behavior:
![single group](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/deb9218f-46b9-4904-a0f9-1a5d307672b8)
![two groups](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/e7e27701-1ea0-4cae-8d24-3fc1384923b0)


But at the same time I'd be very cautious about changing it because it risks breaking a lot of stuff.
For example I use the current behavior to create subroutines with arguments and return values because we don't have that kind of stuff built-in, yet. Even worse: My logging tool relies on this to read local values.
So without a proper replacement - like functions - I'm against this change unless it is opt-in via a separate trigger or receiver option.

**Comment by Nytra** [comment]
You can use StartAsyncTask to manually fork a context

**Comment by mpmxyz** [comment]
Hmm... I never noticed that OnStarted executes after TaskStart. That's good for sync impulses.
Unfortunately we can't await async chains like that.
Should an issue be opened to request that, instead?
("Await Async Task": * -> TaskStart, OnStarted, OnFinished, OnFailed)

**Comment by Psychpsyo** [comment]
> Even worse: My logging tool relies on this to read local values. So without a proper replacement - like functions - I'm against this change unless it is opt-in via a separate trigger or receiver option.

Local values as in the ones from the variables section or as in the temporary outputs of nodes such as ``Duplicate Slot``?
Because, yes, nesting local values for this sort of recursion seems like a very bad thing.

But I feel like the temporary node output values should nest instead of being overwritten and become invalid / un-nest when the physical wire coming out of the node stops. (at the point where the pulse execution jumps back to the original Dynamic Impulse Trigger)

**Comment by LeCloutPanda** [comment]
This could be related to an issue I was having with flux, I had the flux setup below and from my knowledge Local variables written values should only be what it was written as in that context rather then outside of the context but I may be mistaken as this is my first time using Local variables.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/53411604/5e803309-d577-4ade-bcd6-be2962164497)

I have this issue where if I use the flux set up below and that Local variable gets written to again it decides to have a fit and create the second image rather then the first on

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/53411604/0031001a-46f4-4ef2-ae58-309ff1074a07)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/53411604/b4302a92-c0c6-4a51-bab1-e9f4be3e5e40)

I believe if we had nested context using a Local varible could be a bit more consistent but I could also just be completely wrong so I don't know.

**Comment by Frooxius** [comment]
We will not be making this change due to a number of reasons (ordered from most significant to least):

- This goes against design of dynamic impulses - they are a dynamic binding indirection mechanism, not a recursion mechanism like you want them to use as. ProtoFlux already has a recursion mechanism as part of its design that would allow this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/564
- Doing this would break huge amounts of user content (I know this for a fact, because it was discovered during development of ProtoFlux)
- It would make it completely impossible to use certain programming patterns that this is currently utilized for (this is related to the breakage of user content)

I suggest up-voting the Nested Node issue and potentially adding your use case there. They are designed specifically for handling recursion.
