### ISSUE TITLE
Consider revision or split of bug report form

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#2422]
### Describe the Underlying Issue

Personally, I find there are some required fields on the bug report form to not necessarily be relevant to all reported issues.  This especially applies to the version and log fields.

For the former, it is really hard for me as a user to specifically promise a version, and typically I will just boot up Resonite (if it's not already open) and use the current version.  I cannot see any value in specifying an older version, as I'm not going to report an issue that's been fixed, and it's very unlikely I'll be able to pinpoint exactly when the issue I'm posting abut started happening.  Even if I could pinpoint exactly when the issue started, unless I happen to make a note about that version, Resonite will have often updated before I actually end up reporting the issue, and there's no way for me to recover the exact older version number when I personally started observing the issue in question

For the latter, I sincerely doubt Resonite is capturing every little interaction in logs, and if it is then it shouldn't, as that has performance and storage implications.  Not every bug is a crash, and in fact most of the bugs I report are usually behavioral nuances that are not captured in logs, and I'd rather leave the field blank than have to put an n/a and feel like I'm fighting the team.

### Expected Behavior

Concise and useful fields on report form, reduce dependence on required fields where not needed, create separate forms if there are cases that it does matter (ex behavior bugs and crashes are not the same, and may have different reporting needs)

### Reporters

zangooseoo

**Comment by Frooxius** [comment]
Not including the version number makes it much more difficult for us to diagnose the issues - we need to match the bug and information to specific version of source code. And sometimes people report bugs that were already fixed - and if they claim it's on the "latest build", then we get sent down a rabbit hole - sometimes for hours.

While the logs do not capture every interaction, they do capture a good amount and they provide important context and additional information that we need to diagnose. 

Do we need them for every issue? No. But how are users able to determine if log is needed or not? There was also a number of issues which were missing logs. This gets very frustrating from our end, because we look at the thing, we decide "I'm going to work on this". I read through it. Then I'm like "Oh, I need to check the log". And find there's none... So I need to ask and now wait and move to something else and be annoyed that I wasted time with it (because next time I'll need to re-read the issue again).

We can read dozens of issues a day. If this happens a lot more, it adds up. And wastes a lot of our time - time that we could spend fixing more bugs or implementing features. 

Engineering time is very precious. If you want us to potentially spend hours or days (and sometimes more) of our time on your issue, spending a few more minutes on providing relevant information is the least we could ask in my opinion.

Ideally the more time you spend on the issue, the less we will have to - and the more issues overall we can tackle and get resolved - e.g. by isolating the issue, you help us a lot and we're a lot more likely to pick those issues up over ones that are too vague and missing a lot of info.

Imagine it from opposite perspective too - would you be happy if your issue got dropped and not get addressed, because we wasted time on someone else's issue due to missing information? This is essentially what it comes down to.

Because of this, we will not make this change, I am sorry, however I  hope this helps understand why.
