### ISSUE TITLE
Framerate affects scrollwheel speed when laser sliding

### ISSUE THREAD

**Issue by BlueCyro** [Yellow-Dog-Man/Resonite-Issues#2451]
### Describe the bug?

When in desktop mode, turning off VSync will reveal that as the framerate goes higher, the scrollwheel speed decreases. This is especially problematic when working in a world by yourself without VSync, as trying to move items further or closer to you takes quite a while if you don't have a free-spinning scrollwheel.

### To Reproduce

1) Go to an optimized world (gridspace will do)
2) Spawn an object
3) Note the scrollwheel speed
4) Turn off VSync
5) Note the difference in scroll wheel speed if your FPS has increased dramatically

### Expected behavior

The scrollwheel speed should stay constant no matter the framerate.

### Resonite Version Number

2024.6.25.1149

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-6C2UJFB - 2024.6.25.1149 - 2024-07-01 22_24_59.log](https://github.com/user-attachments/files/16061310/DESKTOP-6C2UJFB.-.2024.6.25.1149.-.2024-07-01.22_24_59.log)

### Additional Context

This is likely due to the fact that specifically laser sliding does not account for the delta time when sliding the item back and forth along the laser direction in the input system.

### Reporters

Cyro

**Comment by epicEaston197** [comment]
I've actually noticed the opposite effect of this whenever my game freezes and I'm scrolling an item in or away from me The item will be really close or really far away from me then I have to readjust the distance 

(This is a minor annoyance)

**Comment by copygirl** [comment]
I've reproduced this as well. The distance an item is moved closer of further away by grabbing with the mouse in desktop mode depends on the framerate, rather than being a constant distant for each "notch" the scroll wheel is moved. Can be seen easily by moving the scroll wheel back and forth and noticing the grabbed item moving inconsistent amounts when framerate is not absolutely stable.

Sounds like there could be a `* deltaTime` or similar too much in the code somewhere.

**Comment by Frooxius** [comment]
I've merged the fix in 2024.11.12.1329, thanks!
