### ISSUE TITLE
Radiant Dash Reinitializes Every Single Time When Launching Game, Causes Cloud Storage Pileup

### ISSUE THREAD

**Issue by yoshiyoshyosh** [Yellow-Dog-Man/Resonite-Issues#2468]
### Describe the bug?

When launching the game, I've been noticing that my cloud storage increases by ~300KB every single time. Even if I don't do anything, send any messages, get sent and messages, save items, whatever, it still happens. This is, of course, annoying, because it represents a slow time bomb to my storage being full.

In order to get to the bottom of what could possibly be taking up this space, I requested a usage report. I found *hundreds* of `TopBar` and `Screens` objects filling the usage report, each one increasing ever so slightly--tens of KB--as it went on. I requested another usage report between a few relaunches, and `diff`'d what could possibly be different about the two. Sure enough, [the only different items were the `TopBar` and `Screens` objects](https://gist.github.com/yoshiyoshyosh/e3638b384aa80fc6df36de65b7a8a19f) (also, every record had its record ID shuffled? even inventory objects? is that normal? could that be the underlying reason? you'll see why I'm asking this question later)

Looking at my logs, I suspiciously noticed some lines saying
```
20:00:55.390 ( 62 FPS)	Loading target workspace Private/RadiantDash/Screens for U-yosh
20:00:55.390 ( 62 FPS)	Loading workspace Private/RadiantDash/Screens from: resrec:///U-yosh/Workspaces/Private/RadiantDash/Screens for U-yosh
20:00:55.390 ( 62 FPS)	Loading target workspace Private/RadiantDash/TopBar for U-yosh
20:00:55.390 ( 62 FPS)	Loading workspace Private/RadiantDash/TopBar from: resrec:///U-yosh/Workspaces/Private/RadiantDash/TopBar for U-yosh
...
20:00:56.241 ( 45 FPS)	Workspace Private/FacetAnchors/RightForearmBottom/Default initialized to default
20:00:56.321 ( 45 FPS)	Workspace Private/RadiantDash/Screens initialized to default
20:00:56.376 ( 45 FPS)	Workspace Private/FacetAnchors/LeftHandBottom/Default initialized to default
20:00:56.377 ( 45 FPS)	Workspace Private/RadiantDash/TopBar initialized to default
20:00:56.378 ( 45 FPS)	Workspace Private/FacetAnchors/ViewBottom/Default initialized to default
20:00:56.379 ( 45 FPS)	Workspace Private/FacetAnchors/LeftForearmBottom/Default initialized to default
20:00:56.380 ( 45 FPS)	Workspace Private/FacetAnchors/ViewFront/Default initialized to default
```

Searching for the log lines in the code, I was led to the `LoadTargetWorkspace()` function in `FrooxEngine.Workspace` (culled a bit for brevity's sake):
```cs
Uri workspaceRecordUri = GetWorkspaceRecordUri(workspace, userId);
if (workspaceRecordUri != null) {
	UniLog.Log($"Loading workspace {workspace} from: {workspaceRecordUri} for {userId}");
	record = (await base.Engine.RecordManager.FetchRecord(workspaceRecordUri))?.Entity;
	if (!LocalForceReinitialize && Uri.TryCreate(record?.AssetURI, UriKind.Absolute, out var assetUri)) {
		string text = await base.Engine.AssetManager.GatherAssetFile(assetUri, 100f);
		UniLog.Log("Loading workspace asset file: " + text);
		if (File.Exists(text)) {
			try {
				data = DataTreeConverter.Load(text, assetUri);
			}
			...
		}
	}
}
await default(ToWorld);
if (data != null) {
	...
	UniLog.Log("Loaded workspace " + workspace + " for " + userId);
	...
}
else if (_currentDefault == null || !(_currentDefault == InitializeWorkspace.Target)) {
	...
	UniLog.Log("Workspace " + workspace + " initialized to default");
	...
}
```

It appears that the `if (!LocalForceReinitialize && Uri.TryCreate(record?.AssetURI, UriKind.Absolute, out var assetUri))` isn't evaluating to true, given how that `Loading workspace asset file:` log message isn't showing. `LocalForceReinitialize` is only set to `True` when `-ResetDash` is given as a launch param, which, well, I'm not doing, given how I'm not getting a `Resetting Dash!` log line. As such, the only conceivable notion is that `Uri.TryCreate()` is failing for some reason. Why? I don't know.

### To Reproduce

- Launch game
- Look at cloud storage
- Close Game
- Launch game again
- Notice cloud storage is being used more

Annoyingly, though, I haven't been found anyone having the same problem, and thus I'm not sure if this will be reproduced by anyone. Is it a linux only bug? Not sure. Will see if anyone there can reproduce it.

### Expected behavior

The game is able to recognize my existing `RadiantDash` and `TopBar` assets, not allowing 

Additionally, if the game culled every workspace that *isn't* the current one whenever initializing the workspace to default, this would function both as a workaround to this issue *and* not also be an issue for someone who `-ResetDash`, not knowing where a random extra 300KB of stuff came from.

### Screenshots

Notice how the `Syncing 3 items` appears every time.

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/36683489/b1cae756-f50f-4cf6-840b-ea9ae301557f

### Resonite Version Number

2024.6.25.1149

### What Platforms does this occur on?

Linux

### Log Files

these are two log files taken from the launches in the above video

https://gist.github.com/yoshiyoshyosh/c48b29feff02b3a14f2edda0bb77788c
https://gist.github.com/yoshiyoshyosh/0d20398e3d01b03db4462ff4119358d8

### Reporters

yosh

**Comment by stiefeljackal** [comment]
Based on what I saw in the logs and the usage report, I believe the engine is failing to fetch the record for "Top Bar" and "Screens" as I am seeing multiple records for them. This would explain why the space continuously grows and why the "Top Bar" and "Screens" records keep syncing back (the third record is always `R-SettingsData`). Looking at the decompiled code snippit, I assume `record` is null due to the fetching failure. If possible, see if you can monitor your network traffic (mitmproxy or similar) to capture the HTTP request and response for those records.

On another note, `-ResetDash` does not create a new record; it utilizes the same record id used for the "Top Bar" and "Screens" records. The difference is that it does not load the corresponding `brson` file and allows the default "Top Bar" and "Screens" to load. The engine marks those as modified afterwards, which causes those records to be forcefully resynced back with entirely different `brson` files.

**Comment by coolymike** [comment]
This could have a similar cause as the issue I commented about in https://github.com/yellow-dog-man/brotli.net/issues/3#issuecomment-2188664090. Essentially, the Dash does not save on the Linux Native version. If the Dash is modified and saved on the Windows version (either on Windows, or under Proton), the modified Dash loads fine on the Linux native version. If the Dash is saved on the Linux native version, it resets on restart . The logs I get appear very similar to those in the post here.

Note that in order to get anything to sync at all, I'm running a patched Brotli.NET.

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius.

**Comment by ProbablePrime** [comment]
Im taking this one over, I've given the Workspace component an overhaul for some business features and need to take a look to see if this still occurs after my changes are done.

**Comment by ProbablePrime** [comment]
Moved to paused on my work list as I'm waiting for the logging to make it to a build so we can help diagnose.

**Comment by yoshiyoshyosh** [comment]
I haven't been noticing this bug on the proton build. since this is seemingly a linux native only issue, will the linux native build stick around for this?

**Comment by ProbablePrime** [comment]
With the recent update, we do have more logging in the area that may help resolve this, but yes the Native Build isn't sticking around. As this is Linux only I'll uh close it for now I guess.

**Comment by coolymike** [comment]
[The SteamDB page](https://steamdb.info/depot/2519833/history/) indicates that the Linux build for `2024.9.4.357` was created and released. This means we should now have the logging to be able to troubleshoot this better. (Sadly, I don't have the time to provide logging at this moment.)
Since this issue is in FrooxEngine, not Unity and likely not mono either, it will stick around for after the Linux build is re-introduced with .NET 8 and Sauce. That would also include potential future Android builds.

I'm not sure closing as "not planned" is the correct option for this issue. With the Linux native build being deprecated (for now), a ton of Linux-exclusive issues like these are in a sort of limbo state. Maybe use the "Linux" label, move the issue off any backlogs, then re-open it? Closing the issues to me feels like they're all going to be lost permanently, and won't be picked up when the Linux build is re-introduced.

**Comment by ProbablePrime** [comment]
When we re-introduce the Linux build we'll do a full round of testing internally and externally with pre-release etc. 

At that point the engine is going to be completely different and I'm confident that this issue in its specific incarnation would not occur.

**Comment by coolymike** [comment]
> When we re-introduce the Linux build we'll do a full round of testing internally and externally with pre-release etc.

Considering this issue was created long after the games release, but seemingly in a bit of code that hasn't changed much since then, it is fairly difficult to find and troubleshoot. A "full round of testing internally" is unlikely to catch issues like these.

**Comment by yoshiyoshyosh** [comment]
While I understand the bug being closed, the fact remains that I have... quite a few (hundreds, maybe even >1000) components/slots/whatever on my dash that I can't get rid of with a -ResetDash. is there any easy way for me to remove all these dead ones on desktop that *doesn't* require manually record deleting with the bot?

also, these dead components still appear when doing a -ResetDash, so I should probably make a new github issue for that...

**Comment by shiftyscales** [comment]
@yoshiyoshyosh - that'd probably be covered by #594. Prime's comment there:

> I forgot to update this now that we've had an update.
> 
> There were some large scale changes to how the dash works in that update. They won't have specifically fixed this issue but there's another one it might have that I keep forgetting the number of.
> 
> However, I did get close here. I have a branch where we won't create any additional components. What's left is writing a one-time upgrade process to remove the older ones and I hit some technical snags there because of our versioning system. I do have a solve and hope to get back to this soon.

https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/594#issuecomment-2330783015
