### ISSUE TITLE
Per Device Setting: Ignore Tracker Position (Use Rotation Only)

### ISSUE THREAD

**Issue by MahSandwich** [Yellow-Dog-Man/Resonite-Issues#2519]
### Is your feature request related to a problem? Please describe.

Tracking causing the avatar to fly off in a random direction.

### Describe the solution you'd like

From using Slime VR with a cell phone for tracking which only provided rotation data it never seemed to have that issue and generally worked great as long as the phone had a good network connection and a good gyroscope.
So I feel that if tracking can be done without using the position (which is generally still required for the headset and probably the hands) it may help with the current tracking issues if specific devices can be individually configured to optionally not use position data.

### Describe alternatives you've considered

Could go back to using SlimeVR with a Cell phone but it's not an ideal setup.

### Requesters

Hikari Akimori (hikari_akimori)

**Comment by art0007i** [comment]
the thing is SlimeVR implements a whole Forwards Kinematics system which requires knowing your exact body proportions so it would be a lot of effort for resonite to support this. I think the slimeVR software supports using normal steamvr trackers in their system somehow but I haven't looked into this

**Comment by Frooxius** [comment]
Yeah I don't quite see how well we'd be able to support this. The rotation itself isn't enough information, because we need to figure out where to actually put the limb - I'd say that in some cases it's even more important than the rotation!

We'd have to implement some kind of IK system for the tracking estimation, which can be a significant burden on our end to make it work well.
