### ISSUE TITLE
[Tweak] Apply DataModelAssemblyAttribute to plugins automatically

### ISSUE THREAD

**Issue by BlueCyro** [Yellow-Dog-Man/Resonite-Issues#2535]
### Is your feature request related to a problem? Please describe.

Current plugins no longer load as they lack DataModelAssemblyAttribute. The update log notes that this attribute is to be applied by the plugin author, but both legacy and newly-added plugins are now not loaded by default when referenced by the `-LoadAssembly` flag in the startup options.

### Describe the solution you'd like

Apply the DataModelAssemblyAttribute to any valid plugins that are loaded via the `-LoadAssembly` flag

### Describe alternatives you've considered

Adding the attribute to the plugin project manually: This requires that the plugin be recompiled or further post-processed. This is simple for the plugin author, but currently all plugins will be broken until their authors update them.

### Additional Context

Given that referenced assemblies will automatically be post-processed, it makes sense that this attribute would be added to any assemblies you explicitly target via the `-LoadAssembly` launch flag as well.

### Requesters

Myself

**Comment by Frooxius** [comment]
We can't really apply this automatically - and we shouldn't, because that would defeat the point of the new system and muddle things.

This is a decision that the plugin maker needs to make.

Notably they need to decide:
- What type of data model assembly this is
- Which types should be data model types

This is a breaking change for plugins, with the expectation that authors will update them accordingly to work with the new system.

There can be other reasons to load plugins that are not data model assemblies - e.g. if they were to introduce functionality like device drivers, importers and so on, which do not need to interact with data model at all.

If we made this change, then it would make it impossible to not have an assembly be data model assembly.
