### ISSUE TITLE
SignalR High latency/Down

### ISSUE THREAD

**Issue by skywindkitsune** [Yellow-Dog-Man/Resonite-Issues#2607]
### Describe the bug?

Messages, invites are failing to send, sessions fail to show up

### To Reproduce

Login to a headless send yourself an invite, it will take a while or fail.

### Expected behavior

invite should be near immidiate

### Screenshots

![image](https://github.com/user-attachments/assets/385c821a-f9f5-4cd4-b4f2-ab3cb722db5e)

### Resonite Version Number

2024.7.17.1173

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Oculus Quest 3

### Log Files

No Logs

### Reporters

Skywind Kitsune, ExoTheWicker

**Comment by ExoTheWicker** [comment]
I'm observing ping times with the /echo command >1 minute

**Comment by bredo228** [comment]
Noticing this as well, have a headless that's constantly showing offline (despite being online) and failing to send messages.

Also seeing some sessions in my contacts list flicking in and out of existence

**Comment by Frooxius** [comment]
I think this might be resolved for now. From what I could tell the Redis cache used for user statuses was overloaded by the mechanism that cleans up user statuses when they drop unexpectedly.

I have disabled that mechanism for now, since it's not necessarily needed (just leads to some oddness when users lose connection - it makes them linger online for a bit longer, but that's not super big deal).

I'll investigate some more in the meanwhile.

**Comment by skywindkitsune** [comment]
SignalIR is still having some problems, sessions are still disappearing, my friends list just went all offline.

**Comment by Frooxius** [comment]
I'm working on it. See #devlog in Discord

**Comment by skywindkitsune** [comment]
ah xD dur i didn't see that.

**Comment by Frooxius** [comment]
I'm closing this, as it's been resolved! Thank you for report!
