### ISSUE TITLE
Let asset system to retain material names on imported models

### ISSUE THREAD

**Issue by SilvyPaws** [Yellow-Dog-Man/Resonite-Issues#2704]
### Is your feature request related to a problem? Please describe.

I find it infuriating when trying to modify materials on an avatar or model that i've saved and they're just all called....
![image](https://github.com/user-attachments/assets/25ca1522-5b46-4188-84ef-3b58c66b2e5a)
The more materials a model has, the worse this issue is.

Currently, the only "solution" to this problem is saving all of your materials onto your avatar as components and naming your gameobjects to the associated material so you'll know what each material is. However, this means it'll no longer be using the asset variant system which is bad. 

### Describe the solution you'd like

If you never create new materials and instead convert them using the material tooltip, it should retain those material names even after being saved and respawned from your inventory.

### Describe alternatives you've considered

An alternative solution would still require the Asset system to retain the names, but to allow the user to rename the materials. One method could be double clicking the material with a devtip or material tip and typing in the desired name for that material to rename them or clicking on the array number and having a context menu button to bring up your keyboard and rename that material slot.
![image](https://github.com/user-attachments/assets/05977913-72ae-4a1d-8db3-e16efdf38e54)

### Requesters

SilvyPaws

**Comment by ProbablePrime** [comment]
The problem here is that Materials don't have names.

The names you see are the name of the slot that the material is on and the type/shader that the material uses.  These are inherently unstable and likely to be altered no matter what we do. That's because of how we treat assets.

As such its difficult to resolve this without changing up the system to listen and somehow factor these names into the whole system.

It is possible, most things are. I wanted to point out the crux of the issue though, materials do not have names.

Additionally, the asset variant system and the asset system found in a world are two separate systems:
1. Asset Variant/Varience System - Calculates more optimized variants of assets, Separate from Resonite
2. Asset System - Part of Resonite, places common assets within an "assets" hierarchy within the world.

**Comment by Dusty-Sprinkles** [comment]
Would it maybe be possible to change the behaviour of the material tool to put it in the same spot when you choose the "convert" option? Not sure if that's hard/overcomplicated though.

**Comment by ProbablePrime** [comment]
Could you elaborate what you mean by "spot"

Converted materials are spawned into the world in LocalUserSpace(AKA the slot that you are parented to)

**Comment by Dusty-Sprinkles** [comment]
> The names you see are the name of the slot that the material is on and the type/shader that the material uses. These are inherently unstable and likely to be altered no matter what we do. That's because of how we treat assets.

I may have misinterpreted this? but my idea was if you could put the converted materials into the slot that the material you're converting is in

**Comment by ProbablePrime** [comment]
Oh that wouldn't help and is not really related to naming. New materials are created on a new slot and thus have a new name.

**Comment by Dusty-Sprinkles** [comment]
Hmm yeah but what if they were created in the existing slot? that was sort of my idea since they should? have the same name minus being a different material type in that case right?

Not sure if theres any reason that getting the current slot of the material being converted would be hard.

**Comment by Electronus** [comment]
> The problem here is that Materials don't have names.

So how crazy is it to give them names? I don't know how much work that would be, but seems like it would be a cool thing to have and make working with things much easier.

**Comment by ProbablePrime** [comment]
> Hmm yeah but what if they were created in the existing slot? that was sort of my idea since they should? have the same name minus being a different material type in that case right?
> 
> Not sure if theres any reason that getting the current slot of the material being converted would be hard.

That wont work. Let's say you have a slot called "Body Material - PBS" and you convert the single material on that slot(remember materials do not have names), to Xixe. That would then place two materials on that slot, one a PBS and one a Xixe. At that point the Slot name is just confusing. That's if the materials are already on the object.

Then what if you need to use either of those materials on another object? Its no longer the body material, its a table material.

If they're in the asset system, that will just put another material on the same slot within the assets system. Particularly if you reload the object in another session.

I can totally do this, it just doesn't fix the problem, in my opinion.

> So how crazy is it to give them names?
Also easy, but think it through.

We could easily put another field on the material components called "name", but that doesn't solve the problem. What you'd need there is some new UI on the mesh render to pickup this name and display it somehow, This would only apply to materials. So we'd need to edit the inspector to render materials differently.

Oh and at that point, do we show all the details? Some of the details? What interactions change? What buttons change?

It gets larger and larger.

Now look at Blender which names materials and material slots(on an object) separately.

Its all possible, its just not a "quick fix".

**Comment by Frooxius** [comment]
This issue seems to be based on misunderstanding of how the asset system works and I think we're getting too deep into possible solutions, when one already exists.

> Currently, the only "solution" to this problem is saving all of your materials onto your avatar as components and naming your gameobjects to the associated material so you'll know what each material is. However, this means it'll no longer be using the asset variant system which is bad.

This actually *is* the solution and it's the proper way how you can name materials.

It does not mean that it will no longer be using the asset variant system at all. I'm unsure where you got this information from, but it's not true, for two key reasons:
- Asset variant system doesn't care about names or where things are placed in hierarchy at all. Placing assets in one place over other in hierarchy will never prevent asset variant system from being used.
- Material assets specifically never use asset variant system at all. It's not relevant or useful to them in any way.

The way the system is structured is that Materials themselves are just that - materials. If you want them to be organized and named, then you can place them somewhere specific under the object itself. If you don't care, leave them whenever, but the organization (which includes names) will likely be lost.

Additionally there's an option during 3D model import - in advanced import settings you can check "Place Assets On Object", which will place all of them under the imported object hierarchy for you.

Given above, I don't see any changes that would actually need to be done here. Is there anything I'm missing?

**Comment by kulzae** [comment]
> This issue seems to be based on misunderstanding of how the asset system works and I think we're getting too deep into possible solutions, when one already exists.
>......................

Okay so currently when placing materials on slots you do see the slot name and that lets you identify the material
![image](https://github.com/user-attachments/assets/dfcd4c1c-ebf3-454a-90e4-5fda7ea8a3b5)

the problem is when something is saved and those materials are not manually put into slots you end up with the following
![image](https://github.com/user-attachments/assets/c2ec26f1-d1c4-4d30-a6bc-8e1436efa2e7)

and your material list becomes "pbs metallic on pbs metallic"

**Comment by Frooxius** [comment]
@kulzae I understand that, but what I'm saying is that this is intentional and it's a workflow issue.

To put it clearly:
1) Place the material on the object itself to properly name it and organize it - the system is aware of this and will never erase the name or move the material, because by doing this, you tell the system you want the material to be organized
2) Place the material outside of the object if you don't care where it is or how it's named - this tells the system you don't care about its name and it'll reorganize it for you

That's expected behavior - you told the system you don't care about the organization/naming of these materials - so it did just that - it consolidated them and lost the naming in process.

If you do care about the naming being preserved - put them under the slot of the object. This is the mechanism for solving the problem, you just need to use it.

If we made both ways preserve organization and names, then there would be removing a way to tell the system you don't care about the material and you're okay with it being moved & consolidated.

**Comment by kulzae** [comment]
Is there a specific reason why the name is erased when using the asset system? The only reason I can think of is to avoid conflict like
Object 1 uses material called red ball
Object 2 gets spawned and uses the same material but calls it red rubber
Object 2 now has a material named red ball when it was supposed to be called red rubber

**Comment by Frooxius** [comment]
Yes - reducing overhead and improving overhead.

If you don't tell the system that you want the material to stay where it is, it will try to consolidate them into as few Slots as possible, merge any duplicate materials into same one and erase everything else that's not necessary (e.g. the individual names).

**Comment by TisFoolish** [comment]
> erase everything else that's not necessary (e.g. the individual names).
Users obviously consider those names as necessary, though.    And having the materials on the object instead of just including the name kind of invalidates part of the idea of the asset system, doesn't it? Specifically the deduping because now there will be tons of dupes if everyone did this for all their avatars and items that use multiple material slots.

**Comment by Frooxius** [comment]
> > erase everything else that's not necessary (e.g. the individual names).
> 
> Users obviously consider those names as necessary, though. And having the materials on the object instead of just including the name kind of invalidates part of the idea of the asset system, doesn't it? Specifically the deduping because now there will be tons of dupes if everyone did this for all their avatars and items that use multiple material slots.

If you consider the names necessary, then tell the system they're necessary by putting them under the slot. It's simple as that.

Yes, it will prevent the material from being deduplicated - it needs to. You can't unify multiple materials into a single one without losing the name of one or more of them. The whole point of the deduplication is that it removes unnecessary overhead - but you're asking for that overhead to be removed... while also keeping it at the same time.

You can't have your cake and eat it too.

However I don't really see this being such a big issue in practice for this particular use-case - how often do you have materials on your avatar that are exactly same as someone else's avatar? This seems very uncommon scenario to me.

**Comment by TisFoolish** [comment]
For me and several of my friends, quite a lot. I personally give out copies of my avatar freely and at times there are multiples 'Foolishes' in world at any moment. Those other friends of mine do similar things. There are also avatars that are meant to be used in group settings (eg games), meme items, and more.

**Comment by Frooxius** [comment]
My point is more general though - overall this doesn't seem that common. Yes, there's some cases where it'll happen, but that doesn't mean it's very common.

However, ultimately - it's a decision you have to make. If you want to keep the materials well organized and not consolidated, you have to pay a little extra performance overhead for that. Overall that's still kinda small, especially with avatars.

**Comment by BlueCyro** [comment]
This sounds like something that could potentially be clarified on the wiki, as it seems moreso that this particular mechanic is misunderstood/obscure to the end user rather than something that needs explicit tweaking

**Comment by SilvyPaws** [comment]
> This issue seems to be based on misunderstanding of how the asset system works and I think we're getting too deep into possible solutions, when one already exists.
> 
> > Currently, the only "solution" to this problem is saving all of your materials onto your avatar as components and naming your gameobjects to the associated material so you'll know what each material is. However, this means it'll no longer be using the asset variant system which is bad.
> 
> This actually _is_ the solution and it's the proper way how you can name materials.
> 
> It does not mean that it will no longer be using the asset variant system at all. I'm unsure where you got this information from, but it's not true, for two key reasons:

I'm glad this was the proper way to do things, I didn't think it was because I was told by multiple people that you only want material components on your avatar if you're animating values (Which makes sense to me). I'm new to this game so it was very frustrating trying to figure out what material was what on the avatar, and frustrating when trying to help a friend out with their avatar because nothing was named and they couldn't remember what went where. Hence the making of this post. Thanks for clarifying this, i'm satisfied with the answers given from both ProbablePrime and Frooxius. It was insightful <3
