### ISSUE TITLE
Enable OpenGLCore and/or Vulkan in the Windows build

### ISSUE THREAD

**Issue by Raidriar796** [Yellow-Dog-Man/Resonite-Issues#2757]
### Is your feature request related to a problem? Please describe.

With the removal of the native Linux build, which used OpenGL, requiring Wine/Proton limits use on Linux to DXVK to translate DX11 to Vulkan. DXVK is fine in most situations but it doesn't work well on every device. In my experience, Resonite with DXVK performs worse than native DX11.

### Describe the solution you'd like

Enable OpenGLCore and/or Vulkan. This may not require adding a new setting or a new launch argument as Unity has launch arguments for forcing specific graphics APIs.

### Describe alternatives you've considered

Doing nothing for now and waiting until Unity is replaced.

### Additional Context

According to [Unity's 2019.4 documentation](<https://docs.unity3d.com/2019.4/Documentation/Manual/GraphicsAPIs.html>), Vulkan is supported, but I do not know how mature Unity's support is in the 2019 version, and it might not be worth enabling.

### Requesters

@Raidriar796 / raidriar796

**Comment by Frooxius** [comment]
Unfortunately this isn't as simple as "enabling" those API's. We use a lot of custom systems, notably for handling texture assets and uploading them to the GPU using time slicing.

Because of that, we would need to implement support for both OpenGLCore and Vulkan to our systems for this to work, which is a substantial development effort (more for Vulkan than OpenGLCore).

The other issue is that Vulkan support with Unity 2019 is pretty immature last time I tried it. Deferred rendering doesn't work correctly, nor does VR.

Since we're already working towards moving away from Unity, we will not be investing time into implementing those solutions. I'm sorry.

**Comment by Raidriar796** [comment]
Understood.

How did the Linux build use OpenGL then? Was OpenGL being supported only for non Windows builds?

**Comment by Frooxius** [comment]
Yes, we only support OpenGL for Linux/Android builds. That's why OpenGL would be easier to implement on Windows than Vulkan, but it would still require development effort to support.

**Comment by coolymike** [comment]
OpenGL wasn't supported on Windows builds, but as far as I know, the OpenGL implementation for Linux could be used instead with relative ease (I could be wrong on that though).

Note that this requires extra work on the rendering side, which is unlikely to happen given Unity is going to get replaced by Sauce, and all work going into this is temporary.
