### ISSUE TITLE
Manually un-checking PresentInWorld doesn't affect SimpleAwayIndicator

### ISSUE THREAD

**Issue by SilvyPaws** [Yellow-Dog-Man/Resonite-Issues#2766]
### Describe the bug?

When un-checking PresentInWorld in the UserInspector, SimpleAwayIndicator doesn't react to this but FluxNodes do.

### To Reproduce

Use devtip > create new > Editor > User Inspector > Select Yourself and uncheck PresentInWorld

### Expected behavior

I'd expect SimpleAwayIndicator to react as if you're not present in the world. This was troublesome because I wanted to see what I looked like if I was in a different world to others while I was making my own material to see if it looks how i wanted it to look.

### Resonite Version Number

Beta 2024.8.5.1341

### What Platforms does this occur on?

Windows

### Log Files

Not required for this kind of bug

### Reporters

SilvyPaws

**Comment by Frooxius** [comment]
This is not really a bug - this field is informative only - it tells if you're present in the world, but it doesn't prescribe if you're present in the world or not - because it can't -  you're still in the world.

We can't really do anything about this in particular.

There's not really a need to do so in order to solve the problem you have - SimpleAwayIndicator has buttons in the inspector that let you test the effect, I recommend using those.
