### ISSUE TITLE
Add Zero G Alignment binding for Desktop.

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#2835]
# Is your feature request related to a problem? Please describe.
Zero G is fun, but in Desktop there's no binding for the Align action.
This action, re-aligns the user to the world. Which I use a lot in VR

# Relevant issues
No response

# Describe the solution you'd like
Add an alignment binding for desktop.

X, is free and the best option given that the other near keys such as e, r, f, c and even Z are used for other things.

# Describe alternatives you've considered
N/A

# Additional context
Requested by Spacerocket1, I can't find them on Discord

**Comment by CybrixTheProot** [comment]
a?

**Comment by epicEaston197** [comment]
I use X for my Sitting system I would have to rebind that and that's really annoying

**Comment by ProbablePrime** [comment]
We can't possible handle this for all keys, you might use X but another user would use any key I move it to. There's also bias, because you've commented here, but another user who might use the key I move it to wouldn't comment etc.

I understand that this is frustrating but we have no way to allow you to edit bindings right now. We do plan to allow key re-mapping in the future.

**Comment by Frooxius** [comment]
There's only few options from our end:
1) We pick a key - whoever already uses that key for something will end up having to remap it or use a mod to remap this one. There's no way to conceivably avoid any possible collisions
2) We halt all feature additions that need new keys until input binding UI is made - this blocks all those features behind a much bigger one. This is one of those cases where it's like "Why don't you just add it, it's just 1 minute change" on the surface, but then it gets complicated due to stuff like this.
3) We add convoluted mechanisms to trigger this - this leads to bad UI/UX - cases of "Why do you trigger this action in such obscure way, when everything else uses a key?" 

It's one of those things where there's not a path forward without a single downside. Out of all these, 1) is the simplest way to proceed on our end.

**Comment by epicEaston197** [comment]
I don't really think this is a button that users need to click really often It can be something like the "." key that wouldn't be accessed often

**Comment by Frooxius** [comment]
This leads to the problem of bad UI/UX though. Consider that you're a new user. And all the movement keys are around WASD - C for crouch,, Z for slow. X is right there in the middle, it would make sense right? Nope, it's all the way across the keyboard, out of reach of your WASD hand.

Plus consider someone is using "." for their stuff. While we solved your problem, we now made it that persons problem instead.

**Comment by kulzae** [comment]
> I use X for my Sitting system I would have to rebind that and that's really annoying I have built muscle memory around that particular button and I don't want to be realigned to world root every time I want to sit down
> 
> Maybe there's another way to access this feature without adding another hard coded key bind we can't modify giving users less options for triggering their own systems

Wouldn't this only do something when in zero g? How often would you be using your sitting system while also using zero g

**Comment by epicEaston197** [comment]
> Wouldn't this only do something when in zero g? How often would you be using your sitting system while also using zero g

Huh 
good point I thought this was a general purpose key bind for just Rotating yourself back up In other locomotions like fly or no clip

**Comment by ProbablePrime** [comment]
This shipped in: 2024.9.4.357
