### ISSUE TITLE
Avatar's entire head constantly looks around without any input

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#2891]
### Describe the bug?

When standing still in Desktop mode, my avatar's entire head keeps looking around, instead of just facing towards what I want to be looking at.
This happens on at least 3 of my avatars and only in desktop mode.

### To Reproduce

1. Stand in front of a mirror in Desktop mode.
2. Observe your avatar looking all over the place.

In case you don't have an avatar that does this, you can use this one:
resrec:///U-Psychpsyo/R-fbab33dd-1bb9-4eca-904d-2f7db6f8db9e

### Expected behavior

The avatar should just look straight ahead.

### Screenshots

[neo.webm](https://github.com/user-attachments/assets/adcd4a76-40eb-460d-bc7e-c960b08c178c)

[robt.webm](https://github.com/user-attachments/assets/fc14760c-0e29-42e3-bcc0-bc1e521de039)

### Resonite Version Number

Beta 2024.9.6.626

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

I do not feel comfortable sharing my log files, especially for issues this easily replicated.

### Additional Context

I think this might have to do with missing eye bones? Not sure though.

### Reporters

Psychpsyo in Resonite, cameron5 on Discord

**Comment by TisFoolish** [comment]
Log files have very little identifying information and what is in there can be easily removed, especially if the log file is just of you starting the game, observing the behavior, and closing the game. 

Further more, the devs *need* log files to make sure nothing weird is happening on your end. Full stop, logs are required to get help.

**Comment by shiftyscales** [comment]
Avatars idly looking around / moving their head is an intended part of the new animation system to give otherwise stiff desktop avatars a bit more liveliness.

If you do not like it and want to disable it, you can attach a LocomotionAnimationConfiguration component (from Users > Common Avatar Systems > Animation) to the avatars you do not want this behaviour on and adjust the following:

`HeadSwayVerticalAngle` > Set to 0
`HeadSwayHorizontalAngle` > Set to 0
`HeadMaxLookDirectionAngle` > Set to 0

Otherwise, if you want to keep it, but lessen the effect, you can try adjusting these / other properties to try and tune it to your liking.


https://github.com/user-attachments/assets/88cd5636-a71e-427d-b495-c5409e8ebc43

**Comment by Psychpsyo** [comment]
> Log files have very little identifying information and what is in there can be easily removed, especially if the log file is just of you starting the game, observing the behavior, and closing the game.
> 
> Further more, the devs _need_ log files to make sure nothing weird is happening on your end. Full stop, logs are required to get help.

I know the importance of log files and I am aware that they can be necessary to resolve issues.
Creating the log file for this issue just took me a little over 2 minutes.
Going through it to redact out things like my Steam ID, my contacts, my PC name, what websockets my client connects to and so on took me a bit over 18 minutes.
I'd rather not submit github issues at all than doing that every time and risking getting told off for trimming down my log files.
Also, this was without any homeworld getting loaded, just the empty local world and somehow Resonite still managed to load and log a youtube video I had watched a while ago.

That might sound petty but it's my decision and if it decreases the likelihood of my issues being addressed, then I am fine with that.
