### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Frozenreflex** [Yellow-Dog-Man/Resonite-Issues#29]

**Comment by Frozenreflex** [comment]
> Per our [best practices](https://github.com/Yellow-Dog-Man/Resonite-Issues#best-practices-for-bug-reporting) I would also like to remind you to use objective, and respectful language for any issues and comments submitted to our repo, @Frozenreflex.

I have not directly insulted anyone. Atrocious is an apt description for completely unplayable, unless you want me to call completely unplayable "sunshine and rainbows". You're reactively applying labels to me because I outed you from the Linux channel in the Neos Discord awhile ago. If anyone is being actively malicious right now, it's you, projecting malice onto me.

**Comment by Frozenreflex** [comment]
Thanks for ensuring I'll never report any issues I find here ever again.

**Comment by Gawdl3y** [comment]
I don't see anyone insulting you - you may need to re-read Shifty's reply, as they were just suggesting that you shouldn't assume that anyone here is trying to be malicious with what they say, which it does seem like you're assuming. As a completely regular member of the community without inside knowledge, I assume that logs are requested for every bug report for a multitude of reasons; it simplifies troubleshooting, reduces the potential need for manual reproduction, and helps ensure that there aren't other things interfering. Plus, quite honestly, not everybody can be expected to know when a log does or does not make sense to add, so it's just a blanket request to ensure it's there regardless.

On a more on-topic note, Geenz posted a preview of the libVLC upgrade in the [Discord #devlog channel](https://discord.com/channels/1040316820650991766/1154514014563483759) (specifically, [this message](https://discord.com/channels/1040316820650991766/1154514014563483759/1162775439895437343) and [this message](https://discord.com/channels/1040316820650991766/1154514014563483759/1162800357743792189)) they're working on. From prior discussions on the matter from the old platform (assuming it still applies), this is the main blocker for Linux video player functionality. When this upgrade gets finished and implemented in an update, I assume that video players on the native Linux build will be fully-functional! 🤞

**Comment by Frozenreflex** [comment]
> they were just suggesting that you shouldn't assume that anyone here is trying to be malicious with what they say

You didn't get to read what I said before they censored me. I didn't assume malice in the first place and it's insulting to me to accuse me of assuming malice like that, then delete my message going against that. I feel double insulted that you also assume I assumed malice.

> I assume that logs are requested for every bug report for a multitude of reasons; it simplifies troubleshooting, reduces the potential need for manual reproduction, and helps ensure that there aren't other things interfering. Plus, quite honestly, not everybody can be expected to know when a log does or does not make sense to add, so it's just a blanket request to ensure it's there regardless.

This is not an average case. I decompiled the game and figured out exactly why the bug was happening, and wrote a fix for it myself , then proceeded to link to that fix on the [Neos Github](https://github.com/Neos-Metaverse/NeosPublic/issues/2762#issuecomment-1079819075), where I proceeded to get basically no official response. There (was) no need for logs because the fix was sitting right in front of them, and were they not overhauling the video players now, they could just apply the fix and it would work fine. Given that I gave them the fix such a long time ago, they could've easily included it in the Resonite launch.


I am well aware of what Geenz is doing, and I think it's rather redundant because they're both going to ditch Unity in the future and it seems like they're just breaking video players on Linux even more. It also seems that nobody is reading what the fix I made actually is, because the blocker for video players on Linux in Neos was not some big overarching problem that would take a long time to solve and lots of overhauled code, it was two misconfigured strings, which is basically a one minute fix.

**Comment by Gawdl3y** [comment]
> You didn't get to read what I said before they censored me. I didn't assume malice in the first place and it's insulting to me to accuse me of assuming malice like that, then delete my message going against that. I feel double insulted that you also assume I assumed malice. I didn't assume malice on my first reply, I just speak bluntly. Now that I've been censored, I absolutely assume malice.

Your words are coming across to me as quite hostile, and I don't think that I'm the only one that would think so. "Speaking bluntly" is not really a great reason for this usually. I consider myself to speak rather bluntly most of the time, but still try to word things in ways that avoid unintentional ire. Perhaps you don't intend on being hostile at all, which I absolutely would believe - in that case, I'd offer the friendly suggestion of consciously wording things in a more friendly/less controversial manner.

> This is not an average case. I decompiled the game and figured out exactly why the bug was happening, and wrote a fix for it myself, then proceeded to link to that fix on the [Neos Github](https://github.com/Neos-Metaverse/NeosPublic/issues/2762#issuecomment-1079819075), where I proceeded to get basically no official response. There (was) no need for logs because the fix was sitting right in front of them, and were they not overhauling the video players now, they could just apply the fix and it would work fine. Given that I gave them the fix such a long time ago, they could've easily included it in the Resonite launch.

I'm sure the team appreciates the additional effort you put into this, but that doesn't really mean you deserve a pass to skip a required step of the issue reporting process, at least in my mind. Logs should basically always be present on bug reports, unless it truly isn't applicable at all.

> I am well aware of what Geenz is doing, and I think it's rather redundant because they're both going to ditch Unity in the future and it seems like they're just breaking video players on Linux even more. It also seems that nobody is reading what the fix I made actually is, because the blocker for video players on Linux in Neos was not some big overarching problem that would take a long time to solve and lots of overhauled code, it was two misconfigured strings, which is basically a one minute fix.

I can't comment on your suggested fix because I'm not knowledgeable enough on the matter. That being said, the libVLC update benefits everybody, not just Linux users, as it has far more consistency and support for codecs across all platforms than Unity ever will. The existing libVLC is a very old, custom implementation that replacing will greatly improve the stability and compatibility of. Plus, eliminating reliance on Unity is always good, as it's going the way of the dodo in the long-term for Resonite. The goal is to completely remove Unity from the equation and use a custom renderer (Sauce) and modern .NET runtime.

**Comment by Frozenreflex** [comment]
> Your words are coming across to me as quite hostile

They are now because I've been insulted and censored and made out to be the bad guy when I was trying to help,

> but that doesn't really mean you deserve a pass to skip a required step of the issue reporting process

It was not required when this spat started.

> I'm sure the team appreciates the additional effort you put into this

Doesn't really seem like it to me, considering how long I've been ignored and the previous arguments I've had with Shifty (something that was censored).

> That being said, the libVLC update benefits everybody, not just Linux users

Given that it makes fixing video players on Linux exponentially harder, I don't think it benefits everyone at all.

> The goal is to completely remove Unity from the equation and use a custom renderer (Sauce) and modern .NET runtime.

I am fully aware of this, I have been for a long time, and that is why the overhaul seems redundant to me, it uses Unity-VLC which also does not support Linux.

**Comment by ProbablePrime** [comment]
I've hidden the majority of comments on this thread as Off-Topic. I'd like for us to focus on the issue at hand which is Video Players being broken on Linux.

Thank you.

**Comment by Frozenreflex** [comment]
Ah, so you're marking my argument with someone else as offtopic, but not the insults from your colleague directed at me that started the whole mess. Gotcha, I see how it is.
Here's your logs that you wanted. The game file log says that youtube-dl couldn't be found, which I already said and explained very thoroughly why it does that, and the player.log didn't contain the error about the UMP settings directory. Just as I said, you did not need the logs. I had to use the superpiss mod (#69) to get the game to boot properly, because otherwise it gets stuck with a glitchy loading world and a blank dash, so these logs wouldn't even suffice for the no mods requirement. Are you happy now?

[frozenreflex - 2023.10.13.743 - 2023-10-17 00_50_28.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12924785/frozenreflex.-.2023.10.13.743.-.2023-10-17.00_50_28.log)
[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12924790/Player.log)

**Comment by ProbablePrime** [comment]
Thanks for the log file, I am now kicking this back to the Triage state.

Please keep all comments professional and respectful, or they will be hidden.

**Comment by Frozenreflex** [comment]
> Please keep all comments professional and respectful, or they will be hidden.

If what you want is professional comments only, please hide the comments from your colleague.

**Comment by ProbablePrime** [comment]
Shifty's comments are professional. They're reminders of our best practices and requests for information.

Thank you.

**Comment by Frozenreflex** [comment]
> Shifty's comments are professional. They're reminders of our best practices and requests for information.
> 
> Thank you.

Saying definitively that I assume malice is not professional.

**Comment by iamgreaser** [comment]
It's probably worth opening a new issue saying more or less what needs to happen, and then taking the low-hanging fruit and JFDI - you get a bug fix that you didn't have to find yourself, and you make a notable minority of your community happy - notable because we host some of your most important headless servers :)

Considering how much the NeosVR Linux version has been completely and utterly shoved so far to the back of the queue of stuff to do that it's fallen off the edge, I can understand why Frozen would be so frustrated about this not being worked on. Hell, the fact that the Linux build never got the updated CloudX library despite being a fully-functional drop-in replacement was the final straw for me which motivated me to start making my own replacement for NeosVR from the ground up.

Anyway, this issue still needs to be tracked properly.

And Frozen: This is the sort of thing you should never attribute to malice.

**Comment by Frozenreflex** [comment]
> And Frozen: This is the sort of thing you should never attribute to malice.

I didn't in the first place. Everyone else is saying I definitively did, and when I tried to tell them I wasn't I got censored and hidden.
