### ISSUE TITLE
Add edit mode button to dash

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#290]
### Is your feature request related to a problem? Please describe.

**I was kinda conflicted if I should make this a feature request or a content issue**

the main reason why I want this is because most new users are gonna be incredibly confused when we tell them how to go into edit mode and this would also require guides and panels to be created to tell people how to go into edit mode on their individual controllers which is just complicated just having a single button on the dash that would make it go into edit mode would be preferable

### Describe the solution you'd like

A dedicated button on the dash that would put it into edit mode without needing any weird controller key bind
kinda like this
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/1bad4e2c-5b9b-4c60-aa8e-6418d9225649)

### Describe alternatives you've considered

Giving the new user an edit mode button then telling them to save it to there inventory and telling them to click the button in their user space (this works really well)

### Additional Context

I was wanting to make this a content issue since I think that would fit this issue very well but the description of it is related to existing official content so I didn't think this is applicable please correct me if I'm wrong

**Comment by epicEaston197** [comment]
> What items are you giving to new users that require editing at a userspace level?

Simple quality of life facets like a mirror and world's you're in and others this is really useful functionality that most users will never learn because they don't know how it works because it's hidden behind a unintuitive key bind

**Comment by Zyro1331** [comment]
I would really appreciate this change as entering edit mode with a custom binding (such as one that re-assigns the "A" button on my right Index controllers to be jump instead of a secondary dashboard button) is much more difficult than it needs to be. 
I don't know if it needs to be it's own dedicated facet as I don't access it too often though.

Some sort of gesture like long-holding Primary while hovering over the center of your dashboard's home-screen could also enter Edit mode. But I do have a much further reaching idea.

I feel this would be more appropriate when integrated with a much improved UI Modal system. 
You know what happens when you press the Secondary button while in the Desktop tab? It'll open up a little modal with options like what monitor you're using and what you wish to input. 
Adding some functionality like this to the Home tab when you are just hovering over the backdrop and hit secondary, it could open up a modal which would let you easily enter edit mode, save your changes to your dashboard, or even have some sort of "advanced options" to whatever facet you were hovering over when you pressed the Secondary button. Likely though this is a much further and more ambitious reach, but from a User Experience standpoint it would be much improved, along with keeping the home screen simple while letting the Facets have much more flexibility for what they do.

Think of the implementation similar to how Android does it's widgets. When you long press the Wallpaper on an Android device, it will open a context menu asking if you want to edit widgets, change the wallpaper, or enter system settings. When you do the same action over an app, that app can show quick shortcuts to actions the app supports. Adding more functionality while keeping the base home screen much more concealed. 

Of course though, I'm pretty sure the reason why Edit mode's controller gesture is so complex is due to it's currently VR only nature. _(see issue #628)_ So even if it's a little complicated at the moment, I'd say to live with it as stays currently. 
And if that one user-created Edit mode facet still works, you can probably continue using that for the moment until things improve and this issue can be resolved. I wouldn't recommend inviting brand new users to use UI Edit mode unless they _really_ desire custom facets.

**Comment by gentlecolts** [comment]
somewhat related to #99

**Comment by shiftyscales** [comment]
Discussed with @Frooxius in our coding team sync today the possibility of introducing UI Edit Mode as a setting. This would in turn prevent the case of new users pressing a button and accidentally messing up their UI- since it'd require users to discover, and enable the setting in the first place.

It would also mean that the user could then take a copy of the setting as a facet to place elsewhere on their dash/facet containers wherever they like.

**Comment by Frooxius** [comment]
There's now a setting in 2024.5.28.94, thanks!
