### ISSUE TITLE
Footstep events don't work in the cloud home. (colliders that are character colliders but have raycasts disabled.)

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#2938]
### Describe the bug?

I think because IgnoreRaycasts is on the cloud home's colliders, the feet aren't causing footstep events.

### To Reproduce

Enter the cloud home, and walk into the main area. You will see that footstep events do not trigger in the main area, spawn is fine but not the convex hull colliders in the main area.

### Expected behavior

For the footstep events to work on any character collider, regardless if they have IgnoreRaycasts on or off.

### Screenshots

In this video i'm using the self relay, and you can see me enable and disable the IgnoreRaycasts on the collider.

https://github.com/user-attachments/assets/d151a457-6fc1-4fb2-8a4c-7d8d252ee680

### Resonite Version Number

Beta 2024.9.12.772

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

N/A, This issue is probably not really a bug, but it's not behaving as i'm expecting it so i'm reporting it as a bug. Rather it's a behaviour that should maybe be looked at, because i'd probably think it was a bug if I was building this footstep thing in the cloud home.

### Reporters

ModernBalloonie

**Comment by ModernBalloonie** [comment]
Also this isn't a content issue, it's related to the footstep system itself. just clarifying.

**Comment by AmasterAmaster** [comment]
This confused me as well, as I used the dawn modular set in my classroom world and I was struggling to figure out why the node was not firing. Basically this issue is why (and I documented it on the wiki accordingly). I also wish it was just collider based and not raycast based, as that confused me for a good while.

**Comment by ModernBalloonie** [comment]
I feel like this post is sort of a feature request too, that being for the footstep events to trigger on character colliders in particular because, well it makes sense.

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius.

Although this is in-part possibly a content issue, @ModernBalloonie. In specific it's effectively yet more side-effects / consequences of decisions made in how the cloud home colliders were set up as I highlighted in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/524#issuecomment-1912574400.

@RyuviTheViali had noted there:
> As for the object colliders themselves, there is currently no method to keep our current feature set with the models while enabling raycasts on the simple colliders and/or removing the (non-collision) mesh collider, so these are being kept as-is.

I'm not certain what features those are in specific- but if possible, ensuring the character colliders are raycastable would be ideal.

**Comment by Frooxius** [comment]
This is difficult one. The system requires raycast to determine the exact point where the foot lands. So if IgnoreRaycasts is off, then it cannot determine where the foot has actually landed - it's effectively landing "in air" and it cannot generate a footstep event.

Question is, why is the IgnoreRaycasts turned off?

**Comment by shiftyscales** [comment]
Seeking input from @RyuviTheViali.

**Comment by RyuviTheViali** [comment]
The primitive colliders for the modular pieces have IgnoreRaycasts enabled so that the mesh collider for the render mesh of the modular piece can easily have its materials changed and reassigned using the material tool. Enabling raycasts on the primitive colliders would prevent the mesh collider from being interacted with, removing the ability for users to directly interact with the modular piece's materials. It's mostly setup this way because I don't think there is another way to provide accurate primitive-collider-based collisions on something while retaining the ability to manipulate the render mesh's materials (in essence, preserving this functionality when the collision mesh and render meshes differ).

**Comment by Frooxius** [comment]
Thanks for info!

Since it sounds like there's a collider already - the footstep system should be hitting that one with raycasts, since material tools can too.

Does placing the footstep events components in this collider not work? You don't need to place it on the exact slot that the character controller is colliding with. In fact, this one is probably better, because you can make the sound differ depending on the submesh.

**Comment by ModernBalloonie** [comment]
> Thanks for info!
> 
> Since it sounds like there's a collider already - the footstep system should be hitting that one with raycasts, since material tools can too.
> 
> Does placing the footstep events components in this collider not work? You don't need to place it on the exact slot that the character controller is colliding with. In fact, this one is probably better, because you can make the sound differ depending on the submesh.

![image](https://github.com/user-attachments/assets/4245f0f0-e299-4882-9cb8-b7c39b42fcd9)
Hmm, i tried placing the footstep events on the collider, and it doesn't seem to have worked.

**Comment by ModernBalloonie** [comment]
However, update: if I make the collider for that a static collider, it does work. I think I do remember it working without collisions though.

**Comment by Frooxius** [comment]
I see. I think best change here is to make it work with colliders that have "NoCollision" set on them too. I'll change the filtering rules on this. Thanks!

**Comment by Frooxius** [comment]
I've made the changes in 2024.9.13.672! Thanks! Closing this one.
