### ISSUE TITLE
Userspace prompts and userspace laser are below the user

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#2941]
### Describe the bug?

In desktop mode, attempting to Use Save As/Save Copy will move the prompt to be below the user at [0, 0, 0]. Additionally seems like all other things that spawn into the userspace to be shown exhibit this and appear below the user. The only one that doesn't is now the world join indicator as that one was specifically addressed https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2855 

### To Reproduce

Create a new world (Or open any existing)
Go to Session tab in your dash
Attempt to 'Save As' or 'Save Copy'
Observe 

### Expected behavior

For Userspace prompts to be shown in front of the user.

### Screenshots

https://private-user-images.githubusercontent.com/31176843/365430816-55f09bae-d667-404f-92c0-f1b1a2a44524.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzk3NjYsIm5iZiI6MTcyNjE3OTQ2NiwicGF0aCI6Ii8zMTE3Njg0My8zNjU0MzA4MTYtNTVmMDliYWUtZDY2Ny00MDRmLTkyYzAtZjFiMWEyYTQ0NTI0Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIyMTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMmQyN2U4NDk0MTYyMGRkN2Y0YTYyZDljNWRlMDA0OWU2YTI5ZWI3NmU2OThmMGU0MGZiNGM0YjM0MjM0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aPFcrLW6qFf59OSj-WLO7epXFdG0KAXZjATd4f5EqDI

![955ea47c66-1](https://github.com/user-attachments/assets/7bd9d341-2d37-4eaa-9b91-1c94038afd20)

### Resonite Version Number

Beta 2024.9.12.772

### What Platforms does this occur on?

Windows

### Additional Context

Mentioned in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2855

Related https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/722 (specifically for Overwrite World)

Also seems to effect some other things that call `PositionInFrontOfUser` such as the `OpenInspectorButton` delegate on a RefEditor.

### Reporters

_deltawolf

**Comment by shiftyscales** [comment]
Thanks for making this issue, @XDelta - it seems others didn't heed @ProbablePrime's warning to file a separate issue for this one.

Assigning them since they handled the related issue #2855.

**Comment by XDelta** [comment]
Adding an additional note from a brief look at other things that appear to be placed at [0, 0, 0].
`PositionInFrontOfUser` may be part of the cause of these all being in the wrong spot. Prime mentioned part of the head positioning being odd but unchanged
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2855#issuecomment-2328497571

**Comment by ModernBalloonie** [comment]
Yup, I can confirm this.

**Comment by NepuShiro** [comment]
I can confirm this as well.

I can also give insight to why this is happening, since the Userspace UserRoot isn't initialized with any Locomotion/IK so the tracked body is at [0, 0, 0] including the head and hands. You can confirm this by using a Userspace inspector to look at any of the UserRoot tracked devices and see that they're at [0, 0, 0] and not tracking. (This issue wasn't present in the last update before the Locomotion update, Beta 2024.8.5.1341)

All of these issues are also more prominent using the unofficial mod (3DDashOnScreen) to give desktop the VR Dash and complete 3D Userspace, so things as Hand Lasers, items spawned that use the PositionAtUser/HeadPosition, etc. all spawn at [0, 0, 0]

**Comment by ProbablePrime** [comment]
This also affects the particles on the dash.

https://cdn.discordapp.com/attachments/1159271139483320483/1284810863429161031/2024-09-15_02-37-59.mp4?ex=66e7fcdc&is=66e6ab5c&hm=6c8c876a137c0831d9b2bd07820ba4f211441b3ed5678d2b9688f2d1767a2343&

**Comment by ProbablePrime** [comment]
Im heading off on vacation on the 5th, so probably won't have time for this one, I've assigned @RyuviTheViali to take a look while Im away. But Ryuvi can reach out for help.

**Comment by RyuviTheViali** [comment]
Figured I'd update here while doing some research - the ValueStreams for the Userspace head slot themselves are returning [0;0;0], and internally some components aren't registering that they've received data at all (since it hasn't changed from [0;0;0]). Still attempting to figure out why this is, though.

**Comment by ProbablePrime** [comment]
There are some more cases of this here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/722

**Comment by ProbablePrime** [comment]
@RyuviTheViali Is also going on Vacation on the 5th and has had a look here and would like more assistance.

@Frooxius this sounds like a deeper issue, see comments from Ryuvi: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2941#issuecomment-2384615602

**Comment by Frooxius** [comment]
I've fixed this in 2024.10.8.1349, thanks for the report!
