### ISSUE TITLE
FFMPEG as a choice for media streams.

### ISSUE THREAD

**Issue by ItsAlphaNeon** [Yellow-Dog-Man/Resonite-Issues#2953]
### Is your feature request related to a problem? Please describe.

Resonite's implementation of yt-dlp is fine for most Youtube cases, but attempting to stream from m3u8 playlists or other streamable sources often causes issues, or just flat out doesn't work. 

### Describe the solution you'd like

I believe allowing FFMPEG to be a media player backend choice would resolve a lot of these playback issues, and would give more freedom in what media can be streamed inside of Resonite.

### Describe alternatives you've considered

I have tried using different streaming formats with yt-dlp, and while these work in the CLI to download the streams, none of my efforts seem to result in the media playback occurring in-game with a media player.

### Requesters

@alphaneon

**Comment by Frooxius** [comment]
I don't know if resolving this with FFMPEG is necessarily the best choice here to resolve the problem.

We already have plan to upgrade the libVLC to the official library for example: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1476

However I don't understand what kinds of issues you're actually encountering? This might be more yt-dlp issue, rather than the video playback engine one.

I'd recommend making an issue on the problems you're encountering. Integrating a video playback framework and maintaining is a huge undertaking, so we're very unlikely to prioritize that as a solution for something that could be a smaller problem elsewhere.
