### ISSUE TITLE
CachePath supplied by any mechanism will have "Cache" appended to it.

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#3114]
### Describe the bug?

When using, [command line arguments](https://wiki.resonite.com/Relocate_Resonite_Folders) or [Configuration Files](https://github.com/Yellow-Dog-Man/JSONSchemas)

To specify a Cache Path, the Word "Cache" is added to the end of the path.

### To Reproduce

1. Edit the cache path of your resonite, [command line arguments](https://wiki.resonite.com/Relocate_Resonite_Folders) are easiest. 
2. Ensure that you include cache in the path, for example: `-CachePath D:\Resonite\Cache`
3. With Resonite started observe that the cache path will have an extra Cache appended to it, so for our example the final cachepath would be: `D:\Resonite\Cache\Cache`

### Expected behavior

It is expected that CachePath is an absolute path to the cache and therefore a second "cache" should not be added.

### Screenshots

![Image](https://github.com/user-attachments/assets/b961289b-b1c9-4fb1-a1ed-27cb6b4d3d30)

### Resonite Version Number

2024.9.16.110

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

N/A

### Log Files

[ALFRED - 2024.9.16.1105 - 2024-09-30 01_50_55.log](https://github.com/user-attachments/files/17483982/ALFRED.-.2024.9.16.1105.-.2024-09-30.01_50_55.log)

### Additional Context

Im sure I've seen an issue for this before, but could not find it, because search for these specific terms is hard.

Its also a difficult thing to solve we could:
1. Remove the addition of a "Cache" suffix, but this would break anyone who did not add a cache suffix and expected it to be in a folder named "Cache"?
2. Do Nothing at all, and just document this oddity?
3. If we detect that the CachePath contains, cache, do not append "Cache"?

It seems like this was originally done in a way which matches the use of DataPath, where DataPath does contain sub-folders that are created in the same location within Resonite's LocalDB.

You can see this in this abridged code:
```cs
public LocalDB(SkyFrostInterface cloud, string permanentPath, string temporaryPath, HashSet<string> precachePaths)
{
....
    if (permanentPath == null)
        throw new ArgumentNullException(nameof(permanentPath));

    if (temporaryPath == null)
        throw new ArgumentNullException(nameof(temporaryPath));

    this.Cloud = cloud;

    this.PermanentPath = permanentPath;
    this.TemporaryPath = temporaryPath;
    this._precachePaths = precachePaths;

    this.AssetCachePath = Path.Combine(TemporaryPath, "Cache");
    this.AssetStoragePath = Path.Combine(PermanentPath, "Assets");
....
}
```

LocalDB get's initialized with its "temporaryPath" parameter containing the full path from the CachePath config or Command line parameters. E.g. `D:\Resonite\Cache` and then LocalDB adds "Cache" again.

I think LocalDB is doing this, because its treating "temporaryPath" as having differing semantics to "CachePath" in other concepts.

Number 3, is probably the most backweards compatible solution, but it does leave some weird logic in place that might be confusing in the future, so I'm not sure.

### Reporters

Private Corporate Client

**Comment by XDelta** [comment]
I use `-DataPath "V:\Resonite" -CachePath "V:\Resonite"`. I personally would suggest just not including the text of "Cache" in the path override when adding it into launch args. (option 2: doing nothing) That also can allow for changing the structure or adding more files that aren't strictly in that '/Cache' folder down the line more similar to the datapath option. Changing it otherwise would be tricky to do without breaking how it is currently setup for people.

I think this mainly would come up as an oddity if your cache and data paths are 2 separate locations entirely. Most of the reason I see for users changing either/both in the first place is changing the drive it gets stored on, which would still likely lead to them both moving to the same spot.

Option 3: While would be backwards compatible, I agree that would be some weird logic in place for a very niche thing. And without any mention/warning of that. It would just delay the 'breaking change' and would still require the additional documentation for it.

**Comment by ProbablePrime** [comment]
Thanks for the commentary, this is the whole reason I put this issue down into a GH issue to inspire such conversation.

You've made me think that its basically only LocalDB's cache that exists right now. Let's say there's another cache in the future, the gloopie cache. Then the cache path would be more like a "Cache Root" which specifies where all different varieties of Caches that we come up with can live.

That also makes sense documentation wise to explain the distinction.

**Comment by XDelta** [comment]
Describing both DataPath and CachePath as 'root' paths instead of the final path would be a good way to present it. Currently there is just the one big cache but maybe at some point that separates out thumbnail cache or maybe there are additional files next to the cache that aren't directly in that cache folder.

**Comment by ko-tengu** [comment]
Yeah, I never saw this as an issue and assumed it was for a root folder similar to the -datapath command.

**Comment by ProbablePrime** [comment]
Thanks! Yeah I'll speak to the corporate client and explain the rationale. I'll also update the wiki, but we don't need to do anything here!

**Comment by shiftyscales** [comment]
@ProbablePrime - The cache folder is not the only thing stored in the "cache" location- if Resonite has a managed crash, crash dumps are stored in a "Crashes" folder contained within the top-level cache directory- it sounds like the conclusion has already come to 'do nothing, document' - but this is one more detail/note to add, and another point in the 'keep it as it is' column as far as I'm concerned. :)

**Comment by ProbablePrime** [comment]
Good Observation and a "deal sealer" let's keep it open for a day longer while i get the docs sorted, then ill close it!

**Comment by ko-tengu** [comment]
> [@ProbablePrime](https://github.com/ProbablePrime) - The cache folder is not the only thing stored in the "cache" location- if Resonite has a managed crash, crash dumps are stored in a "Crashes" folder contained within the top-level cache directory- it sounds like the conclusion has already come to 'do nothing, document' - but this is one more detail/note to add, and another point in the 'keep it as it is' column as far as I'm concerned. :)

Incorrect, these are unity generated and are always stored at ` %temp%\Yellow Dog Man Studios\Resonite\Crashes`, likewise the unity logs are always stored at `\LocalLow\Yellow Dog Man Studios\Resonite`

**Comment by shiftyscales** [comment]
Good to know, @ko-tengu - but that likely at least explains the default behaviour. But that would also mean that in that context, there is no "Cache" subfolder- as inside of `%TEMP%\Yellow Dog Man Studios\Resonite\` there is only one `Cache` folder since `%TEMP%\Yellow Dog Man Studios\Resonite\` would be the "CachePath" in that context.

**Comment by ProbablePrime** [comment]
I've updated some language on the wiki here and can adjust more if needed, closing as not planned.
