### ISSUE TITLE
a "grandparent cellphone UI" like UI for newer / players who want it for avatar creation

### ISSUE THREAD

**Issue by KaedeyRe** [Yellow-Dog-Man/Resonite-Issues#3182]
### Is your feature request related to a problem? Please describe.

UI to help light unity users feel more comfy coming over

### Describe the solution you'd like

so im new to github so bear with me...

somethin id really enjoy an i feel would add to the new user experience would be a UI mode for avatar creation that was on by default for new users an one someone could opt into if they want later. what im wanting is... its hard to explain but samsung phones have a "grandparent mode" that reduces alot of the UI to bare bones an makes icons really big for older users. this kinda thing would be really great cause alot of friends ive shown resonite to see the crazy amount of UI options when making avatars an hard nope out of the game or the discord stream.

what im suggesting is a "new player UI" for avatar creation. hide anything that isnt nessesary to get a FBX into the game, add textures, change some light physics settings an maybe a shader setting or two. somethin that light unity users from vrchat could understand to get their avi of choice functioning at a basic level. im not sayin like it needs to have crazy features, just somethin bare bones enough so they dont feel uncomfy.

i understand the "just use an existing avatar" but alot of people from vrchat an other platforms want to be in somethin they call their own an would feel much more at home in their own avatar coming over to resonite but as it is right now, its scares some people away.

sorry if i explained that poorly, im not into dev stuff much.

much thanks <3

### Describe alternatives you've considered

uhhh idk?

### Requesters

discord : re.kaedey

**Comment by TheRealSphyxia** [comment]
The casual user who has no real interest in creation for the most part is the life blood for the success of the platform on the longer term.
Most users in VRChat with "custom avatars" will usually purchase a premade avatar that comes with a unity packages that is essentially a drag and drop then upload.
ResonitePackages are big step into helping the non-creator types have an easier time, but is dependent on users creating these packages in the first place.
A bit of hand holding for non technical types would be great to help people get started, who are just here to hang out, socialize, and play with what others have made

**Comment by Frooxius** [comment]
Thank you for the suggestion. We definitely want to make avatar creation as simple as possible and there are things to make the UI and interactions simpler.

However importing/creating avatar from scratch is ultimately a complex process and it can be impossible to reduce that complexity, while still having it work with all possible avatar. Say we make UI that has significantly reduced options to simplify - now you'll only be able to setup 10 % of all avatars with it.

If you happen to be in that other 90 %, you'll be stuck and not able to setup your avatar, because the UI is missing all the functionality needed for your particular avatar - which can be even more frustrating for the user - while also wasting a lot of our time to maintain 2 separate pieces of UI and tooling, which is difficult for our small team.

Think of the analogy as trying to make a programming language for grandparents who have difficulty operating TV - if you make something they can understand, it'll have to be so dumbed down that you can't really do much with it.

What I see as best way forward for these problems are:
- Rework the avatar creator to simplify the initial setup and automate more parts - this will make the overall setup easier and reduce the times you need to go to inspector to set the avatar up
- Introduce a Workshop ( https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1473 ) - this will allow offering the user pre-setup base of the avatar they're trying to import, perhaps with a version that was configured by the creator/community with a simple UI specifically for that avatar
- Unity import SDK ( https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/6 ) - for users coming from VRC, this could allow simple conversion of their existing avatar without having to re-setup it in Resonite

**Comment by KaedeyRe** [comment]
yeah that makes sense. the unity import sdk imo would be really great imo an imo would solve alot of issues ive run into showin others resonite. im assumin itd just be export your unity package an slap it / the scene into resonite (at a very basic level). 

ty for the reply an yeah i guess i forgot that a UI like that would have to be maintained (im just a silly vrchat user who spends too much of their life in unity >w>;;)

**Comment by ProbablePrime** [comment]
As other items have been referenced that would be done in place of this grandparent mode, we can close this one as unplanned.
