### ISSUE TITLE
Add JSONDataFeed component

### ISSUE THREAD

**Issue by brecert** [Yellow-Dog-Man/Resonite-Issues#3186]
### Is your feature request related to a problem? Please describe.

JSON is a commonly used format for data interchange, often used for configuration files and responses from APIs.

Currently JSON is already parsed and used in a variety of ways throughout Resonite, however Resonite has no way to built in way to interface with JSON data, leading to ProtoFlux parsers that can often cause lag, are fragile, and/or are a lot of work to set up and create.

This means there's no convenient way to consume and work with JSON from APIs or work with JSON data that's imported into the game from outside the game.

Some examples uses of JSON currently are
- creating slots with dynamic variables and UI elements for questions and answers from a trivia API
- creating slots with dynamic variables using data fetched from PluralKit
- parsing JSON for a mastodon viewer
- creating dynamic variables for truth or dare questions fetched from a truth or dare API

JSON is planned to be supported in the future (#572 and #946), however generic collections support seems like it will take some time to add.

### Describe the solution you'd like

JSON data feeds for consuming and working with JSON inputs.

This should be able to be added more immediately without needing to wait on generic ProtoFlux collection support, and immediately be more performant than existing ProtoFlux systems that generate slots from an input.

I'd like to be able to create UIs using data from various APIs that return JSON, and access the current path to create unique and consistent dynvars names for JSON values easily, and I'd like to be able to use JSON as way to have external programs interface with Resonite more easily.

In the future when #572 is resolved it should still be distinct enough from a ProtoFlux solution to provide an more intuitive and easy way to consume and work with JSON depending on the use case.

I'm not sure of how a JSON input should be provided to the data feed.
A string input could be wasteful in both memory and the network for larger inputs but may fit best in existing UX patterns. A method that's called with a string input to process the JSON could be more efficient and fit well into ProtoFlux that fetches JSON but may have a strange UX otherwise.

### Describe alternatives you've considered

Continuing to use existing ProtoFlux systems and waiting until #572 and #946 are resolved to build our own efficient JSON data feeds.

### Additional Context

Many services that target Resonite use their own format that's easier and more efficient to parse than JSON within Resonite. It takes additional effort to work with those formats, can cause ProtoFlux to be less understandable since it's parsing a bespoke format, and lag a bit despite those improvements. UniPocket, two different event calendars I've seen, and even some of my own projects take this approach.

I'm hoping a JSON data feed would also be a replacement for those cases as well, and make it easier to interface with existing APIs without needing a proxy with processing or needing to use a bespoke format.

### Requesters

brecert

**Comment by Frooxius** [comment]
I don't really see a uniform way to convert arbitrary JSON into a data feed - JSON documents can be formatted in variety of different ways, so there's not a single way to convert them to a data feed.

We'd need to add some sort of system to determine how will the JSON data actually map to data feed, which would get quite complex - probably more complex than just actually supporting JSON and letting you process the data generically.

Data feeds also don't really give you much way to actually work with the resulting data - they generate a number of objects, like end UI, but often times to work with JSON you need to actually parse and process the data in various complex ways - I can see this solving only certain niche uses of JSON usage, but not being useful for most of them.

And generally, we do avoid "workarounds / shortcuts" like this - they end up being more trouble than worth, because we have to maintain them long term and fix all the issues and shortcomings that come with them. If we want to implement something, as principle we do it properly.

Because of these reasons, we're very unlikely to add this.
