### ISSUE TITLE
dynamic impulse data with extra pulse outputs

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#3195]
### Is your feature request related to a problem? Please describe.

currently, you can not check if a impulse made it to the receiver.

### Describe the solution you'd like

similar to the write dynamic node, have options for or like:
- on not found
- on failed
- on sent
- sent

### Describe alternatives you've considered

there are no alternitives to this that i can use with projects in the way i'm using them

### Requesters

charlie-san

**Comment by 5H4D0W-X** [comment]
I don't understand how this would work considering that a dynamic impulse trigger can trigger any number of receivers. What constitutes a "fail"? If that's just when no receiver is triggered, you can simply compare the existing TriggeredCount output and check if it's 0.

**Comment by Frooxius** [comment]
We cannot implement this, because this doesn't really match how dynamic impulses work:
- They are one-to-many relationship - you can have more than one receiver for single trigger
- They have no concept of "failing". They're either triggered or not

The only feasible information that you can get is how many receivers were found for given invocation, which the dynamic impulse trigger nodes already provide through their "TriggeredCount" output.

It might help to understand what your underlying issue is, but for what you are specifically requesting here, we cannot implement this for the reasons above.

**Comment by charlie-sans** [comment]
so i'm trying to check if a dynamic impulse receiver exists or if one of them exists and if not return to the user that whatever they are doing doesnt exist

**Comment by Frooxius** [comment]
TriggeredCount will give you how many of them were triggered. You should be able to check if it's larger than 0.

Is that sufficient to get the information you want?

**Comment by charlie-sans** [comment]
anything works! i'm more just trying to see if something picked it up

**Comment by shiftyscales** [comment]
It sounds like the TriggeredCount should work perfectly for that use case then, @charlie-sans.
