### ISSUE TITLE
Custom shaders

### ISSUE THREAD

**Issue by InconsolableCellist** [Yellow-Dog-Man/Resonite-Issues#32]
### Is your feature request related to a problem? Please describe.

Creators would really love to have custom shader support.

### Describe the solution you'd like

Custom shaders are a wonderful thing, unlocking tons of potential for avatar and world creation. It'd be great to support them. One of the most popular shader requetss, I'm sure, is for Poiyomi, an excellent and flexible avatar shader. But the importance of shaders go beyond that, and would unlock all sorts of possibilities, including crazy things like compute shaders, geometry deformation, lighting effects, music worlds, screenspace shaders, etc.

### Describe alternatives you've considered

Simply using built-in shaders.

**Comment by ProbablePrime** [comment]
Thank you for making this request.

Custom shaders is a feature that we do plan for in the future, however it is unlikely to support Poiyomi or other Unity based shaders. This is due to our decision in graphical engines/renderers which would not support these.

Custom shaders instead would be created and constructed using ProtoFlux nodes in a similar way to the node based rendering settings of a blender scene.

Details are sparse as we haven't fully planned this feature due to existing pre-requisites. So this comment is more to set expectations.

**Comment by Frooxius** [comment]
I've created official issue with more context, closing this one in favor of our official one: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/632
