### ISSUE TITLE
Ability to download an older version of resonite

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#3205]
### Is your feature request related to a problem? Please describe.

 Basically ability to get a older resonite version to be able to use features that older versions had etc

### Describe the solution you'd like

Ability to download different resonite versions 

### Describe alternatives you've considered

Asking someone who hasn't played resonite in a while if they have a certain version and send files of that Version 

### Additional Context

Versions

**Comment by JackTheFoxOtter** [comment]
I assume this will be easier to do once #1212 is implemented. For the time being you should be able to download older builds using Steam's CLI. My question is just - why do you want to do that? You would have to be very careful to not corrupt any content you've saved with a newer version, if you go back too far you probably wouldn't even be able to properly log into the cloud anymore.

Generally Resonite is pretty future proof with stuff, so any features that used to work on an older build should still work on a newer build. (The only instances of actually removed functionality without a replacement I can recall was pretty much purely only stuff that never worked properly in the first place).

If you find something that used to work, but doesn't work anymore, I suggest creating a separate issue for that, since that should get addressed.

**Comment by Frooxius** [comment]
This will be implicitly handled by https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1212

The whole point of the versioning and update system is to be able to switch builds easily. 

Closing this one as duplicate.
