### ISSUE TITLE
OnSaving+Proxy triggers under non-persistent slots

### ISSUE THREAD

**Issue by Krzeszny** [Yellow-Dog-Man/Resonite-Issues#3228]
### Describe the bug?

If you have an OnSaving node under a non-persistent slot, it'll still trigger when anyone saves the world (or the slot), even if the slot itself isn't actually being saved to anyone's inventory.

Example: OnSaving nodes on an _equipped_ avatar trigger when the world is saved despite nothing actually saving the avatar.

### To Reproduce

Use the example provided and save the world (touch the object to unpack its Flux): https://dl.dropboxusercontent.com/scl/fi/up2wkgmnnyxg6lqedze7e/Overengineered-OnSaving-Box.resonitepackage?rlkey=1272c0ie8ibcje3wsjgjmn93k&dl=0

Or just have an OnSaving node on your equipped avatar and save the world

### Expected behavior

OnSaving only triggers under persistent slots because non-persistent ones aren't saved anyway

### Screenshots

https://github.com/user-attachments/assets/cedfe2b4-524b-4ee9-ac58-b661ce5a2556

### Resonite Version Number

2024.11.19.479

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Reverb G2 V2

### Log Files

It's not an exception so n/a?

### Additional Context

Affected example:
You can place an OnSaving function on your avatar that you'd like to trigger when you save it, but it'll also trigger whenever anyone saves the world. A workaround could be making it only trigger save if the local user is the owner.

### Reporters

novafox21, krzeszny

**Comment by JackTheFoxOtter** [comment]
I mean, I'd think this is expected. You still trigger the save event, I wouldn't expect that to not get fired if the slot is non-persistent.

**Comment by shiftyscales** [comment]
@Krzeszny - Is the provided screenshot / Flux representative of your actual use-case / Flux? What are you trying to accomplish on your avatar, exactly?

I'm trying to interpret / understand what you could be doing with that Flux- seeing your actual setup on your avatar / hearing how you're using it would help when making suggestions for how your issue could be resolved.

**Comment by Krzeszny** [comment]
> [@Krzeszny](https://github.com/Krzeszny) - Is the provided screenshot / Flux representative of your actual use-case / Flux? What are you trying to accomplish on your avatar, exactly?
No, it's just an example

> I'm trying to interpret / understand what you could be doing with that Flux- seeing your actual setup on your avatar / hearing how you're using it would help when making suggestions for how your issue could be resolved.

I have two use cases:
1. Let's say I want to have a system that incrementally changes the name of an item every time I save it manually. I can use WorldSave+Proxy to set it to non-persistent when the world gets save (currently impossible because it triggers OnSaving anyway), then return it to persistent, and when I save it to my inventory, it actually triggers the name change.
2. A system that prevents people from saving an item or avatar by making it delete itself when it's saved, that doesn't use SimpleAvatarProtection, but this system also shouldn't trigger on WorldSaved, or else every world save deletes the object.

**Comment by Dusty-Sprinkles** [comment]
> 1. I want to have a system that incrementally changes the name of an item every time I save it manually. I can use WorldSave+Proxy to set it to non-persistent and prevent world saves from triggering it (currently impossible), then return it to persistent, and when I save it to my inventory, it actually triggers the name change.

Unfortunately this one is pretty much impossible because of #1343
Molecule #1212 is the intended solution for that one

The other two probably are outside of the scope of onsaving maybe, but I also wouldn't mind the option to differentiate between a world save and saving an avatar

one thing I've personally ran into was making a system that would clear my tools and things from a toolshelf system I have on saving to prevent extra assets I'm not using from getting saved with my avatar, which means that when the world is saved I have to re-equip all of my tools

**Comment by Frooxius** [comment]
This is not a bug, it's intentional behavior.

When the saving event is sent, it is to the whole hierarchy - there might be modules or systems that need to react to saving - e.g. causing notifications, sounds and other behaviors, that aren't persistent in the world, but you still want them to react.

In some cases non-persistently marked objects also *can* be saved - e.g. when you save the root of the non-persistent object directly, it will ignore that particular non-persistence status. There's other mechanisms which will preserve non-persistent objects in certain scenarios.

By making this change we would break those systems.

We could potentially add more information to the saving event which would let you determine the scope of what's being saved. You'd have to make a new issue for this.
