### ISSUE TITLE
Make Edit Mode in the session menu the option that lets you adjust tool grip poses

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#3254]
### Is your feature request related to a problem? Please describe.

Currently activating UI Edit mode allows you to change the grip pose on tools. To me this feels inconsistent with the name and its general area of use (userspace) and I feel like it would make more sense if the Edit Mode accessed via F2 or the session menu allowed this

### Describe the solution you'd like

Make Edit Mode toggle grip pose editing instead of UI Edit mode

### Describe alternatives you've considered

continuing to tell people to enter UI edit mode to change the grip pose of their tools
adding some other option to do that other than either
dunno

### Additional Context

I feel like this would be a good  change and it makes more sense since grip poses are a "world" thing and not really a userspace thing outside of equipping a dev tool in your dash but that hardly counts

### Requesters

Venport/dustysprinkles

**Comment by shiftyscales** [comment]
Since we can easily add settings now, I think this would make more sense as a standalone setting / mode.

**Comment by Frooxius** [comment]
We're unlikely to make the specific change you're requesting. This being UI edit mode is intentional choice over Edit mode for a few reasons.

- You need builder permissions for turning on Edit mode. Meaning if you don't have those, you can't adjust the grip pose for comfort in that session. In contrast, you can *always* enable UI edit mode 
- UI edit mode lets you rearrange various elements and their placement - like facets. This conceptually fits with being able to adjust arrangement of tools on your hands too

I'm not sure this really need to be another setting - we have a shortcut for turning on UI edit mode, which allows for quick adjustments. Adding yet another one would just over-complicate things.

I don't really see the need to change this behavior.
