### ISSUE TITLE
Non-Impulse Protoflux wires are connected backwards

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#3255]
### Describe the bug?

Recently while discussing a new wire stylizing mod that had come out in the modding discord, we were talking about how the wires would be backwards for anything that wasn't an impulse. I do not have this mod so I tested it by changing the UV of wires in my world to use the impulse textures and they were also backwards.

### To Reproduce

1. Open a world
2. Spawn any node with impulses and values/objects as inputs/outputs
3. Connect it to something
4. Select the non-impulse wire and inspect it to find the UV offset field of the wire mesh and set it to zero (the same value as the impulse wire)
5. Observe the wrong-ness in the value/object wire

### Expected behavior

Wires flow in the direction of protoflux

### Screenshots

![Image](https://github.com/user-attachments/assets/24c8980d-7fdf-4db3-ba27-c08b17c05378)

![Image](https://github.com/user-attachments/assets/d251822a-eaac-4bda-97bc-065adf21f160)

### Resonite Version Number

Beta 2024.12.2.1188

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

N/A

### Additional Context

cyro told me to make this issue

### Reporters

Venport/dustysprinkles
epicEaston197

**Comment by Nytra** [comment]
I don't think this is a bug. It happens because the non-impulse wires are referencing their sources, whereas the impulse wires reference their targets. So they are actually pointing correctly to their reference targets in both cases.

**Comment by Frooxius** [comment]
Yes, this is by design.

Wires always flow from the point that is referencing to the point they reference.

For impulses, you have the "impulse source" (on the right side of the node) referencing an impulse target (on the left side of the node) - so you have the wire flowing from the right side of the node to another node on the left.

For inputs, it's the node inputs that are actually doing the referencing - the input (on the left) is referencing a node output (on the right), therefore wire flows from the left of the node towards the right side of a node.
