### ISSUE TITLE
Context Menu ItemsRoot has no effect?

### ISSUE THREAD

**Issue by Readun** [Yellow-Dog-Man/Resonite-Issues#3320]
### Describe the bug?

Trying to use the ItemsRoot under an ContextMenuSubmenu does not do what I think it should do?
At the moment we can not place the submenu on a different hirachy, it needs to have a "RootContextMenuItem" on a slot above. It cant be linked by "ItemsRoot"

Maybe I just misunderstood its function? Or is there a other specific way to accomplish this?

### To Reproduce

Have a ContextMenuSubmenu on a different hirachy or not underneath a slot with a RootContextMenuItem and reference it by ItemsRoot.

### Expected behavior

Being able to place Submenu's in different places on an Avatar / Object.
For example, to Equip an object/tool and having its Context menu show up under an Avatars existing menu.

### Screenshots

![Image](https://github.com/user-attachments/assets/d0abe93a-1cf2-4fe9-8e07-af2f6857255a)

### Resonite Version Number

BETA 2024.12.2.1188

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, VR

### Log Files

-

### Reporters

Readun, Shello

**Comment by badhaloninja** [comment]
I'm not sure I understand how you are trying to set this up


The ItemsRoot on a ContextMenuSubMenu points to a slot with ContextMenuItemSources in it's children (only the direct children if SearchWholeHierarchy is disabled)

RootContextMenuItem is not necessary at all for ContextMenuSubMenu to function, you could place the ContextMenuSubMenu component directly on a button alone and it should still function.




Here is an abstracted layout of something I actually use (I changed the labels to be tool oriented but the structure is the same)
This works in version BETA 2024.12.2.1188
![Image](https://github.com/user-attachments/assets/83ea02ba-e300-4f96-bf57-171cd5f0286c)

Here is a zipped resonitepackage of the above (It's zipped because GitHub wont let me attach resonitepackage filetype directly for whatever reason)
[Context Submenu Demo.zip](https://github.com/user-attachments/files/18050209/Context.Submenu.Demo.zip)

**Comment by Readun** [comment]
Oohhh... thank you, so I got it wrong by it is doing the reverse. ContextMenuSubmenu > ItemsRoot must be under the actual root menu and it will specify what will come next. 

Thank you very much!
Shello and I were both getting the reversed Idea of what it might do :D
