### ISSUE TITLE
Unregistered users are always forced to do the tutorial

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#3361]
### Describe the bug?

Resonite will always display the first time user prompts and force a user that's signed out to do the tutorial, no matter how many times you complete it.

### To Reproduce

Start the game while signed out.

### Expected behavior

The tutorial to only be played once.

### Resonite Version Number

2024.12.10.482

### What Platforms does this occur on?

Windows

### Log Files

[BUFU - 2024.12.10.482 - 2024-12-14 06_56_56.log](https://github.com/user-attachments/files/18135688/BUFU.-.2024.12.10.482.-.2024-12-14.06_56_56.log)
[BUFU - 2024.12.10.482 - 2024-12-14 06_52_13.log](https://github.com/user-attachments/files/18135689/BUFU.-.2024.12.10.482.-.2024-12-14.06_52_13.log)

**Comment by troyBORG** [comment]
You should be able to just add  `-SkipIntroTutorial` to the launch options and it will skip it.

**Comment by ko-tengu** [comment]
Sure, but you used to only have to do it once, logged out or not. The first time setup always runs until you register an account, which is new behavior and probably unintentional.

**Comment by Frooxius** [comment]
Nothing actually changed with this logic, there's not really "new" behavior - it's just more nuanced than you assumed it to be.

We use heuristics to determine if the user has reasonably used Resonite enough to use the tutorial - notably how many things got loaded into the database.

If heuristics determines that the user has not used Resonite enough, it'll run tutorial again. This is to handle scenarios like when users start Resonite, have some issue, so they shut it down and then run again. Or they install Resonite, launch it once to test things. Then don't play after a while and launch it again - at which point when they weren't introduced to tutorial, they'd be confused.

Since we had a number of reports of these types of scenarios happening in the past, we made the tutorial launch again if it thinks that's the case. There are some false positives, but the impact of false negatives (user who needs a tutorial not getting one) is worse, I do not intend to change this behavior.

If you really want to skip it, there's the command or you can press "F2" right at the start (enable Edit mode essentially).

**Comment by ko-tengu** [comment]
If this is intentional then I would like to switch this to a feature request then. The tutorial is entirely too slight and simple to be something that someone may be forced to do over and over again if they've not hit whatever the metric is. I made this issue after a new user in the discord running into this after spending a couple of hours failing to create stuff without an account and it driving them away.
