### ISSUE TITLE
Item Preview Preloading/Caching

### ISSUE THREAD

**Issue by AwesomeTornado** [Yellow-Dog-Man/Resonite-Issues#3404]
### Is your feature request related to a problem? Please describe.

When an inventory folder is opened for the first time, it always takes a couple seconds of waiting for all of the item icons to fully load.

Note that after the first time the folder is opened, the icons all show up instantly when the folder is re-opened. I assume that this means that the icons are already being cached, but that the cache is not saved.

### Describe the solution you'd like

I would like the icons for the items to be cached and persist across multiple startups. 

I assume that the implementation for this would be to save the cache for the icons to a file, and to load it again upon startup.

### Describe alternatives you've considered

making a mod that opens a bunch of folders when it starts, causing all of the icons to load. opening a bunch of folders manually when I first join the game.

Preloading, by having the game load all icons one or two folders beneath the current one.

### Additional Context

It would likely be infeasible to cache *all* icons in a user's inventory, as this would include all the icons in public folders, which would lead to a massive amount of data being cached. However, I hope that my suggestions of re-using a previous instances' cache or preloading icons effectively work around this issue.

### Requesters

iambadatnames_ on discord, @AwesomeTornado on GitHub

**Comment by Frooxius** [comment]
This is what already happens.

Resonite will cache the assets after they are first downloaded. However cached items still need to be decoded and loaded from the disk, which takes a bit on subsequent startups.

If you view them during the same session, it's usually the same asset that's already been loaded and hasn't been unloaded from memory yet (there's a grace period for doing so).

Since there's nothing actionable here, I'm closing this.
