### ISSUE TITLE
Full Blender Environment Implimentation

### ISSUE THREAD

**Issue by RabbitRetro** [Yellow-Dog-Man/Resonite-Issues#3422]
(Yes, I realize something along these lines is on Froox's to-do list, but this is more specific)

Using the [Blender Code Repository](https://projects.blender.org/blender/blender) , we should have a mode we can go into (a world, in fact, as is already simulated) where we can be inside the Blender application and modify & save 3D forms down to the vertex, line, and triangle level and (Including voxels.) This would include the node graphs for building shaders, composites, textures, and non-destructive geometry... and floating menus, dialogs, and maybe even the menu bar.

### Describe the solution you'd like

Blender or Blender-analogous pogram code integration into Resonite.

### Describe alternatives you've considered

Something proprietary and more simple.

### Additional Context
GitHub Blender Code: [https://github.com/blender/blender](https://github.com/blender/blender)

**Comment by Frooxius** [comment]
What you're asking for is not really possible for a number two big reasons:
- Most clearly, legal reasons. Blender is licensed under GNU, which is not compatible with the code that Resonite uses. This alone is a showstopper for something like this
- Blender is very complex application. As such embedding it into Resonite in full and having it be well integrated is fairly speaking unrealistic on technical level - they are too different separate applications, so they cannot be easily merged

There's a number of features specific to Resonite that will allow for stuff like this:
- Vertex editing - https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1233
- Mesh DSP - https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/569
- Blender SDK - https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2335

However for your specific request, we have to say no due to the reasons above, I'm sorry.

I'd recommend requesting more specific functionality you'd like to see in Resonite.
