### ISSUE TITLE
CharacterLinearVelocity ProtoFlux node outputs zero for users who are not updating the input CharacterController

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#3426]
### Describe the bug?

When trying to drive something based on a charaacter's linear velocity, the ProtoFlux node outputs zero for all users except the user updating the CharacterController

This is unexpected because the velocity of a character controller should be something that all clients can compute

(This might be some misunderstanding on my part about how the physics system works)

### To Reproduce

Use CharacterLinearVelocity ProtoFlux node and check the value it outputs for a number of different users

### Expected behavior

Value is synced for all users

### Screenshots

![Image](https://github.com/user-attachments/assets/b97b585c-0432-408c-b8c3-698cd57c497c)

### Resonite Version Number

Beta 2024.12.18.477

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[DESKTOP-H976HO2 - 2024.12.18.477 - 2024-12-25 00_59_00.log](https://github.com/user-attachments/files/18242428/DESKTOP-H976HO2.-.2024.12.18.477.-.2024-12-25.00_59_00.log)

[DESKTOP-H976HO2 - 2024.12.18.477 - 2024-12-25 00_57_35.log](https://github.com/user-attachments/files/18242431/DESKTOP-H976HO2.-.2024.12.18.477.-.2024-12-25.00_57_35.log)

### Additional Context

N/a

### Reporters

Nytra

**Comment by Frooxius** [comment]
This is not a bug. 

Any locally simulated physics entities and other mechanisms can have their values accessed only by the simulating user - these values simply don't exist on other users.

This is how the physics system works. 

Once we have full rigidbody simulation, this will allow for more shared simulations, but the character one is designed to work specifically for particular user controlling it.

**Comment by Nytra** [comment]
Could it fallback to computing the velocity of the slot? The node outputting zero is quite inconvenient imo.

**Comment by Frooxius** [comment]
That will not be accurate and would require some hacky mechanisms. Slots do not have any velocity associated with them. It would need to track how it moves and then run some algorithm.

But those tend to provide very jittery outputs, because the update rate changes a fair bit, which doesn't give very useful values.

Overall it would be detrimental to include this - users relying on this could spend time trying to make things work with the inaccurate values, only to find out that it doesn't work and other parts of the system won't work either (this is not the only one that you need to use on the simulating user end).

It being zero will immediately tell users that they can't use this like this - you generally need to rethink/restructure your logic to be built around how the physics simulation works.
