### ISSUE TITLE
Releasing the Protoflux binding generator for plugins

### ISSUE THREAD

**Issue by moonheart08** [Yellow-Dog-Man/Resonite-Issues#37]
### Is your feature request related to a problem? Please describe.

At this time, plugin developers intendng to add new nodes must write the FrooxEngine bindings manually. This is, naturally, Not Very Fun, especially as the game's own bindings were clearly source generated.

### Describe the solution you'd like

Ideally, releasing a dll for Rosyln (or equivalent) that can sourcegen protoflux bindings, to allow plugin authors to focus on writing their plugin.

### Describe alternatives you've considered

Auto-generating the bindings at runtime ala Weaver is an option, though imo not ideal. A third party could also produce their own generator, but that's also not ideal for potentially "upstreaming" third party nodes into the game officially, as there will likely be API differences that make porting nontrivial.

**Comment by Xlinka** [comment]
Following this issue as it related to my creation of plugins with my plugin Obsidian.
As writing the bindings manually each time is annoying but we could make our own community made binding generator using a source generator but this will lead to feature parity issues.

**Comment by Xlinka** [comment]
Current solution ![image-62.png](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/22996716/3c0ed922-5bab-482e-87d4-0dafdf4a4aa1)

Do it all manually with blood sweat and tears XD

**Comment by hamishgavinmacdougall** [comment]
Hi, just want to chime in with support for this enhancement :)
We are struggling with this binding issue for a number of research projects:

1) A project on diagnosing Essential Tremor (a movement disorder like Parkinson's) where we are looking for the best measures among over 300 channels of VR data that distinguish between patients and normal subjects (movement of the head hands, body, eyes, face etc.).
This project needs a plugin to record raw accelerometer and gyroscope data from headsets, controllers and trackers since that’s the data traditionally evaluated in movement disorders: 

2) A project to evaluate the use of VR head and eye tracking in the diagnosis of various conditions in: Neurology, Ophthalmology, Vestibular (balance) function etc. Lack of access to specialists means that many patients go undiagnosed for years, especially in remote and rural locations where VR telemedicine could help.
This project needs a Varjo Eye Tracking plugin since native support has apparently been deprioritized.

3) A project with cancer patients receiving immunotherapy which aims to teach them about their immune system, how the therapy works, and why it is important to contact their oncologist whenever one of many potential side effects occurs. This project needs a plugin to record avatar performances (body, eyes, face etc.) so that healthcare people can explain conditions, demonstrate therapies, etc.

**Comment by Frooxius** [comment]
We could bundle the tool for this, but it will need a little bit more work to wrap it a bit, since it's integrated into the build process.

The way this works right now is it's a command-line tool, that scans all the libraries and generates binding source files for another project, that then needs to be compiled.

We could release it mostly as is and just bundle it with the client with minimal documentation, so you'd have to integrate it into your pipeline yourself. This would be the quickest way to approach this.

We originally attempted to implement it as a Source Generator module, but this ran into a number of issues due to its limitations. We'd like to revisit it, but it'll take some time.

**Comment by Xlinka** [comment]
i wouldn't mind integrating this as our own tooling on my project if possible. or attempt to try the source generator route. 
but that's on dependability if you release the code.

**Comment by Frooxius** [comment]
Source generator would make this take considerably longer, because we'd have to rework our solution for that.

Simplest and quickest thing is to just release the command-line utility that generates the binding source files.

**Comment by art0007i** [comment]
I think the command line one is perfectly acceptable. just so we have something work with at all

**Comment by Banane9** [comment]
> We originally attempted to implement it as a Source Generator module, but this ran into a number of issues due to its limitations. We'd like to revisit it, but it'll take some time.

I feel your pain, I tried to make a "simple" source generator to add some properties too... every little bit seems ultra complicated with no useful helpers :C

**Comment by Xlinka** [comment]
yeah honestly the console command line utility is better than me typing them manually.

**Comment by Frooxius** [comment]
> > We originally attempted to implement it as a Source Generator module, but this ran into a number of issues due to its limitations. We'd like to revisit it, but it'll take some time.
> 
> I feel your pain, I tried to make a "simple" source generator to add some properties too... every little bit seems ultra complicated with no useful helpers :C

The main thing that I remember that I hit was some weirdness when processing data in assemblies other than the one that's compiled (which was needed to reference some stuff that was done across them), it would behave very weirdly. Like it would get weird errors, trying to treat them as .NET Standard or something, while they were not and it would freak out over some missing types.

I don't quite remember what it was exactly, just that it was combination of the tooling feeling too unpolished and difficult to debug too.

**Comment by Banane9** [comment]
> The main thing that I remember that I hit was some weirdness when processing data in assemblies other than the one that's compiled (which was needed to reference some stuff that was done across them), it would behave very weirdly. Like it would get weird errors, trying to treat them as .NET Standard or something, while they were not and it would freak out over some missing types.

Ah yes, I remember that too - ironically also for loading FrooxEngine dlls. "Reflection only" loading should prevent complaints about the runtime though 🤔 


> I don't quite remember what it was exactly, just that it was combination of the tooling feeling too unpolished and difficult to debug too.

Oh yea, debugging _mods_ feels nicer than trying to debug source generators. What annoyed me the most was definitely that even just putting something in the same namespace as another class required one to manually build up the name from the chained definitions. Let alone recreating the class signature with what it inherits and implements - considering partial classes seem to be the main intention of adding code to a class with source generator, having these key elements not be easily done seems like an incredible oversight.

**Comment by Xlinka** [comment]
So if the console program becomes avaliable to use will it be published under its own repo on the organisation?

**Comment by Frooxius** [comment]
@Banane9 I don't think that helped. But it's been over a year ago now, so I don't remember the details.

@Xlinka No, we'd just bundle the .exe with the build right now so you could fetch it from there.

**Comment by Frooxius** [comment]
The tool has been released in 2024.3.1.1178!

Include ProtofluxBindingGenetator with the builds (requested by moonheart08, @xLinka | Plugin Bird, @SHFR_H, @art0007i, @Banane9, issue #37)
-- Note that we are providing this tool AS IS and we will provide NO SUPPORT for this tool (the only exceptions we might make is if it's not usable at all, but generally making this part of your modding pipeline is on modders)
-- This can be found under the "Tools" folder on the Steam distribution
-- This will generate C# source files that provide bindings to ProtoFlux nodes, which can be useful for mods
-- The first argument is path where the bindings should be generated into
-- Other arguments are paths to assemblies that the bindings should be generated for
