### ISSUE TITLE
Missing issue types compared to legacy issue tracker

### ISSUE THREAD

**Issue by Banane9** [Yellow-Dog-Man/Resonite-Issues#455]
### Is your feature request related to a problem? Please describe.

I wanted to create an issue asking for clarification on policy, however there's no issue template cut out for it.

### Describe the solution you'd like

Add the issue templates missing compared to the legacy issue tracker:
* Documentation or Information Request
* Discussion / General Feedback
* (optional) Tweak (I'm fine with that being under Feature Request, though perhaps add it as an example to the description of the template)

### Describe alternatives you've considered

Use other templates for issues that aren't ostensibly covered by them.

### Additional Context

Legacy Issue Templates
![legacy issue creation screen](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/bb40ac9a-db22-4598-86e3-5a7ce5a23986)

Current Issue Templates
![current issue creation screen](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/2d7f3374-e06c-46f0-89eb-4c756ea782ce)

**Comment by ProbablePrime** [comment]
We're working on keeping some items simpler this time. So we're starting with less templates for now, we're constantly evaluating our processes and trying to figure out how to optimize it. Due to this we have no plans to copy and paste workflows from other projects.

And due to this we'll be closing this issue. Thank you
