### ISSUE TITLE
Easier Access to the Issue Tracker (Link on Resonite.com among other places)

### ISSUE THREAD

**Issue by Azavit** [Yellow-Dog-Man/Resonite-Issues#459]
### Is your feature request related to a problem? Please describe.

Right now finding the GitHub issue tracker can be a nuisance, having to go to YDM github then going to the issue tracker.  This can often be a slowdown of actually reporting issues not having the issue tracker in the same places where people access other YDMS/Resonite information.  Often times I end up searching for a "Resonite Github" rather than the Yellow Dog Man Studios Github.

### Describe the solution you'd like

One of the easiest solutions is to add it to the resonite.com website, but having it in all other places where links to moderation/support help shows up wouldn't go amiss.

### Describe alternatives you've considered

When the Wiki is officially released this won't be as much of an issue but honestly having a link to the bug reporting location where ever other support is listed should be done anyways as all support links should be found together.

**Comment by FlameSoulis** [comment]
A larger issue honestly is that you need a separate account to vote or discuss an issue on GitHub. Unfortunately, it's just one of those "damned if you do, damned if you don't" situations, because many people will herald that the Issue Tracker is robust and means that developers don't have to make their own solutions.

I get that may be a seperate issue of its own, but I could see people getting confused going from Resonite's domain to suddenly not Resonite's domain for issue tracking.

**Comment by ProbablePrime** [comment]
We've increased the links to this location in multiple areas. Closing.
