### ISSUE TITLE
item tagging and hiding like in cvr

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#46]
### Is your feature request related to a problem? Please describe.

this is really nice people can then select what effects they see from items ie if an item got explosion effect itll be tagged explosion/flashing and then users can chose to enable disable items that have certain tags so for explosion they wont see the effect or sound or flashing also make it so the tags are connected to what component is added so when people try to remove the tag to circumvent the tagging system that it also removes the component of the effect basically the component cant exist without the tag

### Describe the solution you'd like

a system like this to be intergrated

### Describe alternatives you've considered

not yet but i thought it was a good idea

**Comment by Dusty-Sprinkles** [comment]
by using the power of the search bar I found this post was already made, so I'll just add my thoughts that aren't specifically stated to it here

I think a few ways this could be done would either be
- Users are allowed to tag items on upload and the community can add additional tags with some sort of consensus-based thing
- Problematic items are given specific danger tags if they're reported (could maybe be slower)

There would be some concern with someone just uploading a new copy (like even if there were tags someone could potentially just use a tagged item to make a replica without tags) of a previously marked item but I'm not sure how much of a concern that is, maybe if enough players were interested there could be some kind of confirmed-safe item database so that players can spawn toys and such out without giving permission for all the possibilities

Or I suppose it could be made that an item has to have been verified that its tags are accurate before adding to a general item availability permission thing, which would mostly work I think

Also I'd like personally if the first option was picked for the list of tags to be available in case it expanded to helpful categories/etc (this would also probably help with good content being easier to share around)

**Comment by Geenz** [comment]
This would be something addressed by the eventual Content Tagging system.  I'll stand up an issue for that.

**Comment by Geenz** [comment]
Stood up #1564.  Closing this in favor of that.
