### ISSUE TITLE
[Headless] Sometimes two UndoManagers are created in the world

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#490]
### Describe the bug?

Sometimes when you start a headless session and the first user joins the session, two Undo Manager slots can be found in the world. Both slots contain a UndoManager component but only one of them works as far as I can tell. Also the first joining user will not be able to properly use undo until they respawn.

One of the UndoManagers is attached by the headless host, the other is attached by the first joining user. I think something in the joining user's client is creating the second UndoManager in the world.

### To Reproduce

This is not something that can be consistently replicated. I would say it happens 50% of the time. Maybe less.

1) Start a headless session.
2) Join it.
3) Sometimes there will be two UndoManagers.

### Expected behavior

Only one UndoManager is created in the world.

### Screenshots

![2023-10-31 04 37 16](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/04211b45-b1b1-4390-b9ed-481a51949ee2)

![2023-10-31 04 37 46](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/b2c70e9d-eaaf-4f52-b996-7010033324cb)

### Resonite Version Number

Beta 2023.10.20.831

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Valve Index, Desktop

### Log Files

Headless log file:
[DESKTOP-H976HO2 - 2023.10.20.831 - 2023-10-31 04_33_30.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13212079/DESKTOP-H976HO2.-.2023.10.20.831.-.2023-10-31.04_33_30.log)

Client log file:
[DESKTOP-H976HO2 - 2023.10.20.831 - 2023-10-31 01_12_15.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13212081/DESKTOP-H976HO2.-.2023.10.20.831.-.2023-10-31.01_12_15.log)

### Additional Context

N/a

### Reporters

Nytra (Discord: nytra)

**Comment by ProbablePrime** [comment]
Took a brief look.

UndoManager is mostly accessed through a helper method that's designed to ensure that only one exists. That helper method scans the hierarchy looking for an existing UndoManager.

Due to this, and the "sometimes" here I think we're probably looking at some form of race condition. 

Getting any way to increase the likelihood of this happening would help tremendously.

**Comment by PJB3005** [comment]
> but the child slots created by it are marked persistent- that seems a bit backwards.

Doesn't making a parent slot non-persistent apply to all descendants too, regardless of whether they are marked persistent themselves or not?

**Comment by ProbablePrime** [comment]
The persistence setup is fine, with the top level (Undo Manager) not being persistent the created undo steps are not saved.

Let's focus on the duplicate undo managers to which I'll have another look.

**Comment by ProbablePrime** [comment]
In cases where two undo managers exist, could you check the contents of the Root slot for an additional undomanager?

**Comment by Nytra** [comment]
Not sure what you meant by this exactly, but I had a case with two UndoManagers, then I checked the components on the Root slot and found no UndoManager in there. Using a find child by name it could only find the two "Undo Manager" slots that were direct children of the Root slot.

**Comment by Nytra** [comment]
Oh there is something weird happening here though.

I have loaded up a headless and in this case there is only one UndoManager visible in the Root slot through the inspector, and it has no children.

However I have managed to get a reference to a second one (using find child by name) which has children and seems to be the one which is actively in use by me, although it does not appear to be visible in the Root slot. It is somehow hidden.

![2024-03-12 07 31 04](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/e3ac6a5d-1e27-411c-b744-e45b2c4aabb0)

**Comment by Frooxius** [comment]
Merged this fix in 2024.3.12.1169, thanks!

**Comment by Nytra** [comment]
I don't think this is fixed. It actually seems to happen much more consistently now, like every single time you join a headless session.

Logs:

[graphical client - DESKTOP-H976HO2 - 2024.3.12.1169 - 2024-03-12 19_57_23.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14578057/graphical.client.-.DESKTOP-H976HO2.-.2024.3.12.1169.-.2024-03-12.19_57_23.log)

[headless client - DESKTOP-H976HO2 - 2024.3.12.1169 - 2024-03-12 19_59_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14578058/headless.client.-.DESKTOP-H976HO2.-.2024.3.12.1169.-.2024-03-12.19_59_36.log)

**Comment by ProbablePrime** [comment]
Thanks for the Fresh logs, this will be a lot easier to work on with the other bug out of the way.

**Comment by ProbablePrime** [comment]
@Nytra Are you able to reproduce this without a headless?

**Comment by ProbablePrime** [comment]
Remember to read part 1: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/490#issuecomment-1980083328

So apparently exactly 6 hours ago I started working on this again as my first step was to figure out why this only appeared to happen on a headless.

I can't seem to keep a stable headless setup on my main development machine, mostly because of the cruft that accumulates when you're building and managing multiple versions of Resonite. It's always broken when I go to use it.

So, because I was frustrated I wrote:
- https://wiki.resonite.com/Headless_Client/Docker
- https://github.com/Yellow-Dog-Man/BasicDockerHeadlessSetup
- https://wiki.resonite.com/Headless_Client/Example_Configurations#Minimal_with_Builder/Admin_Permissions

and then followed my own guidance on those pages to run a headless.

With that operational I got back to the actual bug, I just added a logging line that prints the stack trace everytime something tries to get the Undo Manager in the world, then joined the headless. Boom 2 Undo Managers first time. But in my haste to check if there were two undo managers I realized I had .... while the world was loading.... equipped a tool. Equipping a tool is an undo-able operation, that requires.... the undo manager.

So my thoughts go to a race condition. I'm trying to register the undo manager because I'm equipping the tool and then something in the headless is then register the undo manager later. If they conflict or fight somehow in a race condition manner then there's your issue 2 Undo Managers:

So then I get to thinking why doesn't this bug occur with Regular User based sessions. Looking at the same logfile, I notice that one of the first things an avatar does is to setup its InteractionHandler, which requires getting the undo manager:
```
03:31:01.310 (  0 FPS)	Get Undo manager, True

  at System.Environment.get_StackTrace () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
  at Elements.Core.UniLog.Log (System.String message, System.Boolean stackTrace) [0x00000] in <ebcf2cba0793432d9877a63b284d682f>:0 
  at FrooxEngine.Undo.UndoManagerExtensions.GetUndoManager (FrooxEngine.World world, System.Boolean addNew) [0x00000] in <add1221686e04bed8d7d9df3072b0daf>:0 
  at FrooxEngine.InteractionHandler.OnStart () [0x00000] in <add1221686e04bed8d7d9df3072b0daf>:0 
```

And as headless users, in addition to not having heads, do not also have hands, it means they don't have InteractionHandlers. 

So in summary, as to why this only works on headless sessions:
- Regular Sessions at Startup: 2 Hands, 0 Heads
- Headless Sessions at Startup: 0 Hands, 0 Heads

But, why does the interaction handler need the UndoManager? 

So it can attach button event handlers... toooo the context menus!!
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/76aa0be2-4b52-449c-a76c-291f9e7fdd20)


And guess what headless users don't have... Context Menus!

Anyway, I'm going to see what I can do just make part of the world setup include an undo manager. It'll basically be:
```
Headless OnStart {
GetTheUndoManager 
}
```
That way an undo manager will exist before a regular user can join.

It looks like the code was originally added to only setup an undo manager when the system was used in some way. This would make static worlds like the Meta Movie project world NOT load undo managers. But as everyone has those context menu items it makes sense to make this component always exist.

**Comment by JackTheFoxOtter** [comment]
> With the settings rework and Headless Configuration files, in worlds that don't change we can probably expose a setting or configuration thingy to turn off the undo manager if needed.

This would be a very appreciated feature coming out of this rabbit hole. (Was interesting to follow you dig into this though!). There are situations, especially for game worlds, where the Undo Manager isn't really wanted, and its precense requires engineering solutions around it to ensure players can't break the game using undo / redo. There is #284 and #285 which are related to customizing undo functionality. (I'm aware these are for disabling undo functionality and not the entire undo manager, but I wanted to link them anyway as they likely touch similar systems).

**Comment by ProbablePrime** [comment]
Ok jumped back on this to take a look. 

Did some changes and.... now there are 3 Undo Managers in the world :D

**Comment by Banane9** [comment]
> Did some changes and.... now there are 3 Undo Managers in the world :D

Perfect, now just do the exact opposite of those changes and this should be fixed 😁

**Comment by Redd56** [comment]
update: my world had 3 as well, truely a sight to behold!
i dont know how. and i forgot to document it other than seeing it 💀
