### ISSUE TITLE
AudioReverbZone Applies To UI Sounds

### ISSUE THREAD

**Issue by Ruikio** [Yellow-Dog-Man/Resonite-Issues#51]
### Describe the bug?

Currently, the game has the UI dash sounds react to reverbs in worlds.

### To Reproduce

Bring a reverb component into a world.
Produce a sound in userspace, e.g. muting/unmuting yourself, or get a notification (Like a message for example.)

### Expected behavior

UI sounds should be excluded from reverb.

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

HTC Vive Pro Eye, Valve Index

### Reporters

Rukio

**Comment by Ruikio** [comment]
> I understand you might be frustrated with this issue, but as per our [best practices](https://github.com/Yellow-Dog-Man/Resonite-Issues#best-practices-for-bug-reporting):
> 
> > Use objective, and respectful language for any posts/comments submitted (negativity, hateful/angry issues/comments are liable to be edited or removed)
> 
> With that in mind, I have edited the language in your issue. Please keep this in mind in future, @Ruikio.

I'm sorry, what language was passive aggressive? Since the post was edited, I can't really reflect on what issue was there. If I recall, I think I mentioned the issue being a single button press as it's the ignore reverb zone?

If that is the case, I feel that is up to interpretation and my direct messages are open for clarity. I'll gladly voice the intent if need be. @shiftyscales

**Comment by Frooxius** [comment]
I've looked into this, I found a number of UI sound effects that do not ignore reverb, but notifications were already excluded. I tested it on my end and they do not seem to be affected, so I'm a bit confused why they seem to be affected on your end.

I've fixed a number of other places and pushed in 2023.10.17.464. If they are still affected, then reopen and we can have a look.

Also just to commend on the other things:
- For "issue being a single button press", please avoid comments like that. I can tell you that this issue was not a single button press, they rarely are. Saying stuff like that can be a bit demoralizing, as it oversimplifies the amount of work we actually have to do
- Even for issues that are simple and quick enough - sometimes we have dozens or even hundreds of those, which adds up. While any individual issue can be small and quick to tackle, if there are lots of them, we won't be able to do all of them, not at once. Things slip through. Comments like that don't help either - look at it from our perspective: If there's thousands of different buttons and thousands of requests to press this or that button - you won't be able to press them all in time and having someone be unhappy that particular button didn't get pressed and not understanding all the other buttons we're looking at (not even mentioning bigger complex issues) can get a bit frustrating.

We understand not getting issues fixed is also frustrating, but the best approach is to make work be as smooth as possible for us (e.g. following the submission guidelines), so we can tackle as much as we can - adding more frustration on our end is just going to make things run slower.
