### ISSUE TITLE
Hand tracking support like guestures and movement

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#519]
### Is your feature request related to a problem? Please describe.

Basically so you can use hand tracking instead of controller for ui and everything because the quest pro controller has short battery so would be handy to be able to use thehand tracking for moving and using the ui and grabbing 

### Describe the solution you'd like

Hand tracking

### Describe alternatives you've considered

Mod

**Comment by ProbablePrime** [comment]
Thank you for your issue Alex,

This issue is too broad to really handle.

I see:
- https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/49
- https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/8
- https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/42

Which are probably suitable components. However due to the vagueness I'll be closing this.
