### ISSUE TITLE
Default Cloud Home coliders and locomotion modules are not set properly

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#524]
### Describe the bug?

The building blocks of the Cloud Home have two sets of colliders each:
- one set is raycastable (mesh colliders, for precise laser positioning)
- the other set is not raycastable, but is a CharacterCollider (prim and convex hull colliders, for locomotion)

The issue is, as the locomotion colliders are not raycastable, if you switch locomotion outside of the spawn pad, the new locomotion module wouldn't initialise because there are no raycastable CharacterColliders below.

### To Reproduce

- spawn in a fresh CloudHome, by default you'd be in Walk/Run locomotion mode
- walk off the spawn pad, for example go inside the main room
- switch your locomotion to Fly
- observe that you are unable to move
- switch back to Walk/Run, go to the spawn pad and switch to Fly there
- observe that the Fly locomotion was able to initialise there and you are able to move now

### Expected behavior

Switching locomotion in any part of the Cloud Home should not lock you up.

### Reporters

Shadow Panther

**Comment by Banane9** [comment]
On another note, it may be worth a performance test to see at which point many simple collider become more costly than one more complex one 🤔

**Comment by RyuviTheViali** [comment]
This is a tricky issue to address. We have two sets of colliders on the models to allow for users to change the materials/colors of the modular set items while only needing to collide with more optimized colliders (versus a higher-poly mesh collider).

If just the basic colliders were present, then the materials of the modular pieces could not easily be changed. If just the mesh colliders are present, then there would be a greater performance hit due to the nature of mesh colliders.

We could very well change the models to not have mesh colliders (and enable raycasts on the simple colliders), however that would be removing a feature from the pieces.

**Comment by shadowpanther** [comment]
@RyuviTheViali You could also set the initialisation root for the locomotion modules properly… 
That way the locomotion would initialise when the spawn collider loads.

**Comment by RyuviTheViali** [comment]
I have adjusted how the locomotion options in the Cloud Home initialize, setting the max initialize time to 15 seconds. This ensures that no matter what, after 15 seconds, the physical locomotion options will initialize and you'll be able to move around like normal.

As for the object colliders themselves, there is currently no method to keep our current feature set with the models while enabling raycasts on the simple colliders and/or removing the (non-collision) mesh collider, so these are being kept as-is.

Closing this though, thanks!
