### ISSUE TITLE
Dev Tip Does Not Switch to Global Orientation

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#53]
### Describe the bug?

Currently the developer tooltip contains two modes, one for editing global orientation of an object, and another for local orientation, however only the local orientation seems to work currently.

### To Reproduce

* Equip a default developer tool tip
* Create a Cube object and rotate it off axis from the world axis
* Open the menu to change transform orientation mode from Local to Global

### Expected behavior

The global transform mode should switch gizmos to global orientation.

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows, Linux

**Comment by Gawdl3y** [comment]
Here's a very short demonstration of the problem.
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/279900/c5985557-cc96-4347-8d14-bd58d1dd939e

Switching to "global space" in the gizmo options doesn't seem to change anything at all. I would expect it to reorient the gizmos so that translation, rotation, etc. are done along the world's axes rather than the selected object's current local ones.

**Comment by Banane9** [comment]
Funnily enough, I just stumbled upon this bug too while porting [Bounded UIX](https://github.com/Banane9/ResoniteBoundedUIX) to Resonite.

The bug appears because the ContextMenu created by the DevTool (in `DevTool.OpenGizmoOptions()`) directly toggles `SlotGizmo.IsLocalSpace`, rather than using `SlotGizmo.SwitchSpace()` which handles actually telling the translation and rotation gizmos about the change.

To fix this, either make the context menu item call `SwitchSpace()` again, or hook up the following event handler in `SlotGizmo.Setup()` and remove the toggle inside `SwitchSpace()` (as I've done in my mod): `IsLocalSpace.OnValueChange += field => SwitchSpace();`

**Comment by Frooxius** [comment]
Fixed in 2023.10.18.449, thanks!
