### ISSUE TITLE
Allow HandPoser component to simulate missing bones in hand armatures

### ISSUE THREAD

**Issue by Beethoven-n** [Yellow-Dog-Man/Resonite-Issues#624]
### Is your feature request related to a problem? Please describe.

Lately I've been getting into learning ASL, and its VR counterpart, VRSL. Turns out, if your rig only has two bones per finger, fingerspelling gets hard to do clearly, as letters like C, O, E, and S all look similar, if not the exact same.

### Describe the solution you'd like

Similarly to how dynamic bones simulate a fake final bone in the chain, the HandPoser might be able to simulate missing bones in a hand's armature, and move the mesh accordingly.

### Describe alternatives you've considered

I did attempt to add new bones to my avatar's base to flesh out the hand tracking, but I don't understand weight painting enough to make it look good.
I don't really have any options, other than just paying someone to rig up the avatar in the correct way.

### Additional Context

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652883/986616d3-483d-4cb4-bf29-914df52488c2

an example of what happens if i try to do C
"my avatar can't... c? huh? (broken C and confusion)"

**Comment by Frooxius** [comment]
You can already do this. Just add extra bones to the fingers and assign them to the HandPoser. You can also add them to the rig before import. 

I'm not quite sure what the expected result of this is though. Since the bones do not actually map to anything on the avatar, there will be no visual difference.

**Comment by Beethoven-n** [comment]
the expected result would be that the extra bones _do_ map to the avatar is the thing. i'm unsure the best way to do automated weight painting, if i did then i'd probably have already done it

**Comment by Frooxius** [comment]
Unfortunately that is not something we can do on our end or with this component - that's up to the author of the avatar or whoever else can modify the avatar model.

You'll have to bring the model to Blender and add additional bones and weight paint them there.

Automated bone addition and weight painting that would work with arbitrary avatars is a very complex solution and I don't think there even is existing solution for that nor it is something we'd attempt to solve by ourselves. This is typically something done by 3D artist, rather than software.

**Comment by Beethoven-n** [comment]
alright, i'll see if i can just git gud then
