### ISSUE TITLE
Double precision world position

### ISSUE THREAD

**Issue by TheJebForge** [Yellow-Dog-Man/Resonite-Issues#664]
### Is your feature request related to a problem? Please describe.

Big worlds are almost impossible to create without using clever tricks due to world position using single precision floating point numbers. Even 1000 units away from the world origin causes the effects of precision errors to start to appear (ie. Dash clipping, hands shaking weirdly)

### Describe the solution you'd like

Increase position precision to Double, or maybe decouple client's origin from the absolute world origin somehow

### Describe alternatives you've considered

Splitting the big worlds into regions with transitions/teleportations in between, but that won't work for everything

**Comment by Cometstreak** [comment]
Hopefully this can also help with issues of small size
Where everything starts getting weird and blocky

**Comment by TheJebForge** [comment]
> Hopefully this can also help with issues of small size Where everything starts getting weird and blocky

I mean it most definitely will help with that, double precision means more precision for big and small

**Comment by marsmaantje** [comment]
Related to #121?

**Comment by Frooxius** [comment]
We will not make this specific change, since it would require propagating through many systems (e.g. physics system) and would result in overall performance penalty, even when building smaller worlds.

It's too big performance impact for particular types of worlds. You double your cache/memory bandwidth. You fit half as much into your registers. Floating point operations are more costly to do. If you propagate it to GPU rendering, it can take twice as much performance, as GPU's are optimized for single precision floating points mostly (or even less than that).

Building large worlds will be addressed through systems to split the world into chunks and partition them out. This would allow to create worlds that go even beyond the limits of doubles: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/121
