### ISSUE TITLE
Parent Slot Doesn't Update When Input is Slot Input

### ISSUE THREAD

**Issue by Enverex** [Yellow-Dog-Man/Resonite-Issues#671]
### Describe the bug?

Ran into a confusing issue earlier wherein a "Parent Slot" node wasn't updating. Turns out the issue was because I was using a Slot Input:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/958670/3cc5debd-7e05-42be-a50e-1100e0bcd2ff)

To get this to update, I would have to break the connection and reconnect that Slot Input node.

In comparison, using a reference to the same slot works fine and updates as the chunk of Flux is moved around.

### To Reproduce

See above image for example case.

### Expected behavior

For the Parent Slot node to update as it does in other scenarios.

### Resonite Version Number

2023.11.13

### What Platforms does this occur on?

Windows

### Log Files

N/A.

**Comment by Frooxius** [comment]
This is issue with ParentSlot node - it doesn't really know when the parent changes - we'll mark it as continuously updating, since its output can change unpredictably at any time.

This will however require the node to cause updates to occur every frame. Generally I'd recommend structuring the logic to use impulses and only do the update when needed.

**Comment by Enverex** [comment]
If the issue is with Parent Slot (and not Slot Input itself) then why does using a ref as the input as opposed to a Slot input work? Does changing the input node inherently change how Parent Slot works?

e.g. this works fine:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/958670/3409ff47-aa94-475f-8b36-8ee5b638d08d)

**Comment by Frooxius** [comment]
@Enverex It's because you're linking directly into the ref, so the node can listen on when that reference updates. However this requires you to bind it to specific ref of the specific Slot.

The GetParent node is more generic - it can accept any Slot and dynamically look up its parent. However because of that dynamic nature, it cannot hook into events, because it does not know in advance what will you give it.

I've marked the node as continuous in 2023.11.15.1100, which should force the updates automatically.
