### ISSUE TITLE
Putting a GrabBlock component on a parent slot of a grabbable object does not block grabbing that object

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#688]
### Describe the bug?

If you spawn a grabbable object and attach a GrabBlock component (Transform->Tagging->GrabBlock) to a parent slot of that object, it will not block the grab of the grabbable object.

It will however prevent the cursor from turning red when you aim at the object, which suggests that this is a bug and not an intended behavior.

### To Reproduce

1) Spawn a grabbable object
2) Attach the GrabBlock component to a parent slot of the grabbable object
3) Observe that you can still grab the object however the cursor will not turn red like it normally does.

### Expected behavior

The object will not be grabbable.

### Screenshots

![2023-11-15 02 44 00](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/5ff3ed58-ea75-4443-af2b-65a4b6dc9128)

### Resonite Version Number

Beta 2023.11.13.1343

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[DESKTOP-H976HO2 - 2023.11.13.1343 - 2023-11-15 02_34_13.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13359404/DESKTOP-H976HO2.-.2023.11.13.1343.-.2023-11-15.02_34_13.log)

### Additional Context

N/a

### Reporters

Nytra (Discord: nytra)

**Comment by Frooxius** [comment]
This is expected behavior and how the component is designed to work. It is meant to intercept search from a collider to the grabbable parent, so it needs to be placed in the middle. 

The main goal is to block grabbing coming from certain parts of the hierarchy. The goal isn't to disable grabbing altogether - if you want to do that, I recommend adding a mechanism to disable the grabbable component. 

If you look at the flip side of this too - if it behaved this way, placing the component at the Root slot would make everything in the world non-grabbable.

**Comment by Nytra** [comment]
That's fine. There is still a bug here though with the color of the cursor I think.
