### ISSUE TITLE
Allow /ShareStorageWithUser on all Tiers

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#714]
### Is your feature request related to a problem? Please describe.

I don't think we should have to pay $75 a month+ just to get access to this options.  

A group of people should be able to help out someone who needs storage by pooling it.

### Describe the solution you'd like

Allow all tiers to be able to share storage.    

### Describe alternatives you've considered

Trying to convince the stubborn person to subscribe to the Patreon.  But they don't want to be "nickel-and-dimed" or don't trust credit cards and only want to pay Cash/Check.

### Additional Context

I'm tired of hearing them complain about Sync errors due to lack of storage.

**Comment by Lorgenz** [comment]
Upon review it does seem rather arbitrary to tie what seems should be a base feature  such as sharing storage to having subscribed to a specific tier. Given  that we already are subscribing for the storage it would be nice for those of us that cannot afford that high a tier the option to share what we have.

**Comment by DanteTucker** [comment]
It’s not arbitrary at all. A lot of time and math goes into balancing all the tiers costs and benefits.

**Comment by ShrikeAlvaron** [comment]
Think of it this way: I have 100GB of storage and am only using about 10% of that, and don’t expect my usage to go up very fast into the future.  If I could share storage with people, well might as well dish out that nearly 90GB I’m not using to friends yeah?  But then if I’m giving it for free, some people may no longer need to subscribe to Patreon themselves and thus reduce the team’s income.

The storage given doesn’t scale linearly with the cost of the tiers, so this can be pretty harmful if say I gave out 5GB each to 18 people who all now don’t need to subscribe.  That’s $90 a month the team would be losing out on across all of them which could really add up if everyone could openly share storage like that.

Also I’m not sure where this idea that you “should” be able to do this comes from or that it’s a basic feature.  If your friends want storage space, they should sub themselves; higher subs being able to share it is a benefit to them, not a standard expectation for everyone.

**Comment by JackTheFoxOtter** [comment]
I honestly think the storage prices are more than fair. The free 1GB already brings you quite far, that's generally enough for a custom avatar and bunch of stuff in the home world. It's literally $1 / month for 5GB should you run out of that. The team is quite big, and I think it's in our best interest to support them in actually turning this into a long term sustainable business. There is also the issue that shared storage only stays shared until the owner lowers or cancels their pledge, so that's something that should always be considered when thinking about sharing storage space too.

One thing I do however think is that if you own a group, you should be able to share storage with that group regardless of your pledge. But that would be a separate issue.

**Comment by JackTheFoxOtter** [comment]
Additionally, the team is planning to allow gifting subscriptions for other users https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/601#issuecomment-1808591213, so this might be something that can be addressed through #601.

**Comment by Banane9** [comment]
> The storage given doesn’t scale linearly with the cost of the tiers, so this can be pretty harmful if say I gave out 5GB each to 18 people who all now don’t need to subscribe. That’s $90 a month the team would be losing out on across all of them which could really add up if everyone could openly share storage like that.

That's 18$ a month they'd be losing out on, not 90$ 👀

To be 90$, they'd have to be at the 5$ tier, meaning you'd need to share 25GB with them - which you could only do to ~3 people, only losing them 15$.

**Comment by shadowpanther** [comment]
Or think of it this way - one $20 subscription where two people use 50G each or two $10 subscriptions where the same two people use 50G each. Nothing is lost, and an additional $10 is gained because the second person is unable to use Patreon or pay in any other way (for example, a person loving in Russia).

**Comment by Banane9** [comment]
As the tiers stand right now, up to 39€ a month you pay about 20 cents per GB, dropping to 14.5 cents per GB for all shareable tiers. So on a pure "cost per GB" measure, they'd actually make the same or *more* money by allowing lower tiers to share storage too.

**Comment by Frooxius** [comment]
I'm sorry, but we do not plan to allow this feature on all tiers. It's designed to be a power user feature and it's priced accordingly, to keep things economical on our end. We might revisit on which tier we allow this once we have more numbers from running the servers, but we're very unlikely to allow it for all tiers.

You are correct - if people pool storage too much, we'll get less subscribers. Meaning it's a double whammy that while we get less income, at the same time each user becomes more expensive on our end, because the average utilization per user goes up. It's not even mainly the ongoing storage costs themselves, but a lot of related operations (API servers, blob operations, compute) that users do with that storage that cost us money that end up making a chunk of the cloud bill and something you need the factor in.

That means we're able to pay fewer people on the team, which affects the development of the software and potentially our ability to keep the lights on.

Which means that if we were to do this, as a consequence we might have to increase overall prices for storage or give you less storage - which means that it's less storage you have for sharing, unless you pay more. And it also means now everyone else gets less storage as a result.

**Comment by shadowpanther** [comment]
> if people pool storage too much, we'll get less subscribers

What about allowing to share storage in the same increments as the tiers go, @Frooxius ?
For example, one person paying $10 (50G) would be the same as the same person paying $5 (25G) and another person paying $5 (25G). Or 10 people paying $1 each for 10*5G. Same space used, same income. The only difference is the amount of subscribers, but does that matter? And I suspect you'd be able to actually save a bit on Patreon fees for the lower tiers.

I guess it would be the solution to gifting subscription tiers #601.

**Comment by Frooxius** [comment]
@shadowpanther You can't just look at how much the storage itself costs, but you have to look at how much the person costs overall with active utilization of the platform - keep in mind there's other services and overhead to run, which are not directly billed - API servers, compute, networking, licenses and so on. I've outlined this a bit in my post above.

We also don't know if people would follow this pattern, where they pay for 2 people worth of utilization to offset the difference - if they are willing to do that, then having option to gift tiers would work better there. If they don't follow this pattern, then our average revenue per person goes down - it means the infrastructure ends up costing more per person on average, which means less funds that we can put towards paying for other services and paying the team - which means we might need to increase overall prices per GB to keep things balanced.

**Comment by shadowpanther** [comment]
@Frooxius and that's why I'm proposing to only share storage in at least 5G, maybe bigger, chunks, following Patreon tiers.

Because currently nothing is stopping a person who is paying for $5 tier from downgrading to $1 and subscribing 4 additional alt accounts for their friends. It is exactly the same cost for you - $5 in one subscription, divided in $1 for 5 users or five $1 subscriptions. All overhead is still there either way, the cost and income stays the same. The only difference is one person paying for 5 people with 1 subscription (less Patreon fee) or with 5 subscriptions (more Patreon fee for you and more complications for that person).

The chunks here would stop people from giving 25 times 1G to 25 people, and that would save your overhead from going through the roof.

Maybe additionally you could limit the number of people you can share with based on the tier to stop $20 subscribers from sharing with 20 people.

And of course one $5 subscriber who shares 5G to one other person is better than two $1 subscribers, paying each for themselves.

I myself am willing to actually up my subscription from $10 to maybe $15 or $20 to stay fair and keep my Headless access and badge benefits if there would be a way for me to share just a bit of my unused storage with a couple of people who can't pay for themselves because they ended up on the wrong side of the barricades in the ongoing war.

**Comment by Frooxius** [comment]
@shadowpanther There are other perks associated though that might prevent the downgrade. I don't think that particular pattern is likely. Like it can be something that can sound good on paper, but won't translate to practice - and like I said, you can't be looking at just the storage itself.

The gifting would be probably way easier - and more economical for us too.

I'm not really looking into getting too deep into this - there are other numbers and calculations that we have internally and some more data we need to gather. Like I said earlier, we might revisit where we offer this feature in the future once we have more data and see what works, but we have to be careful with it and make sure we stay in our margins.

We also don't want to end up in a scenario where we're like "Oh you can share this on all tiers now" and then the numbers look bad and we'll be like "Ooops, nevermind, we're taking this perk away from you now" or "Ooops, sorry, you get less storage now and have to pay more".

**Comment by snootjr** [comment]
Part of why I signed up on a high teir was to be able to share my space. If I now lower my teir since I am unable to share it. Does this not hurt the bottom line also? why not let the 50gig and up share 5 gigs with one person?

**Comment by troyBORG** [comment]
> Part of why I signed up on a high teir was to be able to share my space. If I now lower my teir since I am unable to share it. Does this not hurt the bottom line also? why not let the 50gig and up share 5 gigs with one person?

Yeah maybe setting a limit on how much you can share for the lower tiers.  Even something like 5gb. 
Either 5gb to one person, or maybe gifting 2.5gb to two people?

But the Gifting Subscriptions would be a very nice thing.
