### ISSUE TITLE
MeshCollider not triggering collision pulse when contacting other colliders

### ISSUE THREAD

**Issue by squidge-in-the-fridge** [Yellow-Dog-Man/Resonite-Issues#742]
### Describe the bug?

When contacting a MeshCollider, other colliders such as CapsuleCollider, BoxCollider, or another MeshCollider do not output a pulse, and neither does the the contacted MeshCollider.

### To Reproduce

Drag and drop a MeshCollider component onto the OnContactStart flux node and create a PulseDisplay from its OnEvent output to see the detected pulses, which end up not being anything

Demonstration: resrec:///U-1OSx2bnHcMi/R-493d9745-646d-4cfe-a2cc-e9d8f7fd3444

### Expected behavior

The contacted MeshCollider and the contacting collider should both output a pulse on contact

### Screenshots

https://cdn.discordapp.com/attachments/1165039682778837062/1176487906236432487/Resonite_3hSZx7TfS5.mp4

After recording this I realized both the MeshCollider cubes ended up being set to static, which wouldn't have resulted in a pulse, so I set one of the MeshCollider cubes to active, and after touching the static cube, it still results in no pulse output

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[SHPONGLEOID - 2023.11.18.1263 - 2023-11-21 06_37_51.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13425861/SHPONGLEOID.-.2023.11.18.1263.-.2023-11-21.06_37_51.log)

### Additional Context

My use case for needing colliders is making a parkour system for characters that detects whether the lower half of the player is making contact with the world or an object, and enabling certain logic if contact is made. I have a few baked mesh files of buidlings that I want to use, but with MeshColliders not outputting signal on contact, I'm only able to use my system on unbaked primitives at the moment, or am forced to use raycasts.

I'm not sure whether this is developer intention or not, due to the potential performance implications of MeshColliders. It doesn't seem to be too performance impacting for the meshes I'm using; my character collider can walk around in the relatively low poly buildings I've imported and I notice no performance impact at all. If performance consideration is an issue, perhaps MeshColliders can stop being able to set as active past a certain polycount.

### Reporters

meeshuggah

**Comment by Nytra** [comment]
I think this is maybe intentional. One thing you can do instead is plug the BoxCollider into the OnContactStart node, then it will correctly give you events when it collides with the MeshCollider.

**Comment by squidge-in-the-fridge** [comment]
I should have labeled the boxes in my video better, I named them in the inspector but didn't put any text floating above it for whatever reason, I think it escaped my mind while I was making it. If I remember correctly, the first box to the left is a static BoxCollider, the one after that is an active BoxCollider. Both give pulses when contacting eachother and the player's collider, but neither give or receive any pulses when touching a MeshCollider.

**Comment by Nytra** [comment]
In my testing, a Static BoxCollider can collide with a Active MeshCollider. However no other combinations of BoxCollider and MeshCollider will work.

**Comment by squidge-in-the-fridge** [comment]
You're right, I'm able to get pulses by setting the MeshCollider to active and having the player collider be set to static. Somehow inverting the impacting collider to static and setting the receiving collider to active works, where the opposite doesn't. Weird stuff 🤔
Thanks for the independent testing. Using that info, I *could* do a hacky workaround and make a cylinder in Blender and use its mesh in place of a CapsuleCollider, but it'd just be that, a workaround. The base functionality of the primitive colliders only working on active MeshColliders makes me think even more that there's something buggy going on.

From what I hear, using active MeshColliders is something to be avoided like the plague because of the computational expense involved. Using them is probably the exact inverse of what I'd imagine developer intention would be though, and definitely the inverse of optimal performance. For my use case, doing that would make the literal entirety of the world listen every frame to see if it's touching a single player, rather than listening to a single player to see if they're touching the world. I lost a decent 10-15 or so fps just by having a single building mesh be set to active; to do a whole city would effectively crash/softlock the game due to how slow it would be.

**Comment by Frooxius** [comment]
This is intentional, MeshColliders are always passive because of their complexity, you cannot use them to actively listen for collisions like the other simpler colliders.

MeshColliders in particular can be very complex, with their complexity varying on the used geometry, but generally you would not want to use them like this - everything will crawl to halt very quickly.

They are also a bit "special" in other ways - they have no volume, unlike other collider types. They're a thin sheet of triangles.

**Comment by squidge-in-the-fridge** [comment]
> MeshColliders are always passive because of their complexity, you cannot use them to actively listen for collisions like the other simpler colliders.

I'm not wanting to use active MeshColliders at all, but the way things are right now, all MeshColliders have to be set to active in order for any collider to be able to produce any signals at all. I think the listen settings for the MeshColliders are inverted. 

Nytra and I found from our tests that we can get a signal from a static primitive collider when it hits an active mesh collider, but not from an active primitive collider hitting a static (passive) primitive collider, as I'd imagine things should be. As things are right now, any MeshCollider has to be active in order for any collider to get any pulses from contacting it, and the only pulses that happen are on the static collider. 

In the video below, the capsule on the right has an active MeshCollider while the box on the right is a static BoxCollider. The active MeshCollider isn't outputting any signal, but it still is doing a check every frame in order for the static BoxCollider to receive any signal.

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/136508754/76a3283e-789f-441e-9386-b90ad54f2cbf

I suggest reopening this and investigating further, something definitely feels off with any and all MeshColliders having to be active to give any pulse. I can't progress in the project I'm doing until an active primitive collider can pulse from contacting a passive MeshCollider, which doesn't seem to be working as of posting this.

**Comment by Frooxius** [comment]
@squidge-in-the-fridge What you describe is still an intentional behavior.

As I described above, MeshColliders are treated differently from other types of colliders in the physics system, in order to handle interactions between colliders efficiently. Part of this is the ability to produce collision events like that. The behavior you're seeing is result of this special handling.

Active colliders contacting passive MeshColliders and generating events easily results in computational "explosion", which makes make framerate grind to halt.

Because of that, we cannot and will not make this change, I'm sorry.

I would recommend either re-architecting your project or use the active MeshColliders very carefully. Generally it's strongly discouraged to use MeshColliders for any kind of signalling or events and instead use a collection of primitive colliders or convex hulls at worst.

**Comment by squidge-in-the-fridge** [comment]
Interesting, I wouldn't have figured it would have been that computationally expensive, since my PlayerCollider was able to collide with a whole baked city mesh of about 50k triangles (sized to scale) without any problems, I think that's why I thought this was a bug. I'm guessing that's computed differently than getting OnContact signals, or that it's localized to the triangles themselves or something. I'll try using moving short raycasts or something similar instead. Sorry for the trouble 🙏

**Comment by Frooxius** [comment]
The player collider collisions and generating events are two different things. 

In that case, the player collider is the "driving force", behind those collisions, while the mesh collider takes more passive role. In order to produce events, it would need to have additional handling, which would increase how many computations need to be performed.

Part of that is also that typical use of mesh colliders is to provide large collisions to the environment, props and so on, but generally you're not listening to events to those on the colliders themselves, so they are optimized for that purpose.

The other aspect is that mesh colliders are extremely variable in performance depending on the particular scenario. What matters a lot is the relative density of the mesh vs the colliding body. 

During integration of BEPUv2, there was a point where passive mesh colliders would produce events like that. However that had to be removed, because touching a dense passive collider would make everything freeze up with the computations. Because of that they were excluded from that handling altogether.
