### ISSUE TITLE
Storage sharing is nonfunctional

### ISSUE THREAD

**Issue by VirgilCore** [Yellow-Dog-Man/Resonite-Issues#765]
### Describe the bug?

a friend of mine was sharing their storage with me so i could continue to work on the stargate system, but a week ago the storage sharing broke and now they cant share storage with anyone and nor can my other friend
so i cant work on anything because i have no cloud space now

### To Reproduce

attempt to share storage
recipient never receives storage

### Expected behavior

attempt to share storage
recipient receives storage

### Resonite Version Number

N/A

### What Platforms does this occur on?

Windows

### Log Files

N/A

### Reporters

@.micro. @climber._ @peterthethinker

**Comment by Ardescar** [comment]
Hello :)
Do they still have the correct Patreon Level for the storage sharing?

**Comment by Frooxius** [comment]
We need more information on this:
- Ideally what is their account, so we can check the status
- How did they share the storage (what commands they used)
- How much shareable storage they have on their account? Which Patreon level they are at? They need to run /getBenefits command and check the output

**Comment by ClimberJ** [comment]
I am the friend. I have the Trailblazer tier, which currently only lists storage as a benefit. I remember that it was shareable storage when I signed up, but I am not 100% certain about that. Also, I was able to share storage with my group.

**Comment by Frooxius** [comment]
If that's the case, then this is not a bug.

Shareable storage is available from tier Builder and up, not below. It was never available on lower tiers. If there is anything that's indicating otherwise, you can point us to it, but we haven't changed this on our end, user shareable storage was Builder and up from the beginning.

Trailblazer and up can share storage with groups, but not users - specifically because they allow creating groups.

**Comment by VirgilCore** [comment]
Climber was not the main friend who was sharing storage originally.
