### ISSUE TITLE
Simple User Interface

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#81]
### Is your feature request related to a problem? Please describe.

by default the UI is a bit all over the place and confusing for a lot of users

### Describe the solution you'd like

Create a new default user interface that is very simple and hide all of the more complex features behind a developer mode toggle in the settings page

### Describe alternatives you've considered

No alternative has been considered

**Comment by ProbablePrime** [comment]
Hey, Thank you for making this issue.

Unfortunately, we the team feel like making a separate user interface A.K.A. a "Simple Mode" is out of scope for our Project. 

We understand, that our UI is rough and problematic, that's why we're working on improving it every day. Rather than creating two UIs that need to be maintained our focus is on making the standard stock UI better for all users. 

This includes users who aren't technical or do not want to build.

For feature requests like this, it is much better to come up with specific areas of improvement you'd like to see rather than suggesting an outright replacement.

Due to these factors, I am unfortunately going to have to close this issue as not planned. I do thank you for the time taken to make it though.
