### ISSUE TITLE
Body Node Slot In Children Node Causes Crash on Deleting the Input Slot

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#821]
### Describe the bug?

The `Body Node Slot In Children`  node will crash a user whenever a valid input slot is deleted, then the output is observed.

### To Reproduce

* Create a `Body Node Slot In Children` node
* Set its `Node` to any valid node **except** `NONE`
* Pull out an input node
* Create an Empty Object
* Put the reference to this Empty Object on the input
* Pull out an output node from the `Body Node Slot In Children`
* Delete the Empty Object
* Pull out an output node from the `Body Node Slot In Children`

This will cause a crash for the user performing the action.

### Expected behavior

The user should not crash.

### Screenshots

![Resonite_ILJcX7vk3z](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/d820a603-b67f-47b5-9e83-94ca7d9cfc72)

### Resonite Version Number

2023.11.28.1365

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[BodyNode Slot In Children - 2023.11.28.1365 - 2023-11-29 02_49_55.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13498947/BodyNode.Slot.In.Children.-.2023.11.28.1365.-.2023-11-29.02_49_55.log)

### Reporters

LuxKitty, Nytra

**Comment by Frooxius** [comment]
I've started investigating this one and it's actually a bit trickier than I initially thought.

The issue here is that the input node doesn't update its value when the source object is destroyed. This results in the object still being accessed, even though it's gone.

The problem is, that we do not have a mechanism to get notified when arbitrary world element gets destroyed, so we can't hook into that to ensure that the reference gets explicitly cleared up.

I'll add a filter, which will ensure that the reference gets nulled at least, but problem with that is that change event won't be triggered at all times, depending on the type of object being referenced.

**Comment by Frooxius** [comment]
Not sure at this point. There's lots of ways to potentially solve this.

The data model rewrite could solve it, as it could introduce new mechanisms for stuff like that.

**Comment by Frooxius** [comment]
Fixed this in 2023.12.13.87, thanks for report!
