### ISSUE TITLE
Dashboard is impossible to orient in desktop mode

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#836]
### Is your feature request related to a problem? Please describe.

Users can manipulate the dashboard in vr, and this placement is saved between sessions.  Desktop users cannot manipulate dashboard orientation.  Consider the following case:

- A user is in vr, laying down, and moves their dashboard up overhead
- they exit like this
- their next session is in desktop mode, and they attempt to make use of a facet which relies on the dashboard's orientation, such as mirror facets

In this case, the user would observe the mirror facing down pointed at their head, when they may have wanted a frontal view as is default, with no means of correcting (barring some complex effort on the facet developer)

### Describe the solution you'd like

desktop users able to manipulate, or at least reset, dashboard placement

### Describe alternatives you've considered

one can work around this by getting into vr and correcting it but this is not always viable

### Additional Context

zangooseoo

**Comment by Frooxius** [comment]
I am confused by this issue. Dashboard is projected flat in the desktop mode on the screen. There is no need to manipulate or move it around, because it's not an object in the world that you can interact and move around independently of your view - it's always aligned to the desktop view.

Are you seeing something else?

**Comment by gentlecolts** [comment]
That's why it's not obvious, but if you want to see the issue, add a mirror facet to your dashboard, for example.  Even in desktop mode, the dashboard retains its position from the perspective of facets like this, which means it's possible that they end up stuck at an awkward angle that can only be corrected by going into vr

**Comment by Frooxius** [comment]
That's an issue with the mirror facet - it is its responsibility to render from appropriate location.

In desktop, the dash is not a physical object that you can manipulate in 3D space - it's projected onto the screen. There is nothing to orient or move around.

Any facets and other user made content and tools need to account for that - that's their responsibility to work with how the systems are designed.

**Comment by gentlecolts** [comment]
Perhaps this is me just not understanding how the mirror facets work but it seems to me like their sense of position comes from the dashboard itself.  It's not clear to me how they'd then be retaining that position from a previous vr session when in desktop mode if it's not being miss-reported (or unreported?).

Perhaps worded a little differently, if the dashboard has "no" position/orientation in desktop mode, how would such a facet then approach correctly handling this case.  I'd imagine the correct solution as is would be something like "if desktop mode then place at front + some distance", but i suppose then that requires both the "if in desktop mode" part (I assume some facility for this exists?) and then some concept of both the proper orientation in user space and figuring out a proper distance.

Again, I will openly admit ignorance here, as I've not messed around with much in terms of facets and user space, but it seems like it'd be more elegant to me, and easier for facets that do rely on dash position, if some default position were used for the dash in desktop mode, to allow these kinds of facets to "just work", rather than shifting that burden onto users to implement in potentially inconsistent ways

**Comment by Frooxius** [comment]
That's up to the facet. They could for example choose to position the camera based on the user's head position and orientation, instead of the dash position.

In desktop, the dash does not have a well defined position/rotation in the worldspace, because it is projected orthographically on the screen - in other words there's not really anything to position/rotate for the user.

It's how it works and we do not have plans to change how dash operates in desktop in this aspect.

Any user content and tools need to work with how the dash works in desktop. There's tools to do this already, but implementing that is up to the authors of that facet.
