### ISSUE TITLE
compile AOT instead of JIT

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#84]
### Is your feature request related to a problem? Please describe.

currently there are a lot of performance issues when it comes to loading world and items

### Describe the solution you'd like

similar to what other social vr platforms do, allow for a way to compile worlds and items to an AOT format instead of a JIT format as this would drastically increase performance. maybe even allow for these modes to be hot swapped depending on when they are edited

### Describe alternatives you've considered

N/A

**Comment by ProbablePrime** [comment]
Hey,
Thank you for making this feature request.

This is unlikely to be suitable at this time as Resonite objects and items are not compiled to either JIT or AOT in the traditional sense.

Performance is very important to Resonite but issues like this are difficult to reason about as they aren't really suitable. Performance is more of a bug than a feature request. 

When it comes to performance, its better to be handled as a bug report for an individual area you've noticed.

Due to the unsuitability of this issue, I will unfortunately have to close it as not planned. This does not mean performance is not important or not a focus, it just means that this approach is unsuitable.
