### ISSUE TITLE
could u maybe add poiyomi toon shader

### ISSUE THREAD

**Issue by Skype-Skype** [Yellow-Dog-Man/Resonite-Issues#842]
### Is your feature request related to a problem? Please describe.

im not sure tbh

### Describe the solution you'd like

i would like the ability to use poiyomi toon on avatars because i know how to use it and its pretty

### Describe alternatives you've considered

nothing tbh other shaders are complicated

**Comment by JackTheFoxOtter** [comment]
Instead of asking for adding a specific Unity shader, I suggest asking for specific shader features instead. Since the plan is to eventually move to a custom renderer I'd assume adding any Unity specific shader would cause a lot of headaches and potentially content breakage in the future once Unity is replaced as a renderer.

**Comment by ProbablePrime** [comment]
Thank you for making this issue, Unfortunately, we're unable to provide Poiyomi's shader on Resonite. Our plans for the engine and shaders/rendering, won't allow for Poiyomi's to be compatible. This is due to our target renderer not being compatible with Unity shaders.

While, this may be concerning for you, please do remember that Poiyomi's shader while fantastic, just provides a visual look. Many other shaders and types of shaders are capable of providing this look. 

For now I encourage you to explore our existing shader options and to ask in our Discord if you need help setting them up. I'm sure someone can help you get the look that you're after.
