### ISSUE TITLE
New Component: Boolean One-Shot Float Driver (Bool triggered From-To LERP?)

### ISSUE THREAD

**Issue by MahSandwich** [Yellow-Dog-Man/Resonite-Issues#856]
### Is your feature request related to a problem? Please describe.

There have been a number of times where it would have saved a bit of work to use a single component to do a LERP triggered from a Boolean value. This would be useful for Attack and Decay in Audio as well as when working with Colour, Light, Motion, etc.

### Describe the solution you'd like

A component which has the following inputs: 
Float From
Float To
Speed
Only For User (nullable)
Bool Input (to trigger the single-shot)
Enumerator to determine if it should trigger 'On True' or 'On False' or 'On Change'
Bool to determine if it should auto-reset when the target is reached or if it should hold the drive at the 'Float To' value

And then the output being a Float Driver.

It would probably be a good idea to directly support more than just float but for now being able to drive a Value Gradient Driver with the Float would be a great help.

### Describe alternatives you've considered

Creating it using multiple nodes (which gets messy when you need a lot of copies)
![BFOSD](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70416315/5ac8daeb-6f8c-4d90-a3d6-989a8fdb950e)

**Comment by JackTheFoxOtter** [comment]
I believe what you're looking for already exists as the `Tween` node under in `Action`.
![2023-12-08 14 19 54](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/8157358f-c477-4db7-b842-eefe65716ab8)

On Impulse, it interpolates the value at `Target` from `From` to `To`, taking `Duration` seconds to get there. The `Curve` enum determines what kind of interpolation to use (linear, smooth etc).

If you leave `From` empty, it will take whatever value `Target` before starting the interpolation.

Tween does, however, not drive the value. If you want a temporary drive you can start and stop on Impulse, use the FielfHook node in `Core` instead.

**Comment by MahSandwich** [comment]
I was primarily aiming for it as a Component and not have to use any Nodes.

**Comment by MahSandwich** [comment]
So my screenshot has it set up as I would have it as a component. If I'm going the node route I need a float output that I can string to other nodes. The Tween node in that case requires that I set the output reference to the value of a float input node or similar workaround and is more work, seems to result in additional nodes, and seems to have no benefit in behaviour. It's a useful node but not in that case. (Value Multiplexing with a Conditional Node instead of using a Boolean Value Switcher Component because when using nodes it's usually less work to keep using nodes than mix components and nodes.)

**Comment by Frooxius** [comment]
I don't think this is something we'd likely implement, since it's a bit more complicated behavior, that you can already implement with ProtoFlux. 

The main reason is that this doesn't scale - there's virtually infinite amounts of functions that you could make with ProtoFlux like this, all with different ways and variations of operation - we won't be able to hard-code all of them into components. So question would be, why this one and not others?

Or rather, why this one, since it's a functionality you can already achieve? 

If the main goal is convenience, a more generic solution would be nested nodes once those are implemented: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/564

WIth those you can package the behavior into a single node and re-use across a number of objects more easily. One thing that I'd want to explore there is being able to use nested nodes with the component interface, which would effectively allow you to make your own "Components" out of nodes.
