### ISSUE TITLE
Screenshots are slower to process and render in-world compared to previous versions

### ISSUE THREAD

**Issue by ohzee00** [Yellow-Dog-Man/Resonite-Issues#871]
### Describe the bug?

When taking a picture via screenshot gesture, camera or anything that spawns in a photo into the world, the loading takes a fair bit of time, roughly 10-20 seconds.

### To Reproduce

1. Take a picture
2. Wait for picture, notice it takes a fair bit of time (testing for me was in the 10-20 second range)

### Expected behavior

For the taken screenshot to load in quicker like it has in previous builds.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33611545/ac214608-dd25-4bde-b0fb-2abc573f8b39

### Resonite Version Number

2023.11.28.1365

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-V75BHJO - 2023.11.28.1365 - 2023-12-10 18_51_00.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13629646/DESKTOP-V75BHJO.-.2023.11.28.1365.-.2023-12-10.18_51_00.log)

### Additional Context

"I think there is increase in encoding time with updated libWebP due to the security patch."

### Reporters

Ohzee

**Comment by Frooxius** [comment]
This is expected behavior.

When you take a screenshot, it has to be encoded first from the raw data. So the process goes something like:

`Transfer image from GPU to CPU -> Convert image data for encoding -> Encode image data (e.g. into WebP, JPG or PNG, this typically takes a bit and it can wait in a queue a bit for higher priority items to be done first) -> Import the encoded data -> Generate metadata -> Generate variants -> Image is shown`

When you import existing image, it's already been encoded, so it doesn't need to do some parts of the process. So you just get:

` Import the encoded data -> Generate metadata -> Generate variants -> Image is shown`

A bunch of compute expensive steps are not necessary in that case, because they were already done in the file, therefore the overall process is shorter.

**Comment by ohzee00** [comment]
Aw heck fair enough, I was hoping it was some oversight given how long they take. Thank you for explaining it, it is indeed more complex than I thought.

**Comment by VirgilCore** [comment]
> -I believe that finger photos used to be significantly quicker to process

I agree, back on the old platform, photos were almost instant. I have noticed on Resonite that photos take a significantly longer amount of time to process.

**Comment by Frooxius** [comment]
@shiftyscales I think there is increase in encoding time with updated libWebP due to the security patch.

That's something that can be looked into as a separate issue, but it's different issue from being presented here - encoding still has to happen, so it will always take longer to capture them, than to import already encoded ones - that's expected behavior.

**Comment by Frooxius** [comment]
@shiftyscales I'd rather a separate issue for that specifically to keep things clean and organized please.

This issue, text, repro steps and everything is for something different and changing what the issue is about mid-way makes things a bit harder to work with.

The issue describe here is indeed by design.
