### ISSUE TITLE
Protoflux to show if the current session is a headless session

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#896]
### Is your feature request related to a problem? Please describe.

currently there is no practical way to detect if a session is headless, and it would be useful to know this information. Example the creator jam culling system has a checkbox for headless session optimizations. If a protoflux node existed that could inform them if the session was headless they might be able to remove that checkbox and have it work automatically

### Describe the solution you'd like

A protoflux node that would state as a boolean if the current session was headless or not (or maybe a node that could specify the current type of session if that fits future plans better aka future new session types)

### Describe alternatives you've considered

there is really no good way of checking this at the moment... ive done some checks against the host user without finding anything sensible

**Comment by shadowpanther** [comment]
`Host User -> User Root Slot -> Is Null`?

Because unless the host is currently respawning, the only case where the host doesn't have a representation in the world is when the host is a headless.

Or, even better, `User Head Output Device` would just output `Headless` for the headless. At least that's what the legacy documentation says right now.
