### ISSUE TITLE
SetSlotActiveSelf and SetSlotPersistentSelf don't do anything without a bool input

### ISSUE THREAD

**Issue by Banane9** [Yellow-Dog-Man/Resonite-Issues#923]
### Describe the bug?

For some reason the Set Slot Active Self and Set Slot Persistent Self nodes don't do anything when they don't have an input wired up to them.

### To Reproduce

I made a reproduction item that also includes the other slot info setting nodes: `resrec:///U-Banane9/R-d164edca-3480-4c95-ae1e-b3908131e53d`

* Spawn a protoflux reference to an active/persistent slot
* Spawn the nodes in question
* Hook them up to the slot reference
* Connect their calls and execute
* The slot remains active and persistent

### Expected behavior

The default for both inputs is `false`, so the target slot should become inactive / unpersistent.

### Resonite Version Number

2023.12.13.87

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

Loading into local home, spawning reproduction item, opening inspector and pressing the Call button, then exiting.

[Reproduction.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13698693/BANANE9-GAMING.-.2023.12.15.22.-.2023-12-18.02_48_54.log)

### Additional Context

Does not seem to affect writes to boolean datamodel stores, or the non-boolean slot info set nodes.

### Reporters

Banane9
isotach

**Comment by Frooxius** [comment]
This is intentional.

Our general philosophy is that when input isn't plugged in, it should have minimal impact on the output and for operations that change state significantly, you need to explicitly provide the desired state.

In case of these nodes it means that you need to explicitly specify if you want the target to be active or not.

**Comment by Stellanora64** [comment]
> This is intentional.
> 
> Our general philosophy is that when input isn't plugged in, it should have minimal impact on the output and for operations that change state significantly, you need to explicitly provide the desired state.
> 
> In case of these nodes it means that you need to explicitly specify if you want the target to be active or not.

Couldn't this possibility affect legacy content that wasn't made with this in mind?

**Comment by Frooxius** [comment]
> > This is intentional.
> > Our general philosophy is that when input isn't plugged in, it should have minimal impact on the output and for operations that change state significantly, you need to explicitly provide the desired state.
> > In case of these nodes it means that you need to explicitly specify if you want the target to be active or not.
> 
> Couldn't this possibility affect legacy content that wasn't made with this in mind?

Generally we'd add an upgrade for old content, which preserved the old behavior when it changes, so it shouldn't. 

If you find cases where it does, make a bug report please and we can look into it.

**Comment by Banane9** [comment]
> Our general philosophy is that when input isn't plugged in, it should have minimal impact on the output and for operations that change state significantly, you need to explicitly provide the desired state.

This is completely inconsistent with practically all other nodes though, which work just fine without providing values that have the default you want. Especially since it's impossible to tell which inputs on a node are actually required, beyond aquiring the intuition that slot modifying nodes probably at least need a slot and so on.

Restricting the use of default values on certain nodes is also entirely arbitrary. Setting a dynamic boolean variable could easily have a bigger impact on what something is doing than setting a slot's active or persistent state.

**Comment by Banane9** [comment]
> Perhaps there’s a different solution for this, like updating protoflux node visuals to indicate which inputs are required for them to function.

Hah, while you were typing that, I was making #926 :D

**Comment by Frooxius** [comment]
> > Our general philosophy is that when input isn't plugged in, it should have minimal impact on the output and for operations that change state significantly, you need to explicitly provide the desired state.
> 
> This is completely inconsistent with practically all other nodes though, which work just fine without providing values that have the default you want. Especially since it's impossible to tell which inputs on a node are actually required, beyond aquiring the intuition that slot modifying nodes probably at least need a slot and so on.
> 
> Restricting the use of default values on certain nodes is also entirely arbitrary. Setting a dynamic boolean variable could easily have a bigger impact on what something is doing than setting a slot's active or persistent state.

I understand that it might be confusing when it goes against your expectations, but that that does not mean it's inconsistent or arbitrary - it just means it's following different rules than what you expected. I would appreciate if you took a minute to understand our reasoning for this.

Like I explained in my initial post, this behavior is consistent with our general philosophy.

If you look at it this way... why should "false" be the default for this node? Should we assume users want to set slots to inactive most of the time? No. Should we assume that they want to set them to active? No. They are both roughly equal and user can want either. 

These nodes specifically also directly result in significant change in state, therefore we require the user to explicitly provide what they want the node to do, rather than assuming on their behalf.

Dynamic boolean variable can have big impact down the line - but it doesn't directly by itself, which is the difference. We are only looking at what the node does itself in isolation.

Setting a variable to a default value for the datatype is pretty common operation - one that users will want to do often enough, that it's notable over providing value, therefore this tips the scales on this.

I think having indication for which ones are required is a good solution to this.

**Comment by Redd56** [comment]
Personaly im more of a fan of option 1 though option 2 does have extra benefits. Ie: when an async task is not valid, infinite loops, etc
