### ISSUE TITLE
Component for bounds checking

### ISSUE THREAD

**Issue by NezzKryptic** [Yellow-Dog-Man/Resonite-Issues#951]
### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

A component alternative to the IsBetween protoflux nodes to check if values are within bounds, primarily in regards to float3, floatQ, int3, color, etc. data types.

### Describe alternatives you've considered

Similar functionality can be built using ProtoFlux, but can quickly become overly-complex when the data needs to be sourced in multiple locations, or when a single value needs to be checked against multiple bounds.

**Comment by Frooxius** [comment]
This has similar problem as other issues that ask for things from ProtoFlux to be implemented as components - we are duplicating existing functionality and there doesn't seem to be necessarily a good reason to do so, which is generally a bad practice.

Since you don't even provide reason/problem for this to be implemented, I'm inclined to close the issue - we're not going to spend time working on something when there's not a reason provided to do so.

ProtoFlux is designed to handle more complex setups too, while components are not, so generally you should use it instead for this. Components can only handle simpler, more direct behaviors and interactions, they will break down once you start doing something more complex.
