### ISSUE TITLE
Add per eye override options to AvatarUserRootOverrideAssigner

### ISSUE THREAD

**Issue by TisFoolish** [Yellow-Dog-Man/Resonite-Issues#958]
### Is your feature request related to a problem? Please describe.

On my avatar you can remove each eye and the view for each eye follows via trickery with portals. For the most part this just works, but it has a lot of caveats.

I have to render the view twice over because I'm using portals, incurring a performance penalty.
Some effects and other portals break when looking through them.
My setup only "just works" with the index headset and looks "weird" in other headsets.
Overlap can be visible if the eyes aren't removed in a certain order.
It is a massive pain to set up and make it look good.
It can not be easily moved to new avatars.

### Describe the solution you'd like

The AvatarUserRootOverrideAssigner component having the ability to override the view for each eye independently, not just the whole view.

### Describe alternatives you've considered

The portal system I have is the alternative. It is fraught with issues

### Additional Context

I've been using the portal system for 2 years now, so at least with me there is no issue it making me sick. 

There are also many fun 'tools' that could be made, eg an eyeball that selfparents to a user's head bone and when it does it overrides one of their views (which one depending on if the x coordinate is signed or not).

**Comment by Frooxius** [comment]
We cannot add this unfortinatelly, because the view is rendered as whole, using single pass rendering to achieve better performance. 

The consequence of that is that the eyes are not independent of each other.

Given that splitting eyes like this is also very niche and genrelly you shouldn't do it (it will make a lot of people very sick very quick), we wouldn't invest development time into this. Sorry.

**Comment by TisFoolish** [comment]
The use cases for AvatarUserRootOverrideAssigner are easily as niche and
can also make a lot of people sick, yet it already exists.

The big issue is the single pass rendering. I know that unity allows for
multi-pass rendering, but I don't know if it is possible to
 switch at runtime. If you can switch then the performance penalty would
only exist when you're using the component and even then I bet it'd still
be less than having to render two portals plus the regular view.

**Comment by Frooxius** [comment]
I strongly disagree with those two being equivalently niche. 

The user root override let's you move the entire user - moving or constricting someone's body isn't too crazy in realm of what can realistically happen to a person - being in a vehicle or strapped into something can happen. Sure, you can make user sick with those, but at least they are realistic possibilities and can be used for those.

What you propose is equivalent to somehow taking each eye out of users head and moving them out independently. That's not something you can really experience IRL. And generally a huge no-no for VR game development, unless you're really making some weird eye hurty effects.

Those two are nowhere near as equivalent to niceness.

If you had some practical usecases of this, that could potentially help.

However the other side still remains - we can't switch from single pass to multipass at runtime easily.

If we really wanted to, there are ways around this, but those require a significant amount of additional engineering.

That is another reason why the root override exists - it's been easy to implement and fits with the whole system, while also having more practical uses.

Conversely I don't see this one as being anywhere as practical, while simultaneously being more laborious to implement.

Therefore the answer is still no.

**Comment by TisFoolish** [comment]
> moving or constricting someone's body isn't too crazy in realm of what can realistically happen to a person - being in a vehicle or strapped into something can happen

People use anchors for stuff like that, I've never once seen someone use AvatarUserRootOverrideAssigner for anything like that. The most common usecase I've seen for it is people detaching their head, which is "not something you can really experience IRL".

On that note, shouldn't we be *trying* to figure out ways to do and experience things in VR that aren't possible IRL? Yes, split eye can be nauseating, but of the dozens and dozens of people I've let try out my avatar, only two actually reported feeling nauseous. Most were just enthralled with the idea of moving their eyes around. That doesn't even include the people who could have shown it to their friends as I freely allow others to save my avatar.

Also, a real world use of such a feature would be the ability to let people adjust where their eyes are on their avatar. Another is game mechanics, eg a game where each eye sees a different room that you must align using your hands. Alternatively literally have one eye be an eye in the sky and your other be normal for strategy type games. Educational: being able to experience sight like herbivores and other prey animals do. Memes (already talked about). Avatars with intentionally cartoony proportions. Or avatars with odd features (an avatar that was one of the MMC winners is what inspired my eyeballs. It was an avatar where the left eye was in the hand).

**Comment by Frooxius** [comment]
You're missing the point. Whether people use one approach or the other, moving entire body is way more reasonable than moving eyes independently.

Generally you should never screw with people's eyes on their avatar - their positioning is determined by the VR headset they're wearing. Deviating form this is strongly discouraged for most use-cases. This is a general practice for VR development for general population. It's not just nausea, but potentially headaches over long term use and so on - the point being, it's strongly discouraged to do it.

You can already adjust where eyes are on your avatar - you just can't do this independently - and even that is generally discouraged, because it deviates from the natural neck movement, which can be disorienting.

Even cartoony avatars should keep the stereostopic rendering intact for general use.

Most of those use-cases can be achieved with existing methods if you really want to experiment, they are sufficient for that. They are too niche for us to prioritize this over other features - these uses are just too niche for us to put development time into them over other features.
