### ISSUE TITLE
Delay Protoflux node locking up the game engine, crashing users, and completely killing headless servers and making them unusable.

### ISSUE THREAD

**Issue by RyeTheGooSnep** [Yellow-Dog-Man/Resonite-Issues#998]
### Describe the bug?

When using a delay node, if you are to feed the nodes trigger into the input, and call the node, it will instantly crash your game, and if you do the same thing, but put the next into the input as well, it will lock up the game engine for all users in the world, all audio will continue to work, but the game will be frozen until forcefully closed. If you are in a headless, the entire headless server will completely lock up, and on a linux server, none of the cancel commands or quit buttons will function, and the entire system will freeze and crash, requiring a full restart of the system. On windows, task manager will close the console.

### To Reproduce

spawn in a delay node, the delay seconds int node under flow. Take the protoflux tool, and click and hold on the trigger. Connect the trigger to the input node labeled *. Input an async event node into the input of the delay, and attack a direct call button. On pressing, your game will instantly crash, but no one else will be affected. Alternatively, repeat the steps above, but do not add an async event or call button, but instead take the next output and attach it to the * input node on the delay. The game will instantly freeze up, but not crash, nor unfreeze, and anyone else in the world will also freeze up. Audio will still occur, but the game will not respond until forcefully closed and restarted. If on a headless, the headless will completely lock up, and require a complete restart of the server as a whole, or the console to be closed in task manager, depending on the system used.

### Expected behavior

The delay node should not be easily exploited or able to crash users, and should have a warning for explicit connections that deny use of any of the avaliable functions listed above that only result in the users clients crashing or being locked up.

### Screenshots

![photo_2023-12-25_23-13-25](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147884084/c7d01d6b-3755-4e7f-b064-aca9a345a209)
![2023-10-02 01 32 12](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147884084/39a5b8ee-1259-4c8a-8dba-e81d2c62f066)
![2023-10-12 09 11 47](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147884084/f4133714-8f85-4b96-9060-8a7eea64c9db)

### Resonite Version Number

2023.12.21.1127

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop

### Log Files

Due to the nature of this problem, I haven't been able to get any logs at all other than the standard logs that display no information.

### Reporters

ryethegoosnep
hikari_akimori

**Comment by MahSandwich** [comment]
To note on the linux headless, gui access makes it easier to kill the process, being limited only to remote terminal it gets to be a pain because it's unresponsive even to CTRL+Z

**Comment by shiftyscales** [comment]
This issue is functionality a duplicate of #774. The underlying issue is that ProtoFlux currently doesn't have a mechanism to abort execution when loops like this are created.

**Comment by Krzeszny** [comment]
While the cause of this issue can't get fixed for now, shouldn't that action be just blocked?

Sure, people don't often make crashers, but once in a while someone can think of making a repeating impulse and crash a whole server by accident.i Heck, if I wanted to have an impulse every X async seconds, I'd have use this. (Guess I won't now.)

**Comment by art0007i** [comment]
> While the cause of this issue can't get fixed for now, shouldn't that action be just blocked?

which action? if you want an impulse every X seconds, the solution present in screenshot 2 of this post is valid, as long as you flip the outputs, because if you look closely it's plugging OnTriggered into itself, which causes an instant infinite loop (which hangs the game). Plugging next into the delay will instead cause it to create a pulse every 4 updates.

**Comment by Krzeszny** [comment]
> > While the cause of this issue can't get fixed for now, shouldn't that action be just blocked?
> 
> which action?
Sorry, it seems I wasn't clear enough. I mean that the action of plugging a delay into itself should be rejected (like trying to plug a boolean into an impuse, etc) or cause the nodes to highlight red, if it causes a crash.

HOWEVER, I've just tried plugging a delay into itself like the OP suggested and it doesn't crash or freeze the game. It just doesn't send an impulse at all. I tested:

- fixed integer delay 
- float delay
- plugging Next into input
- plugging OnTriggered into the input
- plugging OnTriggered after calling a delay 

Nothing causes any issues (tested on a self-hosted session with friends). It seems like this issue was fixed at some point.

**Comment by art0007i** [comment]
In single node scenarios maybe you can detect if it's gonna infinite loop but then it's probably more effort than it's worth to implement (since it should be covered by #774 anyway) and for 2+ node setups it's not possible to detect whether it's going to loop infinitely or stop eventually, so it shouldn't cause it to reject.

**Comment by SlyTheFloof** [comment]
🙃
